### ISSUE TITLE
Видимость правил в игре

### ISSUE THREAD

**Issue by Tourorist** [TEHGAM/ADR#254]
Надо бы сделать наличие у нас правил сервера более видимым в игре.

В частных разговорах с нашими разработчиками я уже предлагал привязать ссылку на уже существующую закладку «Правила» (экран карты) на место «Меню групп», то что доступно через ящик со снаряжением и экипировкой. Вместо, потому что функция «Меню групп» и так повсеместно доступна через «Управление отрядами».

Ввиду с возможными трудностями в реализации этого свойства конкретно по моему плану, [longbow](https://github.com/ussrlongbow/) в ответ предложил вытащить правила в отдельное диалоговое окно с кнопками «Согласен/Не согласен». Окно появлялось бы как уведомление после присоединения к серверу, тем самым устраняя незнание правил как потенциальное оправдание нарушителей.

Тем или иным способом, думаю надо что то предпринять в этом направлении.

**Comment by Noart537** [comment]
Можно реализовать: * На карте в кратце; поставить рекламные панели на базе с правилами; транслировать в чат время от времени, по одному пункту. Для наградной, можно попробовать сделать сообщение, когда залазишь, вылазит предупреждение. Еще есть идеи? Или тут уже все вымерли?
