### ISSUE TITLE
Десинхрон маркеров допзаданий

### ISSUE THREAD

**Issue by Tourorist** [TEHGAM/ADR#272]
В некоторых случаях у допзаданий название маркера на карте не совпадает с названием в окне оповещения (см. вложение). Проверил соответствующие файлы самих миссий, внутри вроде всё как положено что наводит на мысль о проблеме в синхронизации.

![Снимок из игры](http://i.imgur.com/WNM9S11.png)

Исток проблемы это всего лишь моя догадка, причина может быть и в другом.

**Comment by Noart537** [comment]
Возможное решение добавить новую строку в каждую миссию над строкой "sideMarker" setMarkerTex....  (на днях проверю)
sideMarkerText = "название миссии"; publicVariable "sideMarkerText";
