### ISSUE TITLE
Дальность повторного появления у техники

### ISSUE THREAD

**Issue by PR9INICHEK** [TEHGAM/ADR#294]
Сейчас стоит 300 метров. То есть, если вы разбили технику, но не до конца, к примеру сломаны все колеса, то техника никогда снова не появится новой, пока от неё не отойдут на 300 метров. Дальность от ящиков терминала до стоянки техники менее 300 метров, а в терминале всегда находятся люди.

Нужно уменьшить данный параметр до 15 м и увеличить время повторного появления у некоторой техники.

**Comment by Noart537** [comment]
Актуально? Если нет, закрывайте.
