### ISSUE TITLE
Поставить скрипт ремонта

### ISSUE THREAD

**Issue by a11archer** [TEHGAM/ADR#3]
Как на Батлфронтте с RW1.

**Comment by a11archer** [comment]
Скрипт позволял любому солдату при имеющихся инструментах за продолжительное время починить технику.
// [] execVM "zlt_fieldrepair.sqf";
// http://forums.bistudio.com/showthread.php?168714-Realistic-repair-script
Нужно бы выяснить стоит ли это делать. Часто крики нужен механик вызваны тем что надо поменять колесо у машины. Это полностью решено скриптом реалистичного ремонта. Можем его переделать чтобы вертолеты и танки мог чинить только механик а остальную технику все.

**Comment by Noart537** [comment]
Механики чинят сразу, другие со скриптом чинят какое-то время? Нужен нам такой скрипт? Можно на голосование вынести, на форуме.

**Comment by GRIDSW** [comment]
+1

**Comment by Noart537** [comment]
Создал опрос http://www.tehgam.com/viewtopic.php?f=36&t=1941 через неделю, решим.

**Comment by Noart537** [comment]
Решили что не нужно. Пока закрываю.
