### ISSUE TITLE
WARNING: Function 'name' - <Игрок> is dead

### ISSUE THREAD

**Issue by PR9INICHEK** [TEHGAM/ADR#300]
Логируется в журнале. Скорее всего связана со скриптом, который показывает экипаж в техники.

Попробую исправить.

**Comment by Noart537** [comment]
Актуально?

**Comment by tym32167** [comment]
Не проверяли, но должно быть актуально. Текст можно поглядеть только в журнале сервера, а сервер пока выключен.

**Comment by Noart537** [comment]
@tym32167  скинь лог боевого сервера. Глянуть что там за ошибки.
