### ISSUE TITLE
Забронировать слот для администраторов

### ISSUE THREAD

**Issue by vosur** [TEHGAM/ADR#302]
Нужно создать слот для администратора, чтобы людей, чьи ID не соответствуют установленным, либо выкидывало со слота, либо вообще на него не пускало.

Порой, очень срочно надо зайти на сервер — что-то протестировать, поставить день, например или еще что — но все слоты заняты.

**Comment by a11archer** [comment]
ищу... функцию типа isAdmin где-то видел. напомните корректное её название если кто помнит.

**Comment by tym32167** [comment]
данная функция не поможет, так как админа выкинет со слота ещё до того, как он зайдет админом. Нужно привязывать к ИД игроков. 
Как работать с ИД https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/scripts/admin_uid.sqf

**Comment by a11archer** [comment]
Ну почему, выкинет только если по прошествии времени видит что нет прав админа. А проверка UID даст слот только определенному человеку. Каждый раз править миссию прописывая UID нового админа некорректно, принято использовать членство в какой-либо определенной группе имеющей роль админа. Чем встроенная группа авторизующаяся по паролю админа не устраивает?

**Comment by a11archer** [comment]
Подготовил принципиальное решение:
в инициализации у персонажа (слота) прописать:
```
if (serverCommandAvailable "#logout") then {
	hint "You are in active admin slot.";
}
Else
{
AdminSlot = Player;
hint "You are not admin, Please leave this game slot or type #login ******  for authentification !";
};
```

а в initServer.sqf
```
if (isDedicated) then
{
 if serverCommandAvailable "#kick" then
     {
       while {true} do
           {
           sleep 30; // разгружает сервер от перегрузки циклами проверки
           WaitUntil {serverCommand ["#kick %1",AdminSlot]; ! (isNull AdminSlot)};
           };
     };
};
```
Пока не проверил.... уверен - ошибки есть. Но принцип с учетом обработки ошибок примерно такой.

**Comment by a11archer** [comment]
Боюсь Unit и имя игрока сопоставить не смогу. AdminSlot (тип Unit) кикнуть не выйдет.

**Comment by a11archer** [comment]
Альтернатива - кикать по Guid

В инициализации Игрока прописать
```
AdminSlot = getPlayerUID this;
```
а в initServer.sqf
```
if (isDedicated) then
{
 if serverCommandAvailable "#kick" then
     {
       while {true} do
           {
           sleep 30; // разгружает сервер от перегрузки циклами проверки
           Switch (AdminSlot) do 
                  case "guid1": AdminSlot = objNull;
                  case "guid2": AdminSlot = objNull;
                  ......
           WaitUntil {serverCommand ["#kick %1", AdminSlot]; ! (isNull AdminSlot)};
           AdminSlot = objNull;
           };
     };
};
```
