### ISSUE TITLE
Вернуть меню выгрузки снаряжения

### ISSUE THREAD

**Issue by Tourorist** [TEHGAM/ADR#304]
Сегодня заметил что нет больше меню в машинах для быстрой разгрузки их содержимого, чтобы освободить место для личного.

Если это действительно неплановое изменение, то возможно проблема связана с недавним исправлением (#289) работы скриптов.

**Comment by a11archer** [comment]
Давай в обработчик вставлю результат действия: будет говорить что вы не Водитель данного транспортного средства. Убирать действие нельзя т.к. это свойство техники а не игрока.

**Comment by a11archer** [comment]
Сорри но я не вижу в скрипте никакой проверки на владельца.
https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/scripts/vehicle/clear/clear.sqf

**Comment by a11archer** [comment]
60% скрипта убили урезав его до нужд вертолета.
https://github.com/TEHGAM/RW6/blob/master/co40_Invade_Annex_2_75b_export.Altis/co40_Invade_Annex_2_75b_export.Altis/scripts/vehicle/setupUnit.sqf

**Comment by a11archer** [comment]
А стало лишь
https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/scripts/vehicle/setupUnit.sqf

**Comment by a11archer** [comment]
и это с троссами вообще не связано... с троссами только комментарий добавили отключив одну строку. весь скрипт точно не переписывал.

**Comment by a11archer** [comment]
как историю правки файла посмотреть? не понятно что совместно с этим правили.
вернуть то через 
строка 17: } 
строка 18: Else 
строка 19: 
20: {  
21:     _unit addAction ["<t color='#3f3fff'>Очистить инвентарь</t>","scripts\vehicle\clear\clear.sqf",[],-97,false]; 
22: };
 тогда не только вертолеты будут с этим скриптом.

**Comment by a11archer** [comment]
где все вышеописанное с владельцем то? вырезано под корень... дайте историю...?

**Comment by a11archer** [comment]
//clearBackpackCargo _unit;
//clearWeaponCargo _unit;
были закомментированы вот все и думали что скрипт не работал. чистились только патроны да личный инвентарь типа терминалов, раций и тд.

**Comment by Tourorist** [comment]
@a11archer, скрипт по-настоящему не работал в одном случае и НЕ-полностью, но работал в другом.

По поводу того что это делалось через принадлежность той или иной техники — это всего лишь моё предложение, в связи с тем что «чинилась» эта функция только после того как игрок побывал на месте водителя конкретной техники.

**Comment by Tourorist** [comment]
Как я помню, единственное что не выгружалось это были автоматы — те запасные, что и в Маршали и в Охотникам всегда есть. Вроде, всё остальное выкидывалось без проблем.

**Comment by a11archer** [comment]
Автоматы не выгружались из за строки 5. рюкзаки из за 4. я  на ветке тестовой (сервер поднят) опробую сейчас код и скажу результат.

**Comment by a11archer** [comment]
проверил, скрипт появился. но 
```sqf
4: //clearBackpackCargo _unit;
5: //clearWeaponCargo _unit; 
```
я не убирал.
проблема с веткой появилась (скрипт лифта) так что надо дальше испытывать. я в понедельник буду продолжать со строкой 4,5

**Comment by a11archer** [comment]
sqf```
clearWeaponCargo _unit; 
```
разкоментировано в [ветке]{https://github.com/TEHGAM/RW2/tree/Lift-path-for-dead-vehicles}

**Comment by a11archer** [comment]
на тестовом ок. насчет доработки скрипта пока беру паузу - владельца техники (последнего водителя) прописать бы.

**Comment by a11archer** [comment]
После слияния Branch ветки уйдет в релиз. Проверку владельца в следующую версию...

**Comment by Tourorist** [comment]
В местной игре у меня тоже работает для всех, как @tym32167 того и хотел или не имея чего и убрал. Я только боюсь как бы в таком исполнении игроки случайно или намеренно себе/другим не сливали загруженное вооружение после долгой поездки.

**Comment by a11archer** [comment]
Ранцы слить нельзя. мы еще не нашли метода защиты. Как и парашюты.
Тестовая версия запущена на Tehgam 2 Test server, пароль единичка. все еще в [Branch ветке](https://github.com/TEHGAM/ADR/tree/Lift-path-for-dead-vehicles)

**Comment by Tourorist** [comment]
Ладно сойдет как есть для выпуска. Закрываю.
