### ISSUE TITLE
Подтирать старые минные поля

### ISSUE THREAD

**Issue by Tourorist** [TEHGAM/ADR#305]
![Эти самые](https://raw.githubusercontent.com/Tourorist/TPS/master/rw2/issue_mifi.jpg)
Хотя технически возможно они и не особо грузят работу миссии, по-моему, само их наличие на карте только отвлекает внимание от актуальных задач и меток.

Насколько я понимаю, их рисует скрипт работы с основными миссиями, то есть через него наверно и нужно в обратном порядке их убирать по окончанию контратаки, или еще раньше — перед обороной.

**Comment by a11archer** [comment]
Дай ссылку на скрипт этот я его посмотрю.

**Comment by Tourorist** [comment]
На сколько я понимаю это в  [fn_AOminefield.sqf](https://github.com/TEHGAM/ADR/blob/master/Annex_Done_Right.Altis/functions/fn_AOminefield.sqf) рисуется, но после захвата точки так и не убирается на ряду с самой вышкой.

Не знаю куда это прописывается, но есть [fn_AOdelete.sqf](https://github.com/TEHGAM/ADR/blob/master/Annex_Done_Right.Altis/functions/fn_AOdelete.sqf) и [fn_deleteUnits.sqf](https://github.com/TEHGAM/ADR/blob/master/Annex_Done_Right.Altis/functions/fn_deleteUnits.sqf). Плюс, в **[регионах](https://github.com/TEHGAM/ADR/tree/master/Annex_Done_Right.Altis/mission/main/region)**  в конце есть несколько строк по удалению всякого (см. [clearItems.sqf](https://github.com/TEHGAM/ADR/blob/master/Annex_Done_Right.Altis/scripts/misc/clearItems.sqf)):
```sqf
//DELETE
  deleteVehicle _dt;
  [_enemiesArray] spawn QS_fnc_AOdelete;
  if (_chance < PARAMS_RadioTowerMineFieldChance) then {[_unitsArray] spawn QS_fnc_AOdelete;};
  
//MAINTENANCE
  _aoClean = [] execVM "scripts\misc\clearItemsAO.sqf";
  waitUntil
  {
    scriptDone _aoClean
  };
  sleep 20;
};
```

**Comment by Noart537** [comment]
Думаю не актуально уже. Мины на миссии затираются. Мины от Zeus стоят долго, возможно пока не удалишь или не взорвется кто-нибудь.
