### ISSUE TITLE
Разгрузить init.sqf

### ISSUE THREAD

**Issue by Tourorist** [TEHGAM/ADR#312]
Как видно из [комментария](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/init.sqf#L13), файл используется для повсеместной инициализации скриптов — как у клиента, так и на сервере. Сами же AW пытаются его разгрузить и в версии 79L у них там только скрипт возрождения. Это наводит на мысль, что возможно подобные вещи негативно влияют на производительность игры.

Тем не менее, @ussrlongbow недавно добивал там ограничение на баллистический компьютер, хотя таковое также работает [клиентом](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/initPlayerLocal.sqf) и [сервером](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/initServer.sqf) по отдельности. Может не дёргать лишний раз железо и прописать это местно?

**Comment by Tourorist** [comment]
Переопределил ограничение на БК клиентом.

Повторюсь — при локальное игре всё работает как надо, будет ли это работать на выделенном сервере покажет время.

**Comment by Tourorist** [comment]
Я тут как будто против течения пытаюсь грести (b7be5d3). :grinning:

**Comment by ussrlongbow** [comment]
на всякий случай в скрипте локальной инициализации добавляйте проверку 
if (local _player) {}
