### ISSUE TITLE
Сформулировать цели форка

### ISSUE THREAD

**Issue by Tourorist** [TEHGAM/ADR#313]
Надо бы вытащить уже изложенные на форуме задачи и общее направление нашей миссии — её политику, как описывает это наш главный депутат — сюда в [README](https://github.com/TEHGAM/RW2/blob/master/README.md) для потенциальных и настоящих разработчиков, чтобы не тратить ничьё время на невостребованные идеи или конкретные разработки.

@tym32167, помоги мне, копни сюда свои основные пункты чтобы знать от чего отталкиваться, а дальше уже поедем обсуждать и доводить до ума со всех сторон.

**Comment by KaMeG** [comment]
Добавлю свои пять копеек в копилку дискуссий.
Надо задать в миссий общую цель, не просто монотонный захват городов. А сделать его более осмысленным. Собственно вот как примерно это выглядит в моей голове:
Старт миссий. Доступен минимальный набор снаряжения(по факту из оружия 2-3 автомата и 1 DMR для снайперов с одним простеньким коллиматорным прицелом) из техники доступны квадроциклы, охотник + аварийный набор грузовиков и парочка хамингбёрдов.
Задать несколько этапов развития которые будут зависеть от степени выполнения заданий, назовем их условно Tech level. 
Соответственно на старте tech level 0 а значит у игроков никаких плюшек в распоряжении. У города соответственно тоже стоит tech level 0, а значит сопротивление врага будет минимально(парочка джипов с пулеметами, да куча пехоты) 
Процесс захвата аналогичный текущему. С одним исключением. Оборону города можно провалить если внутри круга нет ни одного живого игрока. (на подготовку к обороне давать не 5 секунд, а 5-10 минут). Сила атакующих при обороне соответствует показателю Tech level.  Соответственно если город успешно защищен то повышается общий tech level на 1(если задание провалено то tech level остается прежним). Игроки получают прибавку к экипировке(новые стволы, аксессуары) и дополнительный респ для техники(скажем охотник с пулеметом и 1 Гостхок) со своим временем респавна. На следующем же городе tech level 1 добавит к вражеским силам охотники с гранатометом и еще больше пехоты. И так далее постепенно повышая как поощрение игроков так и ставя перед ними новые препятствия. В итоге скажем к 10му городу конфликт перерастает войну с повсеместным применением тяжелой техники и авиации как со стороны игроков так и со стороны ботов. 

Но требует подобная система серьезного вмешательства в миссию =(

**Comment by Tourorist** [comment]
@KaMeG, идея хорошая.

В общем, думаю пора вынести обсуждение будущих разработок в отдельную тему и по крайне мере (это-то мы можем) дорабатывать их пока на бумаге, так чтобы было что представить потенциальным разработчикам которые уже будут воплощать всё это в жизнь. 

Можем конечно и здесь кумекать, но эта конкретная задача (основные цели форка) уже по сути решена вышеуказанным списком от @tym32167, которые мне осталось только переформатировать под [README](https://github.com/TEHGAM/RW2/blob/master/README.md). То есть, с выпуском вер.3.5 эта тема будет закрыта, что сделает её последующие обсуждение и привлечение к ней новых собеседников неудобным так продолжать уже будем — как парадоксально — в [перечне закрытых задач](https://github.com/TEHGAM/RW2/issues?q=is%3Aissue+is%3Aclosed).

**Comment by tym32167** [comment]
Всё верно, тут уже нечего обсуждать, согласен с @Tourorist .

**Comment by ToxaBes** [comment]
Тикету больше 2х лет, может пора его закрыть?

**Comment by Noart537** [comment]
Тут Артём так красиво написал идею, что жалко закрывать)). Если ничего полезного закрывайте.

**Comment by ToxaBes** [comment]
Идея интересная, но ставит всех в неравные условия - медики делают меньше фрагов т.к. лечат/в тылу. ПТ-шником легче всего набить фрагов в виде экипажей бронетехники и т.д.
