### ISSUE TITLE
Запрет на тепловизор не работает полностью

### ISSUE THREAD

**Issue by Tourorist** [TEHGAM/ADR#316]
Сидя в вертолёте за пассажира-стрелка пожно, вопреки общего запрета, использовать ТВ прицел на оружии — проверял на Пауни с Найт Сталкером.
![](https://raw.githubusercontent.com/TEHGAM/Docs/master/images/adr/issues/night-stalker.png)

**Comment by a11archer** [comment]
Ранее удаляли теплаки через скрипт Restrictions.sqf , почему бы сейчас таким же образом не решить? ПБЛА терминалы же удаляли...

**Comment by tym32167** [comment]
не, в файле Restrictions.sqf мы вроде убирали ненужные шмотки/оружие. Есть у нас скрипт с запретом теплака, но проблема в том, что это не просто, видимо, отличить, смотрит юзер в теплак оружия своего пехом или сидя на скамейке или в теплак пушки техники смотрит или в теплак БПЛА - в этом проблема. Я не настолько крутой скриптер, чтобы в этом шарить просто .

**Comment by a11archer** [comment]
Я бы предложил отделить в Restrictions.sqf теплаки от стационарных и техники.
Запретил просто прицелы с теплаками всем кроме высшего командования:
```
//_restrictedAttachments = ["optic_Nightstalker","optic_tws","optic_tws_mg"];  
if (("optic_Nightstalker" in PrimaryWeaponItems player) && (Rank Player != "MAJOR") && (Rank Player != "COLONEL")) then
{
	player removePrimaryWeaponItem "optic_Nightstalker";
	titleText ["Nightstalker item is not allowed below Major Rank!","PLAIN",3];
};

if (("optic_tws" in PrimaryWeaponItems player) && (Rank Player != "CAPTAIN") && (Rank Player != "MAJOR") && (Rank Player != "COLONEL")) then
{
	player removePrimaryWeaponItem "optic_tws";
	titleText ["TWS item is not allowed below Captain rank!","PLAIN",3];
};

if (("optic_tws_mg" in PrimaryWeaponItems player) && (Rank Player != "LIEUTENANT") && (Rank Player != "CAPTAIN") && (Rank Player != "MAJOR") && (Rank Player != "COLONEL")) then
{
	player removePrimaryWeaponItem "optic_tws_mg";
	titleText ["TWS Mg item is not allowed below Lieutenant rank!","PLAIN",3];
};
```

**Comment by Noart537** [comment]
Думаю не актуально. Теплаки оставляем только снайперам и командирам.
