### ISSUE TITLE
Скрывать запрещённые вещи

### ISSUE THREAD

**Issue by Tourorist** [TEHGAM/ADR#317]
Думаю, будет удобней если вместо соответствующего предупреждения при выборе запрещённой вещи, мы уберём их самих из ящика — не знаю как туго закодирован Арсенал.

Это сделает список немного короче для листания и предотвратит лишние щелчки, разочарования и путаницу среди игроков.

**Comment by Noart537** [comment]
Пока у меня получается создать только "белый список" вещей, которые будут в арсенале. Из-за этого у меня появилась проблема. При первом обращении к арсеналу, он не всегда прогружается до конца (некоторые вещи отсутсвуют). После второго обращения, все нормально, полный арсенал по списку.
Возможно создаст неудобство для пользователей. 
(Нужно будет попробовать на другой машине.)

**Comment by Ded-PikhTo** [comment]
Здорово, парни! Позволю комментарий насчёт доступности одежды и инвентаря для классов.
Иногда хочется побегать в чём-то гражданском, почему убрали такую возможность выбора этой одежды? Также бывают ситуации, когда кто-то на точке просит меня, как пилота привезти различный инвентарь. Почему бы не помочь, просто убрать возможность воспользоваться им и всё, выдавая предупреждение при его взятии из ящика(арсенала)? Если здесь не тема для обсуждений, то поправьте.

**Comment by Tourorist** [comment]
> Также необходима гиперссылка на правила сервера из самого игрового мира.

@Ded-PikhTo, в смысле  как меню взаимодействия которое-бы открывало [закладку Правила](https://github.com/TEHGAM/ADR/issues/291#issuecomment-71822369) в нашем журнале? Если речь о ссылке которая бы открывала определённую страницу через браузер Steam-а, то этому пока не научились — допуская что такое вообще возможно в Arna 3.

**Comment by Ded-PikhTo** [comment]
Неважно, в каком формате выглядели бы эти правила- в браузере или ещё как. Главное, чтобы можно было быстро ткнуть носом новичка.

**Comment by Ded-PikhTo** [comment]
А, всё неактуально.

**Comment by Noart537** [comment]
Тим по 6-му ЛЦУ может всем оставим? Итак толком никто не может подсветить.

**Comment by tym32167** [comment]
@Noart537 да, давай. 
П.С. У меня оповещения отключены, ты меня пингани, если буду нужен.

**Comment by Noart537** [comment]
>123

**Comment by Noart537** [comment]
Частично будет в 3.5 по снайперам, командирам (у них будут теплаки) чтобы класс не пропадал, пулеметчикам, пилотам, ПТ\ПВО-шникам. Остальное в следующих версиях.
