### ISSUE TITLE
Уменьшить радиус и время респа квадрациклов

### ISSUE THREAD

**Issue by tym32167** [TEHGAM/ADR#324]
Необходимо уменьшить время и радиус для респа квадриков. Их постоянно раскидывают на базе.

**Comment by Noart537** [comment]
Вот уже смотрю)

**Comment by Noart537** [comment]
На сегодня все. Можно обновлять миску.

**Comment by Noart537** [comment]
Решение найдено - убрать квадрики. На форуме проголосуем.
