### ISSUE TITLE
Закрытие отрядов

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#325]
Не работает закрытие отрядов. После закрытия канала, в отряды все равно могут вступать игроки.

**Comment by tym32167** [comment]
Это, как я понял, все от того, что при подключении к серверу игрока кидает в рандомный канал. Думаю, надо сделать так, чтобы для юзера создавался новый канал и его кидало туда.

**Comment by Noart537** [comment]
Возможно еще конфликт двух скриптов отрядов. Как через Меню колесиком. Так и второй скрипт через T

**Comment by Noart537** [comment]
По умолчанию через T все могут заходить в твой отдят

**Comment by tym32167** [comment]
В таком случае то, что на букву Т, можно спокойно вырезать. Этим почти никто не пользуется.

**Comment by Noart537** [comment]
Попробовал блокировать через T. Все равно свободно можно заходить.

**Comment by Noart537** [comment]
Нужно проверять как минимум троим. В двоем при выходе из отряда, обратно не получается зайти.

**Comment by tym32167** [comment]
Так позовите третьего, народу то с армой на проекте много :smile:

**Comment by Noart537** [comment]
При отключенном групп менеджере, не получается зайти в какой-либо отряд. Включаю назад, до исправления бага.
