### ISSUE TITLE
Увеличение времени на очистку тел

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#326]
1. Предлагаю увеличить время до исчезновения убитого противника. По умолчанию стоит 60 сек,
может увеличим до 300 или 600? Дабы успеть добежать до убитого противника и залутать его.
2. Предлагаю сделать доступным для использования вражескую технику. Чтобы ее можно было захватывать. После окончания миссии она сама исчезнет. Тут уже народ может не тупо уничтожать технику, а будет стараться ее захватить. Инженеры будут популярны на точках, а не только в качестве пилото/водителями. (Возможно увеличение числа тимкилов). И когда начнется штурм ее всеравно уничтожат  два Каймана, которые скоро будут там летать. :smiley:

**Comment by tym32167** [comment]
1. Больше тел = больше лагов.  Если можно как то проверить, насколько больше лагов, то проверь.
2. Если будет возможность вражескую технику захватывать, отпадает надобность в боевой технике на базе. Об этом можно подумать, но мне пока не до этого. Может это на голосование вынеси?

**Comment by Noart537** [comment]
1. Может попробуем на боевом сервере? На один вечер установим параметр повыше. Я думаю из-за неподвижных объектов не должно сильно лагать.
2. Наверно ты прав. Это может отбить надобность бтр.
3. Еще вопрос. Если сделаем два каймана на основе и на защите, как думаешь, стоит нам разместить на базе ЗСУ Гепард?

**Comment by tym32167** [comment]
1. Давай
2. Вот вот
3. Думаю, не стоит. Игроки и так нагибают ботов, нечего им дело упрощать.

**Comment by a11archer** [comment]
Гепард на базе да, нужен. Сейчас на спавне постоянно кроет вражеская авиация, а пзрк запрещены. Расстреливают как котят. Особенно если точка близко. Больше тел не нужно т.к. есть боеприпасы в гостхоках. Чужую аммуницию все равно особо не берут - попадают под огонь снайперов. Ведь когда лутаешь, ты уязвим. Лично я возражаю тела хранить долго.

**Comment by Noart537** [comment]
Тему закрываю. Не актуальна.
