### ISSUE TITLE
Перейти на stringtable.xml для текстов

### ISSUE THREAD

**Issue by Tourorist** [TEHGAM/ADR#328]
Так как стараемся в основном для русскоязычной публики, то конечно решение данной задачи послужит не более чем этапом на пути логического разделения формы и содержания.

Имея один общий, или группу (по категориям, как в [AGM](https://github.com/KoffeinFlummi/AGM)) таких файлов, за место одноязычных встроенных текстов мы — как правильно подметил @Noart537 — сможем, помимо их будущих переводов на другие языки, также упростить любую последующую работу по изменению текущих игровых сообщений.

Если сами эту задачу не осилим, то после <kbd>v3.5</kbd> можно будет поискать под неё стороннего разработчика.

**Comment by Noart537** [comment]
Пример:
<Original>Weapons</Original>
<Russian>Оружие</Russian>
Думаю оригинала и русского хватит.

**Comment by Tourorist** [comment]
Чисто косметически, смогу наверное и сам наделать уникальных имён под переменные, запихать в них соответствующие тексты и раскидать на несколько **stringtable.xml** файлов, каждый в папку к которой его тексты относятся — по типу AGM, чтобы один файл не перегружать всем. Получится ли у меня после этого прикрутить эти переменные в самих скриптах заместо текстов, это я пока не уверен.

**Comment by a11archer** [comment]
Для того чтобы использовать StringTables рекомендуется ознакомиться с [документацией BIS по его использованию (EN)](https://community.bistudio.com/wiki/Stringtable.xml)

**Comment by Tourorist** [comment]
@a11archer, спасибо за справку. :+1: 

Глядишь, может по прочтению и сам полностью разберусь, чтобы вас этой задачей не отвлекать.

**Comment by a11archer** [comment]
Врядли, там любой скрипт должен быть внедрен с точки зрения локализации. Это всех функций касается а не только брифингов и оповещений. А пока надо к нему привыкнуть.

**Comment by a11archer** [comment]
Ограничение: В конфигурации файла stringtable.xml раздел project может быть один на файл.

**Comment by Noart537** [comment]
http://games.sunhorizon.info/Arma2.Stringtable_xml

**Comment by ToxaBes** [comment]
Мы уже используем stringable там где это оправдано (контролы интерфейсов). Тикет можно закрывать.
