### ISSUE TITLE
Задачи на 3.5 и после

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#338]
**Небольшие задачи к 3.5:**
* [x] На полосы поставить ремонтные + медицинские зоны.
* [x] Добавить пару квадриков в порту.
* [x] Убрать пауни из списка наград.
* [x] Функция быстрой выгрузки (#304)
* [x] Новая система подвеса грузов троссами (#340)

**Планируется в будущем**
* Внедрить миссии для водолазов
* Закрытие отрядов (#325)

PS: Убрал галочки специально! Пожалуйста не исправляйте.

**Comment by Tourorist** [comment]
@Noart537, я и сам с текстами не успеваю. Перетащил дату этой вехи на пятницу (13 февраля).

**Comment by Tourorist** [comment]
@a11archer, спасибо что вернул выгрузку, да еще теперь и в полном виде. насчёт проверки хозяина это уже наверно бонус на будущее, когда получится.

**Comment by a11archer** [comment]
я и троссы сделал. просто есть необходимость обсудить что делать со скоростью вертолета. я её забыл как ограничить. можно и без этого в релиз пускать но нежелательно.

**Comment by a11archer** [comment]
Вертолетную площадку перенести сможем в следующий релиз после выбора платформы?
[url]http://www.tehgam.com/viewtopic.php?f=36&t=1846[/url] с координатами. Это не скрипты и не должно вызывать рассинхрон, но все равно проверим.

**Comment by a11archer** [comment]
Сейчас решаем #357 - пауза до 14 апреля примерно.
