### ISSUE TITLE
Прицеп техники Тару

### ISSUE THREAD

**Issue by tym32167** [TEHGAM/ADR#340]
Поступила обратная связь от игроков. 
С новой системой троссов Тару отказывается работать. 
> Maap:
Не цепляет — проверил — только Охотники, даже Маршалы и то для него «не существуют».

Надо бы разобраться с этим.

**Comment by Noart537** [comment]
![2015-01-25_00001](https://cloud.githubusercontent.com/assets/8770445/5891355/2ed2b020-a4b2-11e4-980e-027ebc31f917.jpg)

**Comment by Noart537** [comment]
При смерти, этот скрипт больше не работает.

**Comment by Noart537** [comment]
Скрипт отключать до починки?

**Comment by tym32167** [comment]
да, отруби, и верни пока старую систему прицепа.

**Comment by a11archer** [comment]
после смерти скрипт пропатчил (параллельный бранч). насчет маршаллов и охотников сейчас проверю причину.

**Comment by tym32167** [comment]
@a11archer если этот тикет актуален, то переоткрой его плиз.

**Comment by a11archer** [comment]
бранч разработки тут https://github.com/TEHGAM/RW2/tree/Lift-path-for-dead-vehicles

**Comment by a11archer** [comment]
так, с тару понятно - скрипт с зевсом не совместим (с вручную установленной и техникой ботов). Вся техника один раз прорабатывается и при респавне только. Если постоянно все юниты в цикле делать это повлияет на быстродействие сервера. Можно сделать отдельное действие на базе (во флаге) чтобы прогонять всю технику вместе с зевс техникой. несколько секунд занимает.

**Comment by tym32167** [comment]
Я не спец, но если от этого начнется лаголенд, то такое решение не подойдет. У нас же тот, старый скрипт, со всем пдряд совместим, погляди как там сделано.

**Comment by a11archer** [comment]
в таком духе во флаг вставлю и проверю: this addAction["<t color='#FFBF00'>Прошу захватить новую технику ботов или Зевса!</t>", "scripts\transport\init.sqf"];

**Comment by a11archer** [comment]
не будет лаголенда. этот скрипт чисто на бисовских разработках. ты что...

**Comment by tym32167** [comment]
Я про вот это
>Если постоянно все юниты в цикле делать это повлияет на быстродействие сервера

Действие на базе для активации скрипта не очень катит, так как чем меньше кнопок игрокам, тем лучше. Может, что то наподобие таймера, вызывать скрипт раз в 5 минут, к примеру?
>Можно сделать отдельное действие на базе (во флаге) чтобы прогонять всю технику вместе с зевс техникой. несколько секунд занимает.

**Comment by a11archer** [comment]
да пусть будет так. вставлю таймер от лукавого...

**Comment by a11archer** [comment]
с маршалом тару проверил - заработало. теперь за таймером дело. тару действительно зевсом ставили потому и не цеплял

**Comment by a11archer** [comment]
![2015-01-29_00004](https://cloud.githubusercontent.com/assets/8246683/5957630/d3481772-a7cc-11e4-9499-1ddfda0d06e4.jpg)
вот доказательство с тару...

**Comment by a11archer** [comment]
вот проверил с тару поставленной зевсом еще (то что в цикле будет выполняться)
![2015-01-29_00009](https://cloud.githubusercontent.com/assets/8246683/5957698/aa3fb244-a7cd-11e4-9d40-8019b67a107e.jpg)

**Comment by a11archer** [comment]
Кстати если двигаешься то подцепить не дает. Приходится еще раз заход делать. Троссы при этом просто не появляются когда нажимаешь "подцепить". Либо кнопка подцепить появляется и пропадает. Так должно быть.

**Comment by a11archer** [comment]
Тест на tehgam 4 - пароль единица.
server4.tehgam.com:10110

**Comment by a11archer** [comment]
дублируются действия подцепить. массой более 2х тонн технику не поднимает.

**Comment by a11archer** [comment]
И все это из за поддержки Зевса и техники АИ. Гораздо безопаснее убрать с них скрипт. шустрее будет сервер.

**Comment by a11archer** [comment]
с массой разбираюсь.

**Comment by a11archer** [comment]
Не знаю куда действия деваются. ошибок скрипт не пишет но действия даже при перезаходе на сервер не появляются. буду отлавливать дальше переменные... на 4м серваке тестирую.

**Comment by a11archer** [comment]
все нашел. Связанный скрипт Player искал цели и после смерти останавливался по ! Alive.
```sqf 
player addEventHandler ["Возрождение", { _this execVM "scripts\player\transportCheck.sqf"; } ]; //переинициализация возможностей при возрождении
player execVM "scripts\player\transportCheck.sqf";
```
После смерти по !Alive Player убирались все операции связанные с обсчетом лифта у вертушки игрока. Добавил повторную инициализацию в BTC Revive чтобы начинать заново обсчет цели. После выхода с сервера цикл рвется (по not Alive Player). Обсчет локальный.

**Comment by a11archer** [comment]
проверка выявила ошибку вызова через BTC Revice, ищу почему BTC Revive его не запускал.

**Comment by a11archer** [comment]
Исправление проверено на Tehgam4, запущен Тестовый сервер 2
исправление в [ветке](https://github.com/TEHGAM/ADR/tree/Lift-path-for-dead-vehicles)

**Comment by a11archer** [comment]
Проверки завершены. Выявлены проблемы с физикой на скорости более 120км\ч. буду делать новую версию с улучшенной физикой либо ограничением скорости в понедельник но это не особенно тревожит по сравнению с тем что было. Закрыто.

**Comment by a11archer** [comment]
побили ветку проверяю заново. работало в пятницу 13го все, возврат никак к той версии не сделаю.

**Comment by a11archer** [comment]
неа, все проверил ок. лишь нормализовать нельзя было.
