### ISSUE TITLE
Новый скрипт лифта - не транспортировал после респавна техники.

### ISSUE THREAD

**Issue by a11archer** [TEHGAM/ADR#342]
**[SlingLoad](https://github.com/TEHGAM/RW2/tree/master/Annex_Done_Right.Altis/scripts/vehicle/aw_sling)** скрипт транспортировки имеет не реалистичную физику. Под землю может кидать технику. Не использует троссы — грузы вполне условно висят в воздухе.
Новый скрипт лифта позволял использовать троссы но при рассинхронизации и скорости выше 120км\ч троссы путались в винтах, техника летела впереди вертолета. После респавна техники (наземной) она не подцеплялась, а респавнившаяся вертушка цеплять технику снова не могла.

Создал ветку в которой ведется решение этой проблемы.

**Comment by tym32167** [comment]
Добавлю связь с #340

**Comment by a11archer** [comment]
Вот бранч https://github.com/TEHGAM/RW2/tree/Lift-path-for-dead-vehicles

**Comment by Tourorist** [comment]
Если будете возвращать, то постарайтесь во время к [выпуску **v3.5**](https://github.com/TEHGAM/RW2/milestones).  Только, по возможности, перед внедрением на мастер ветку и заливке на основной, проверьте его работу на Резерве. Пусть хотя бы один день там покрутиться, о чем можно было бы объявить и привлечь на тестирование игроков со Второго.

В общем, так чтобы без очередного отката получилось. Если успеете к этому выпуску, то буду благодарен за ненадобность упоминать этот откат в журнале изменений — там и так полно уже подобных заметок, как будто нам главное затолкать и не в терпёж проверить.

**Comment by a11archer** [comment]
у нас Tehgam 4 для этого есть - простаивает часто. там только конфиг нужен. конфига в проекте то нет. как только добавят я включу в него еще и Tehgam 2 тестовый сервер.

**Comment by Tourorist** [comment]
Я почему-то всегда думал что ты на Четвёртом (ex-RW6) ванильную версию Annex-а крутишь:
> **Карта сервера**: 
Altis: AhoyWorld, совместная игра (Blufor)

**Comment by a11archer** [comment]
там жутконаскриптованный Annex. просто вспоминал как скрипты делать и перегруженный 2й поддерживал. Сейчас уже Резервный есть 2й и не так трудно тестить что-то на 4м.

**Comment by tym32167** [comment]
>Там только конфиг нужен, которого в проекте то нет. Как только добавят 

Так я и не знал, что он нужен. Сейчас с сервера стяну, пароли-логины поменяю и вкручу в проект.

**Comment by Tourorist** [comment]
Всё, теперь понял.

По мне так где угодно кроме основного, но это моё собственное видение процесса, в то время как @tym32167 особенно то и не против над нашими игроками поиздеваться. Эдакий садист. :rage:

**Comment by tym32167** [comment]
[Залил](https://github.com/TEHGAM/RW2/tree/master/SAMPLE_CONFIG/RW2) конфиги, пользуйтесь. 
@Tourorist да да, садист огородник :smile:

**Comment by a11archer** [comment]
ок. а то я уже до таймера дошел. 
while {true} do 
{
	sleep 180000;
	allUnits + vehicles execVM "scripts\transport\classify.sqf";
SystemChat "=Transport Ropes= reinitialized.";
};

**Comment by tym32167** [comment]
в чат, конечно, только для отладки?

**Comment by a11archer** [comment]
только для обсуждения. мне цикл While всегда Не нравится во всех прочих таймерах. это работает повсеместно.

**Comment by a11archer** [comment]
поставил каждые 5 минут. 180000 оказалось в секундах.
30 это тридцать секунд. выставил 300 (пять минут) залил исправленный скрипт сразу в оригинал.

**Comment by a11archer** [comment]
запустил на Tehgam 4 (тот же RCon доступ) тестовый сервер Tehgam 2 Test server в открытом доступе. закрывать паролем или не стоит?

**Comment by a11archer** [comment]
пароль единичку поставил. Чтобы лишних вопросов не было

**Comment by a11archer** [comment]
убежал. буду 30 утром. проверить сам не могу - клиента нету. только сервер.

**Comment by a11archer** [comment]
Rcon доступ как от R4 и настройки портов те же. tehgam.no-ip.org:10110

**Comment by a11archer** [comment]
проверил. дублируются действия "Подцепить. 
SetMass не работает (не получается технику поднять более 2х тонн). 
На других серверах ок.
При скачивании ветки с GitHub все строки в одну пишутся... причину этого я не понял. Не надо ветку сливать.

**Comment by a11archer** [comment]
Переделаю скрипт на этой неделе. очевидно что конфликтует при переинициализации каждые 5 минут в цикле. Проще убрать правда поддержку Зевса и АИ техники. Ведь во вражескую технику нельзя залезть.

**Comment by a11archer** [comment]
вот причина - allUnits + vehicles включает уже инициализированную технику.
надо исключать ту которая инициализировалась. работаю над этим.
while {true} do 
{
    sleep 180000;
    allUnits + vehicles execVM "scripts\transport\classify.sqf";
    SystemChat "=Transport Ropes= reinitialized.";
};

**Comment by a11archer** [comment]
Пока убрал поддержку Зевс. И так хорошо. Намного проще чем выдумывать систему переинициализации новую к скрипту.

**Comment by a11archer** [comment]
вот что пробую сейчас:
```sqf
k = _Vehicle getVariable "attachaction";
k1 = _Vehicle getVariable "detachaction";
_Vehicle removeAction k;
_Vehicle removeAction k1;

k = _Vehicle addAction["<t size='1.5' shadow='2'color='#C9C900'>Прицепить технику</t>", "scripts\transport\attach.sqf", [_Vehicle], 10, false, true, "", "isPlayer driver _target && isNull(_target getVariable ""AttachedVehicle"") && !isNull(driver _target getVariable ""CurrentTarget"")"];
k1 = _Vehicle addAction["<t size='1.5' shadow='2'color='#C9C900'>Отцепить технику</t>", "scripts\transport\detach.sqf", [_Vehicle], 10, false, true, "", "!isNull(_target getVariable ""AttachedVehicle"")"];

_Vehicle setVariable ["attachaction", k];
_Vehicle setVariable ["detachaction", k1];
```

**Comment by a11archer** [comment]
Действие пропадает после того как потеряешь хоть раз груз за текстурами. респавн не помогает судя по всему. пока не понял почему не появляется действие если пишет что инициализировано.

**Comment by a11archer** [comment]
Пропадает т.к. скрипт /scripts/Player оканчивает свое действие. я думаю в BTC Revive добавить строчку инициализации заново. проверяю уже.

**Comment by a11archer** [comment]
да, я попал в точку. солдаты Зевса к примеру из за этого не умеют поднимать грузы. у них скрипт не стартует. закрыта проблема.

**Comment by a11archer** [comment]
давайте последнюю сборку тестировать. пишите в Тимспик когда залить её на тестовый сервер (ветка отдельная, не оригинал)

**Comment by a11archer** [comment]
я уже на тестовом 4м гоняю этот скрипт.

**Comment by a11archer** [comment]
неудачно... не стартует ни в BTC ни в monitor.sqf ищу причину почему.

**Comment by a11archer** [comment]
GitHub изуродовал скрипты - убрал <CR><BR> коды и в результате комментирование строк захватывает следующую строку. что за... что не открою в Github нормально а загружаешь - все в одну строку.

**Comment by a11archer** [comment]
Удалось победить и коды и респавн. рабочий скрипт уже внутри миссии, достаточно запустить его через консоль админа прямо в игре. \player\init.sqf , transport\init.sqf
У меня идет проверка. как только пройдет неделя разкоментирую в основном билде.
