### ISSUE TITLE
Рытвины

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#343]
Может сделаем авто очистку рытвин по всей карте раз в 10 мин? А то лишние объекты только увеличиваются.

**Comment by tym32167** [comment]
а это тоже будет в цикле? Это не будет сервер напрягать? Может, можно как то настроить, чтобы рытвины просто скриптом очистки карты убирались?

**Comment by Noart537** [comment]
Попробую

**Comment by a11archer** [comment]
согласен, давайте лучше по всем обьектам (массив) убить все которые тип рытвина. вставить во флаг или еще что-нибудь. с массивами игра быстро работает.

**Comment by Noart537** [comment]
@a11archer Давай если знаешь как, сделай пожалуйста. Можно даже через меню игровое. 0-0-9 например. Если знаешь как. Сном можно ограничить кол-во использований. Раз в 30-60 мин.

**Comment by Noart537** [comment]
Что если нам поставить неубиваемый\неперемещаемый объект и добавить к нему действие addaction и добавить скрипт очистки рытвин по всей карте.

**Comment by tym32167** [comment]
можно, но только если нет возможности сделать это автоматом (или в цикле), ибо чем больше кнопочек для игроков = тем больше проблем\вопросов. А объект такой есть уже - карта на респе.

**Comment by a11archer** [comment]
re:@a11archer давай если знаешь как, сделай пожалуйста...
Мое мнение чем больше циклов и размеров территории на котором надо их делать - чистить рытвины тем глючнее миссия. Я вообще старался чисто скриптом бобкета делать. За всю карту браться не берусь. Удаляет ведь определенный вид обьекта, независимо от того нужен он там был или нет. Тем более AllUnits и AllVehicles не содержит дроп, а мины и т.п. это похоже на дроп. Я собирался как только доделаю лифт заняться вплотную улучшением бульдозера. Это выглядит реалистичнее. [Текст скрипта на форуме уже выложил](http://www.tehgam.com/viewtopic.php?f=8&t=952).

**Comment by a11archer** [comment]
А то летишь и кричишь "кто там на базе сделайте мне чудо: - я подбит и сажусь на разрушенный уже противником аэродром".
Я хочу упростить бульдозеры донельзя. чтобы никакой площадки чисто к рытвине подьезжать надо было. Кроме площадки пока мне все в нем нравится.

**Comment by a11archer** [comment]
[Идет доработка boxZone.sqf площадки бульдозера](https://github.com/TEHGAM/Nato-vs-ODKB/blob/master/Nato%20vs%20ODKB%20with%20mods/Nato_vs_ODKB_PvP.Altis/boxZone.sqf)
[Идет доработка groundworks.sqf бульдозера](https://github.com/TEHGAM/Nato-vs-ODKB/blob/master/Nato%20vs%20ODKB%20with%20mods/Nato_vs_ODKB_PvP.Altis/groundworks.sqf)
[Улучшено ремонтное оборудование dropResupplyBox.sqf](https://github.com/TEHGAM/Nato-vs-ODKB/blob/master/Nato%20vs%20ODKB%20with%20mods/Nato_vs_ODKB_PvP.Altis/dropResupplyBox.sqf)
В процессе...

**Comment by a11archer** [comment]
В [Branch](https://github.com/TEHGAM/ADR/tree/Lift-path-for-dead-vehicles) добавил. тестирование версии 2 уже идет на Tehgam 2 Test server пароль единичка.

**Comment by Noart537** [comment]
Действие с выгрузкой ремонт-комплекта. Может его убрать? Чтобы не засорять ящиками терминал.

**Comment by a11archer** [comment]
Ремкомплект только 4 ящика выгружает. Не засоришь. В любом случае кроме бобкета ящики для таскания некем порождать. У вас нету как в wasteland генератора контейнеров. Если не нужен просто закомментируйте [AddAction соответствующий](https://github.com/TEHGAM/ADR/blob/master/Annex_Done_Right.Altis/boxZone.sqf): line 14 
```
_dropbox = _bobcat1 addAction ["<t color='#FF8000'>Выгрузить ремкомплект</t>","dropResupplyBox.sqf", _bobcat1];
```
на быстродействие это никак не влияет

**Comment by a11archer** [comment]
Скрипт работает раз в 10 секунд оценивая обьекты в нескольких метрах от бобкета. Поэтому из за него лагать не может. Он просто удаляет обьект выбранного типа (яма) в нескольких метрах от другого обьекта (бобкет) через ванильную функцию. Скрипт писал не я, я лишь доработал.

**Comment by a11archer** [comment]
Изначально он всю карту чистил (грузило сервер). бобкет уменьшил число итераций цикла и размер обрабатываемых обьектов. Сделал элемент ролевой игры.

**Comment by Noart537** [comment]
Вопрос закрываю. Пока оставляем Бобкет.
