### ISSUE TITLE
Совмещение веток с мастером

### ISSUE THREAD

**Issue by a11archer** [TEHGAM/ADR#347]
При совмещении ветки с мастером может выдавать ошибку что автоматически это не производится. Это потому что в Вашей ветке не присутствует нормализация строк типа текст (удаление из текста не текстовых символов почему-то включая конец строки) а в мастере есть.

Для этого надо переключиться в режим ветки в Windows клиенте в верхней части экрана стрелочка вниз на названии репозитория которого выбрали слева. Там перечень всех веток включая Вашу.
  1. совместите Master на вашу ветку чтобы исправить нормализацию строк,
  2. проверьте что это не привело к дефекту ветки!
  3. совместите с оригиналом и работайте уже без нормализации строк (оно текст в одну строку при загрузке ветки с сайта показывает — сразу заметно.

**Comment by a11archer** [comment]
это делается только один раз для ветки созданной ДО 14.02.2015. поздние ветки этой нормализации уже не имеют.

**Comment by Tourorist** [comment]
У нас кроме @a11archer кто-либо еще через Windows клиент изменения забрасывает?

@Noart537, @tym32167 настройте что-ли, если у вас такие-же проблемы.

**Comment by Tourorist** [comment]
Что-то у меня теперь в режиме просмотра (Preview) перед комитом, показывает как-будто весь файл заново меняю, но потом в истории уже показывает разницу правильно — выделяя только изменённые части.

**Comment by a11archer** [comment]
та же фигня. Давайте нормально GitAttributes настроим. я не понимаю как. отключение GitAttribute -text вообще привело к тому что ветки не совмещаются. Я попытался проверить мастер и понял что и в нем куча ошибок там где правили через веб интерфейс. Мое предложение откатить все до нормализации и попытаться выработать настройки GitAttributes для .sqf, .sqm, .hpp и т.п. остальное мы редко и с веб интерфейса и с Windows клиента правим - можно считать это бинарным кодом. Раздражает просто когда скачиваешь миссию с сайта а внутри каша нечитабельная. Нормализация вроде как помогла но откуда-то появились ошибки!

**Comment by Tourorist** [comment]
Я думаю не откатывать, а к чертям `.gitattributes` убрать. Если в других больших репках ([AGM](https://github.com/KoffeinFlummi/AGM), [TFAR](https://github.com/michail-nikolaev/task-force-arma-3-radio)) без него обходятся (есть только `.gitignore`), то и мы тоже осилим.

@a11archer, укажи на кокой-либо файл который сливается в одно, я попробую  проверить у себя. Подозреваю что возможно у тебя просто сам редактор (Notepad++?) шалит.

В любом случае что угодно, только без авто-откатов — надоело уже. Если что не работает, правьте вручную обратно или на лучшее, как я делаю при своих косяках. Ошибаться можно просто нужно быть внимательней, ну а когда ошибки встречаются то не решать их как роботы.

@tym32167 где ты пропадаешь. Пожалуйста, разъясни и рассуди уже эту ситуацию.

**Comment by tym32167** [comment]
Всем привет. Я тут немного выпал из исходников. Сейчас оставлю гит и погляжу, что происходит.

**Comment by a11archer** [comment]
убили настройку нормализацию. только так. GitAttributes менять невозможно пока ветка хоть одна открыта.
