### ISSUE TITLE
Баг с подвесом техники вертолетом

### ISSUE THREAD

**Issue by tym32167** [TEHGAM/ADR#350]
Не получается зацепить Охотник (с тяжёлым пулеметом) грузовым Тару.

**Comment by a11archer** [comment]
там два тару. один не грузовой. КАКИМ пытались? который пассажирский, он не может!

**Comment by tym32167** [comment]
Я ж написал, пытались грузовым Тару.

**Comment by a11archer** [comment]
Я грузовым проверял. Работает. Крюк вынуть надо просто. там другой скрипт очищает все сторонние скрипты. Пробуйте... цепляет за крышу (крючки раскручиваются).

**Comment by tym32167** [comment]
Ты проверял именно на охотнике с пулеметом? Другую технику цепляло просто.

**Comment by a11archer** [comment]
![107410_2015-02-15_00001](https://cloud.githubusercontent.com/assets/8246683/6204157/7a4dc850-b551-11e4-8fd8-a1d2cff21c18.png)

**Comment by a11archer** [comment]
да. его родной скрипт что-то мешает. родной включается. там меню серенькое Hook. Оно имеет тот же номер который создается нашим скриптом и его перезаписывает.

**Comment by a11archer** [comment]
Более того. скрипт работает не сразу а через секунд 8. надо очень точно висеть над техникой.
![107410_2015-02-15_00005](https://cloud.githubusercontent.com/assets/8246683/6204184/ce692276-b552-11e4-8e3f-15e5f3617836.png)

**Comment by tym32167** [comment]
Хмм, судя по скринам, баг неактуален. Закрываю тикет.
