### ISSUE TITLE
Баг с респом игрока

### ISSUE THREAD

**Issue by tym32167** [TEHGAM/ADR#351]
При поднятии игрока медиком пропадает терминал БПЛА.

**Comment by Tourorist** [comment]
У оператора или другого класса который не имеет доступа к БПЛА через VAS?

**Comment by tym32167** [comment]
У оператора. Сохранение снаряжения делали через "Автозагрузку" VAS. Также пропадает нейтсталкер, хотя он не запрещен.

**Comment by a11archer** [comment]
Это не ошибка BTC-Revive. Там вообще нет ничего про оснащение.
```
BTC_first_aid =
{
  private ["_injured","_array_item_injured","_array_item","_cond"];
  _men = nearestObjects [player, ["Man"], 2];
  if (count _men > 1) then {_injured = _men select 1;};
  if (format ["%1",_injured getVariable "BTC_need_revive"] != "1") exitWith {};
  _array_item = items player;
  _array_item_injured = items _injured;
  _cond = false;
  if (BTC_need_first_aid == 0) then {_cond = true;};
  if ((_array_item_injured find "FirstAidKit" == -1) && (BTC_need_first_aid == 1)) then {_cond = false;} else {_cond = true;};
  if (!_cond && BTC_need_first_aid == 1) then {if ((_array_item find "FirstAidKit" == -1)) then {_cond = false;} else {_cond = true;};};
  if (!_cond) exitWith {hint "Can't revive him";};
  if (BTC_need_first_aid == 1) then {if (_array_item_injured find "FirstAidKit" == -1) then {player removeItem "FirstAidKit";};};
  player playMove "AinvPknlMstpSlayWrflDnon_medic";
  sleep 5;
  waitUntil {!Alive player || (animationState player != "AinvPknlMstpSlayWrflDnon_medic" && animationState player != "amovpercmstpsraswrfldnon_amovpknlmstpsraswrfldnon" && animationState player != "amovpknlmstpsraswrfldnon_ainvpknlmstpslaywrfldnon" && animationState player != "ainvpknlmstpslaywrfldnon_amovpknlmstpsraswrfldnon")};
  if (Alive player && Alive _injured && format ["%1",player getVariable "BTC_need_revive"] == "0") then
  {
    _injured setVariable ["BTC_need_revive",0,true];
    if (group player == group _injured) then
    {
      addToScore = [player, 2]; publicVariable "addToScore";
      ["ScoreBonus", ["Возродил сокомандника", "2"]] call bis_fnc_showNotification;
    } else
    {
      addToScore = [player, 2]; publicVariable "addToScore";
      ["ScoreBonus", ["Возродил соотрядника", "2"]] call bis_fnc_showNotification;
    };
    _injured playMoveNow "AinjPpneMstpSnonWrflDnon_rolltoback";
  };
};
```

**Comment by Noart537** [comment]
Условие надо добавить в файл /scripts/restrictions.sqf

**Comment by a11archer** [comment]
Проверил - в других функциях BTC тоже нету удаления оснащения (закоментировано уже все что имеет remove*** имя). Я согласен, буду искать в /scripts/restrictions.sqf там есть что-то что удаляет терминал.

**Comment by a11archer** [comment]
там прописано что только у _uavOperator = ["B_soldier_UAV_F","B_officer_F"];
не удаляется терминал, может модель меняется? пишет ли ```"Только операторы БПЛА могут использовать терминал управления."```?

**Comment by Noart537** [comment]
Может быть так 

if ((playerSide == west && typeOf player != "B_soldier_UAV_F") then
{player removeItem "B_UavTerminal";
titleText [UAV_MSG,"PLAIN",3];}

**Comment by a11archer** [comment]
Там все верно. ведь еще проверка стоит есть ли в массиве используемых устройств терминал, а в таком исполнении просто ошибку выдаст что терминала нет. Причем ежесекундно.

**Comment by a11archer** [comment]
ключ в том что если мешает restrictions то будет сообщение ```"Только операторы БПЛА могут использовать терминал управления.```

**Comment by Noart537** [comment]
Когда берешь терминал в роли оператора БПА, он это и пишет.

**Comment by a11archer** [comment]
Может что-то вроде этого
```
_uavOperator = ["B_soldier_UAV_F","B_officer_F"];
   		_uavRestricted = ["B_UavTerminal","O_UavTerminal","I_UavTerminal"];
       	_assignedItems = assignedItems player;

		if ("B_UavTerminal" in _assignedItems) then {
			if ((player isKindOf) ! in _uavOperator)) then {
				player unassignItem "B_UavTerminal";
				player removeItem "B_UavTerminal";
				titleText [UAV_MSG,"PLAIN",3];

			};
		};
```

**Comment by a11archer** [comment]
попробую в отладчике посмотреть результат

**Comment by Noart537** [comment]
Я тебя обманул ^^
Ошибка в VAS скорей всего. Именно от туда берется текст. При загрузке сохраненной экипировки. Там же находится автозагрузка.

**Comment by a11archer** [comment]
Да, похоже на то. проверю..

**Comment by a11archer** [comment]
//Items to remove from VAS
vas_r_items = [
"B_UavTerminal",
"I_UavTerminal",
"O_UavTerminal",

**Comment by a11archer** [comment]
небось это в связи с Restrictions вообще мешает. комментирую "B_UavTerminal",

**Comment by Noart537** [comment]
давай в отдельной ветке, я сразу проверю и отпишу

**Comment by Noart537** [comment]
Скорей всего надо через условие. т.к. если так закоментить, то все смогут взять. Сейчас проверю.

**Comment by a11archer** [comment]
нет уж. откатить основную ветку проще чем Merge. сразу в мастере проверять надо.

**Comment by a11archer** [comment]
после Merge потом все заливать заново приходится!!!

**Comment by a11archer** [comment]
если закоментить то смогут взять но тут же через Restrictions у них отбирает терминал.

**Comment by Noart537** [comment]
Сейчас проверю, отпишусь. Если все норм закрываем.

**Comment by a11archer** [comment]
проверил. добавляется через VAS. удаляется из оснащения но не удаляется из Assigned Items. Пользоваться при этом нельзя и пишет что было удалено.

**Comment by Noart537** [comment]
Работает. Но надо будет пересохранять набор. Со старыми сохранениями удаляет, если пересохранить снова, то норм работает.

**Comment by a11archer** [comment]
В любом случае это не похоже на ограничения VAS. У нас BTC сохранение оснащения вообще отключено. Мы исправили ящики но не поняли почему при ревайве скрипт удалял терминал. Это точно VAS делал?

**Comment by a11archer** [comment]
я на тестовый сервер закину билд проверить.

**Comment by a11archer** [comment]
А как там со взломом вражеского терминала. Bis вроде внедрили скрипт который позволял чужие терминалы использовать. Или это своим терминалом взломать можно было? Не будет конфликта? Запустил тестовый пароль единичка.

**Comment by a11archer** [comment]
пароль не могу на сервер 62,16,,,, найти

**Comment by Noart537** [comment]
7474

**Comment by a11archer** [comment]
спасибо

**Comment by a11archer** [comment]
тут проблемка кто-то три секунды на ревайв поставил? ```BTC_revive_time_min = 3;```
и это можно в консоли на Esc через админа поменять во время игры.

**Comment by Noart537** [comment]
Это когда тебя убивают, появляется камера с верху над тобой. Когда нажимаешь Respawn то начинается отсчет 3 сек и ты на базе.

**Comment by a11archer** [comment]
то есть это уже после того как тебя могли поднять... хм

**Comment by a11archer** [comment]
Noart исправил я проверил. Правда еще VAS отрабатывает до того как тебя поднимут восстанавливая весь инвентарь. Если будут жалобы займемся и этим.

**Comment by Noart537** [comment]
не правда) я только респ исправил ^^ остальное ты)

**Comment by tym32167** [comment]
@a11archer @Noart537 C терминалом, как я понимаю, все хорошо. А с нейтсталкером? Он у нас не запрещен, насколько я помню. Возможно, есть ещё какие элементы, что можно взять через арсенал, но нельзя через VAS (подозреваю, что потому они и пропадают)

**Comment by Noart537** [comment]
В VAS его нет. Поэтому и нельзя взять. Добавить?

**Comment by tym32167** [comment]
Да, добавь.
