### ISSUE TITLE
Повторяющееся меню

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#353]
![2015-02-21_00001](https://cloud.githubusercontent.com/assets/8770445/6315015/50b03e74-ba15-11e4-87eb-737aa75fd56c.jpg)
![2015-02-21_00002](https://cloud.githubusercontent.com/assets/8770445/6315014/50b008be-ba15-11e4-9e44-c00d26863924.jpg)
Меню повторяется

**Comment by Noart537** [comment]
Словно есть 2 источника на один файл с меню.

**Comment by Tourorist** [comment]
Нет, они в самом файле повторяются — [setupUnit.sqf](https://github.com/TEHGAM/ADR/blob/master/Annex_Done_Right.Altis/scripts/vehicle/setupUnit.sqf)

Я трогать не решился, после того как @a11archer их туда добавил. Надо кому-то кто разбирается, посмотреть какую из этих пар можно убрать.

**Comment by Tourorist** [comment]
Насчёт других (Камера и Отцепить), насколько я понимаю у нас до сих пор похожие скрипты на одну и ту же функцию работают параллельно, т.е. мы не удалили старые. Если так, то надо те что были заменены сливанием веток.

А вообще, когда тестировал, меня удивило количество всяких меню у пилотов. Вам самим-то удобно так во время полёта листать это длинное меню взаимодействия?

**Comment by Noart537** [comment]
А что делать? Приходится)

**Comment by a11archer** [comment]
1) Насчет очистки поправил. Я полагаю и для вертолетов и для техники назваться может одинаково. 
2) С камерой труднее. Она работает вообще? если да я подумаю почему два раза иниациализируется. 
3) Отцепить красным и желтым повторяется? Или и красным и желтым?

**Comment by a11archer** [comment]
Когда удаляли строки [в файле](https://github.com/TEHGAM/ADR/blob/master/Annex_Done_Right.Altis/scripts/vehicle/monitor.sqf) появились задвоения
```
[[[_unit],"scripts\vehicle\setupUnit.sqf"],"BIS_fnc_execVM",nil,true] spawn BIS_fnc_MP; // only for LIFT Transport script
		_classify = [ _unit ] execVM "scripts\transport\classify.sqf"; // only for LIFT Transport script
```
причем строка _classify не нужна т.к. относится к скрипту строп который вы решили отключать.

**Comment by a11archer** [comment]
Поправил. Все, отпишите помогло ли во всех случаях. Надо разбираться с лагами.
3й, и 2й пункт моих вопросов из за задвоения [[[_unit],"scripts\vehicle\setupUnit.sqf"],"BIS_fnc_execVM",nil,true] spawn BIS_fnc_MP; 
Нашел и убрал.

**Comment by a11archer** [comment]
Не актуально проверять (тем более что поправили). Платформа сменилась. Скрипт этот в старой платформе остался. Не вижу причин ставить метку баг.

**Comment by Tourorist** [comment]
Если исправлено то и закрыто.
