### ISSUE TITLE
Добавить папку с оригинальной миссией версии 82

### ISSUE THREAD

**Issue by tym32167** [TEHGAM/ADR#354]
* Качаем http://www.ahoyworld.co.uk/topic/726-aw-invade-annex-changelog-and-download/
* Меняем мастера игры
* Вкрутить дневник
* Запускам на втором

**Comment by tym32167** [comment]
* Поправить адрес ТС

**Comment by tym32167** [comment]
Рядом с отсылкой на сайт ahoy.world указать ссылку на наш сайт http://tehgam.com

**Comment by Noart537** [comment]
Предлагаю:
* _В первую очередь, включить скрипт прорисовки и скрипт транспортировки._

**Comment by Tourorist** [comment]
Упоминания о нашем ТС исправил везде, включая дневник. Полностью заменить его на наш я отказываюсь, это не наша работа, авторство за чужую миссию брать не позволю. :smile: 

Ссылки пусть все их остаются, на данном этапе нашего в ней нет чтобы иметь право вкручивать свою рекламу. Наш сервер где и упоминается сайт, всё остальное не наши.

**Comment by tym32167** [comment]
Да, конечно, пусть ссылки будут оригинальные. По поводу варить скрипт-пока рано, пусть миссия в таком виде проработает пока. Как получим обратную связь от игроков, будем решать, что вкрутить.

**Comment by Tourorist** [comment]
Мне кажется, если после этих двух недель мы всё-таки примем решение сливать, то в первую очередь нужно будет начать с работы над sttringtable.xml, что и обсуждалось когда мы с @KaMeG пришли 77-ую копать. Иначе мы этот геморройный цикл еще раз повторим когда скажем еще через пол года выясниться что мы опять засрали миссию и у нас она почему-то не такая быстрая как самая последняя на тот момент у Ахоевцев.

Нам бы надо на этих ошибках чему-то научится, а не становится на тот же путь чтобы повторить их заново. Поэтому, как и договаривались, давайте пока искать проблему рассинхрона, а там будет ясно. Если уж точно ничего после двух недель не выясним, то ладно можем по этой проблемы смириться, опустить руки и спокойно взять 82-ую за базу, как разнообразие чужим трудом. На сколько можем приводим её в порядок, после чего, занижаем амбиции по её развитию — если мы не можем исправить что есть, то куда нам еще лезть в дальнейшее развитие, если конечно таковое не подразумевает обычную копипасту скриптов из вне, что как заметил @Noart537 возможно и является первоисточником текущей проблемы с рассинхроном.

По завершению манёвра, я думаю как проект ADR можно уложит спать и уже думать что делать дальше как группа, так как в данном исходе очевидно что Арма-строители из нас никакие. Если так, то после всего этого можно было бы например попробовать смастерить для сообщества какой-нибудь полезный ресурс (сайт), в том же составе. Новые проблемы и вызовы, но возможно в этом направлений у нас будет более цельный результат. :smiley:

**Comment by tym32167** [comment]
Ну, основное назначение миссии-это привлекать больше народу на сервер и, соответсвенно,на проект. По большому счету, мы бы могли взять любую пве миссию и запустить перманентно на втором. Миссию же мы пилим для того, чтобы на сервере было интересней играть, ну и чтобы у нас была какая никакая своя фирменная миссия, пусть даже основанная на другой. На данный момент, я думаю, что мы полностью не сможем закончить работу над миссией,  так как остаемся как минимум на поддержке и хотелках игроков. Чем, собственно, сейчас и занимаемся.

**Comment by Tourorist** [comment]
Ну фирменной она не станет если мы просто отредактируем параметры сервера и сложности миссии. Может нам просто спуститься уже до базовой и вместо этого помочь им на Битбакете внедрить stringtable.xml? Так мы хоть что-то значимое для исходника сделаем и впилим ссылку на проект уже во все последующие официальные выпуски.

AGM мод тоже основан на другом, но сейчас вообще кто-нибудь помнит на каком именно? Разница в усилиях. Они как проект и команда свои корни переплюнули, но у нас же, я согласен, навряд ли своими силами получится. Можно отказаться от планов по развитию и достойно спуститься до поддержки I&A для русскоязычного сообщества. А там уже заняться чем-нибудь что нам по силам как проект в свободное от работы время и на что у нас хватает профессиональных навыков.

**Comment by tym32167** [comment]
Думаю, это можно обсудить, когда соберемся в следующий раз.

**Comment by Noart537** [comment]
Народ ушел на резервный, так мы ничего не потестим. Пишут некомфортно играть стало. Нет скрипта отрядов, все говорят в синий канал. Флуд из-за этого. Технику до точки не довезти. Прорисовку еще надо сделать, у авиации видимость в 1.6 км все в тумане. 
Надо влючать скрипты хотя-бы 2, иначе никто играть не будет. И ещё пилотов обязательных отключить.
Как считаете?

**Comment by Noart537** [comment]
Если даете добро, ставьте задачи, по возможности буду решать.

**Comment by tym32167** [comment]
Погляди, если завтра с народом будет также туго, то выключай пилотов и вкручивай нужные скрипты. Без игроков смысла тестить нет.

**Comment by Tourorist** [comment]
Подтверждаю, заходил сегодня на резервным попросил по возможности переселиться массу на основной, но как контр-аргумент получил «там всё на английском и глючит», лаги из разряда обычных, не рассинхрон.

В связи с этим, я согласен что первым делом нам нужно мигрировать наши самые качественные скрипты (отряды и прорисовка). Полагаю, ни то, ни другое на нашу текушию проблему не влияет.

**Comment by Noart537** [comment]
Производительность сервера нормальная. Рассинхрон не наблюдается. Визуально можно заметить по перемещению ботов и по бисовским стропам на вертолетах. Сегодня\завтра добавлю группы и прорисовку. Будем дальше тестировать. Ближе к выходным добавлю еще пару скриптов. И на выходных протестируем. Если все нормально, думаю можно оставлять эту миссию, и вплотную заняться переводом и косметическими изменениями.

**Comment by Tourorist** [comment]
Если не найдём причину рассинхрона то будем идти по моему плану-корректировки (обсудим на совещании):
 1. Сливаем что можем из нашей версии и проект отдаём в дом престарелых.
 2. Либо же, переходим под командование AW и делаем им работу над интернализацией (i18n) с поддержкой русского и английского (как «Original») для начала. А там уже видно будет, сколько других переводов накопится под нашу работу над ***[stringtable.xml](https://github.com/TEHGAM/ADR/issues/328)***.

**Comment by Tourorist** [comment]
Задача выполнена (закрываю), но мы как у нас уже принято опять умудрились чутка отойти от темы.

Работа по сливанию ADR с I&A 79Е/82 уже идет и разбирается отдельными задачами, а вопросы по дальнейшему развитию обсудим уже на следующих собраниях группы.
