### ISSUE TITLE
Транспортное депо для ADR (Запрос Браконьера)

### ISSUE THREAD

**Issue by BJStevenson** [TEHGAM/ADR#356]
1. Качаем файл с миссией ([здесь](https://vk.com/doc5298978_372748321?hash=067858e7807e6c4bfe&dl=9202da2f3abca3b26f))
 2. Разархивируем.
 3. Папку **Supply.Altis** кидаем в папку с миссиями из редактора — на моем примере::  ```C:\Users\Stevenson\Documents\Arma 3\missions```
 4. Запускаем Arma 3, заходим в редактор. Запускаем миссию и проверяем..
 5. Если подходит, то возвращаемся в редактор. Загружаем миссию **ADR**, выбираем иконку «Объединить» (<kbd>CTRL</kbd>+<kbd>M</kbd>) и выбираем миссию **Supply.Altis**.
 6. К миссии **ADR** добавятся объекты из миссии **Supply.Altis**. Потом удаляем двух персонажей, которые появятся около депо (они больше не нужны).
 7. Готово.

**Comment by Tourorist** [comment]
@BJStevenson, спасибо! Как проверю, доложу тебе.

**Comment by Tourorist** [comment]
Я проверил, мне понравилось.

Закрывай как закинешь на мастер.

**Comment by Tourorist** [comment]
Задача была выполнена через комит faa844e от @BJStevenson.

Закрываю.

**Comment by Tourorist** [comment]
@BJStevenson, протолкнул твою модельку в выпуск <kbd>v3.4.5</kbd>, как видно из последней записи в журнале изменений — [на вики](https://github.com/TEHGAM/ADR/wiki/ADR: История) и [на форуме](http://www.tehgam.com/viewtopic.php?f=4&p=15347#p15347).

Спасибо!
