### ISSUE TITLE
Переход на новую платформу. Задачи.

### ISSUE THREAD

**Issue by a11archer** [TEHGAM/ADR#357]
* [ ] Найти и добавить на сервер скрипт мониторинга производительности миссии
 * [ ] Включить логгирование
 * [ ] Собрать и исследовать результаты

**Параллельно:**
 * [x] Начать работу по i18n текстов через **stringtable.xml** (#328)

**Comment by a11archer** [comment]
В данный момент договорились что до 14 апреля 2015 не планируется внедрение каких либо систем скриптов кроме системы мониторинга производительности.

**Comment by a11archer** [comment]
Документируйте ссылки пожалуйста:
[*]Описание логов .rpt сервера arma3 https://community.bistudio.com/wiki/arma.RPT
[*]Пример работы stringtable.xml в скриптах https://github.com/Tourorist/AGM/blob/master/AGM_Aircraft/stringtable.xml

**Comment by a11archer** [comment]
Скажите, какая миссия (дать ссылку) в итоге остается не тронутой (базовой), а какая рабочей?

**Comment by Tourorist** [comment]
* **[79E_UP](https://github.com/TEHGAM/ADR/tree/master/.devfiles/co60_AW_Invade_Annex_2_79E_UP.Altis)** — версия что сейчас крутится на Втором (железо от @AlNazir), это и есть наш пациент, с которого мы собираемся брать пробы на анализы (п.2, 3), и кому будем крепить те самые датчики (п.1). @Noart, я правильно понжал?

>А вообще, никто личному составу толком ничего не разъяснил когда наш глав.врач в очередной раз смотался со всем бюджетом клиники на симпозиум специалистов, хотя сам сейчас, что более вероятно, опять в каком-нибудь Челябинском казино со своей любовницей наши последние деньги пропивает.

Не знаю, что именно ты подразумеваешь под «рабочей» во время этой месячной заморозки сервера, но я лично собираюсь работать и тестировать свою задачу (п.4) пока что только на основе местной копий ADR <kbd>v3.4.4</kbd>.

**Comment by tym32167** [comment]
@a11archer, @Tourorist верно говорит, UP - это наш пациент, запущенный на сервере Т2.

**Comment by a11archer** [comment]
Кандидат пункта 1 - [URL]https://community.bistudio.com/wiki/BIS_fnc_fps[/URL]

**Comment by a11archer** [comment]
Не получилось. Это процедура. Она логи не пишет.

**Comment by a11archer** [comment]
У меня других функций нету. Еще есть варианты? Этот не подходит. Через Стим фпс записывать в логи нельзя. Тем более снимать его с клиентов.

**Comment by a11archer** [comment]
Ice Status Hud перерабатывать можно. _var = _display displaycontrol 520501; отвечает за фпс в игре. может с него как-то можно логи снимать...

**Comment by a11archer** [comment]
нет. все проще имя переменной diag_fps локальное (на сервере оно тоже локальное)

**Comment by a11archer** [comment]
оно численное. с запятой. Может округляеться через round.
