### ISSUE TITLE
Место респауна пилотов

### ISSUE THREAD

**Issue by GRIDSW** [TEHGAM/ADR#359]
Пилоты после первой смерти ресаются с основной группой, это неприемлемо для "новой базы" (старой, действующей тоже), т.к. долгий путь надо будет преодолевать от основного респауна до вертолетной базы. Пилоты должны ресаться на своей базе.

**Comment by Noart537** [comment]
Проблема знакомая, в ближайшее время постараюсь заняться.

**Comment by Noart537** [comment]
Как вариант, в скрипте Revive существует мобильный респаун. Обычно привязывают на КШМ. Можно попробовать привязать к объекту и сделать объект неподвижным и закрытым для игроков.

**Comment by a11archer** [comment]
Сделайте респавн от BIS.
***
Respawn = 3;        //0 = none. 1 = bird. 2 = instant where died. 3 = base or respawn_west marker. 4 = respawn with team, or bird. 5 = into AI or bird.
RespawnDelay = 35;   //Delay prior to respawn, ensure longer than BTC revive delay.
RespawnDialog = 1;  //Default = 1. show respawn timer and scoreboard when killed.
//Respawn = 3;        //0 = none. 1 = bird. 2 = instant where died. 3 = base or respawn_west marker. 4 = respawn with team, or bird. 5 = into AI or bird.
//RespawnDelay = 35;   //Delay prior to respawn, ensure longer than BTC revive delay.
//RespawnDialog = 1;  //Default = 1. show respawn timer and scoreboard when killed.
Respawn = 3;
RespawnDelay = 45;
respawnTemplates[] = {"Revive", "MenuPosition"};
//respawnOnStart = -1;
RespawnDialog = 1;
***

**Comment by tym32167** [comment]
@a11archer как это поможет респать пилотов отдельно от остальных?

**Comment by a11archer** [comment]
Еще есть BIS респавн
***
respawnTemplates[] = {"Revive", "MenuPosition"};
***

**Comment by a11archer** [comment]
Игроки сами отмечают место респавна. к примеру положил палатку и в неё ресаешься.

**Comment by a11archer** [comment]
Хм. я что-то не подумал что кроме пилотов палатку кто-то еще будет использовать...

**Comment by tym32167** [comment]
>Игроки сами отмечают место респавна

NOOO

**Comment by Noart537** [comment]
можно условие сдалть ```sqf if typeOf player = "пилот" then респ на палатке ``` пока не нашел как это правильно написать.

**Comment by Noart537** [comment]
Нашел способ, будет исправлено в 3.5
