### ISSUE TITLE
Строительство Базы 

### ISSUE THREAD

**Issue by GRIDSW** [TEHGAM/ADR#360]
Практически завершил все постройки на базе. Сейчас в процессе тестирования игроками, на удобность расположения обьектов на ней, почти каждый день полирую ее.

Несколько моментов по базе:

- создаю ее на той основе, на которой сейчас ТГ2
- базу создавал из соображений культуры поведения на ней, прошу прощения, но много обезьян играет на сервере, надо было построить базу так чтоб они во время своего обучения Арме не мешали другим игрокам!!! (при тесте пристально наблюдаю за поведением игроков, есть успехи)
  
Одновременное расположение обьектов вместе очень тормозят игровой процесс! из этого:

- базу перестроил так чтоб разная техника была в разных местах
- очень тщательно просчитывал обьекты в трех основных зонах базы, чтоб не много было (ненужный хлам убирал, но не нарушал атмосферу)
- база построена таким образом, что люди не захотят тупо сидеть на респауне\ ждать вертолета на площадке, а будут сразу организовываться на задания (вариантов будет несколько) 
- игроки с интересом будут распределяться по базе, существует место для сбора и организации отрядов, там же можно загрузить машины инветарем не боясь что машину стырят во время этого процесса (это была большая проблема) 
- база была немного ограничена в проходимости пехоты, это мне позволило убрать пехоту с тех мест, где ей быть не положено. 
- очень хорошо продумал расположение зон с наземной техникой, технику ставил на свое усмотрение (баланс использования учитывал) потом обьясню что и зачем я туда поставил, как я говорил - все со смыслом:)
- очень хорошо проработал авиационную часть: база вертолетов, грузовая площадка, место для подбора пехоты, техника для обслуживания авиации.

что получат вертолетчики: 
- интересную, возможно, чуть сложноватую базу (пусть улучшают навыки посадки, а пассажиры увидят кто хороший пилот), грузовая площадка позволит забирать оттуда технику с игроками, если пилоты не будут механиками, то мы будем организовывать эвакуации\ремонт подбитых вертушек (малой) ремонтной техникой, которые могут поднять от гост хока и мощнее вертолеты  
- просьба к миссиям: если есть возможность оставить "зенитные допки" возле базы, оставьте, это будет мотивировать игроков использовать наземные транспортные средства, а пилотам придется организовывать выполнение допки, процесс интересен + 

Есть у меня и просьбы о помощи:
 1. мне нужен скрипт для респауна ХИСов, они тухнут и то что я сделал выглядит не так как было задумано, скрипт можно одолжить с 3го сервера, там ХИСы горят целую ночь на базах
 2. очень хотелось бы прямо сейчас запускать частично эту базу на ТГ2 для теста хотя б на пол дня, я на много быстрее смогу доработать ее путем наблюдения за игроками, и убрать лишнее\отредактировать\добавить недостающие обьекты, пока имею время и огромнейшее желание заниматься этим вопросом. (для запуска на сервере надо обязательно починить место респауна пилотов, без этого никак, добавить на технику, которую я поставил, скрипты и привязку к зевсу)

Спасибо.

**[UPD 5](http://www.tehgam.com/viewtopic.php?f=36&t=1846&p=15436#p15436)**

**Comment by GRIDSW** [comment]
UPD 5 http://www.tehgam.com/viewtopic.php?f=36&t=1846&p=15436#p15436

**Comment by a11archer** [comment]
Grid, с сайта http://windows.github.com пожалуйста поставь клиент для репозитория. Вне репозитория изменения не производятся. Скачай себе локально текущую сборку и посмотри чтобы она обновилась. После этого можно будет ставить\убирать вертолетную площадку в стабильной ветке. Я много раз замечал как параллельные ветки бьются, так что пожалуйста если будешь выкладывать то попробуй сразу в главную ветку Github\tehgam\Adr . Её откатить проще чем конфликты версий битые восстановить. При запуске клиента Git всегда нажимайте кнопку обновления текущей версии иначе можно устроить конфликт на сервере репозиториев исправив свою устаревшую копию ADR миссии. Как скриптами делать респавн у хис я не знаю, пробую написать скрипт. Загружать тестовую версию можно только отсюда! (из репозитория).

**Comment by a11archer** [comment]
Хис не возвращает тип дропа при помощи CursorTarget, я не знаю толком как называется обьект.
Из твоей работы я понял что ты использовал не хис а Land_Flush_Light_red_F и такой-же зеленый. В других миссиях они не исчезают из чего я стал подозревать конфликт с другими скриптами. Скорее всего которые дроп на базе очищают. Я проверял на дропе (хис) он тоже не пропадает.

**Comment by a11archer** [comment]
[Я подозреваю вот этот скрипт](https://github.com/TEHGAM/ADR/blob/master/Annex_Done_Right.Altis/scripts/cleanup/repetitive_cleanup.sqf)

**Comment by a11archer** [comment]
Подобного скрипта в твоей версии миссии и ветке [279EUP](https://github.com/TEHGAM/ADR/tree/master/.devfiles/co60_AW_Invade_Annex_2_79E_UP.Altis) я не нашел. Через какое время пропадает хис?

**Comment by a11archer** [comment]
Наверное в initServer 
строка _null = [] execVM "scripts\misc\clearItemsBASE.sqf";
и этот скрипт править придется.

**Comment by GRIDSW** [comment]
a11archer, я не очень рассшарен в GitHub, по пробую разобраться на досуге.
по поводу хисов, надо попросить глянуть какой скрипт стоит на ТЕHGAM 3, там на базе хисы целую ночь светятся

**Comment by a11archer** [comment]
проверял на отладчике командой nearestObjects [player,["weaponholder"],10]; явно скрипт не реагирует на лампы и реагирует на хисы

**Comment by a11archer** [comment]
На Tehgam3 Доступа нет. Он в закрытом репозитории у Рико. Разбинаривать если только... у меня средств нету. C:\Users\%username%\AppData\Local\Arma 3\MPMissionsCache

**Comment by GRIDSW** [comment]
Оказывается, можно поставить рекламный щит с изображением на нем, для этого нужно в папку медиа бросить картинку с названием сервера, ТС и прописать это дело, если интересует, могу достать инфу по этому вопросу 
![2015-03-29_00006](https://cloud.githubusercontent.com/assets/11561371/6885515/6d3727ec-d62b-11e4-8292-506a68a81f93.jpg)

**Comment by Noart537** [comment]
Чем меньше всякой всячины, тем лучше! У нас пока железо не тянет нормально миссию. 

Всякие ящики, левую технику,флажки можно убрать. Т.к. При падении вертолета в кучу ящиков все это дело разлетается, создавая нагрузку на проц, и безпорядок на базе. 

Если ящики скриптовать, то тоже лишние скрипты лишние лаги.

GRID. Попробуй упростить немного.

**Comment by GRIDSW** [comment]
надо народ запускать, потом хлам буду по-тихоньку чистить, лишнего не хочу убирать
