### ISSUE TITLE
Проблемы с внутриигровым чатом

### ISSUE THREAD

**Issue by tym32167** [TEHGAM/ADR#364]
Один из внутриигровых админов [рассказал про баг](http://www.tehgam.com/viewtopic.php?f=225&t=1877&p=15635)

>. Имеется баг отключения отображения сообщений во внутриигровом чате после включения "камеры". Лечится только полным выходом из ARMA.

**Comment by Noart537** [comment]
Что за камера, не могу понять.

**Comment by Noart537** [comment]
Закрываю. Текста "камера" нет в миссии. Возможно имели ввиду функцию камеры для внутри-игровых администраторов при включенной консоли enableDebugConsole в description.ext. На данный момент она отключена.
