### ISSUE TITLE
Пропадают батарейки для ЛЦУ после смерти

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#370]

**Comment by rlex** [comment]
БИСовый баг, кстати.

**Comment by ToxaBes** [comment]
Похоже что батарейка не добавляется в массив магазинов и `BIS_fnc_loadInventory` не загружает ее обратно. Можно попробовать полечить также как и с пропадающим оружием в #381 
Для этого в строку 1149 [ https://github.com/TEHGAM/ADR/blob/master/co60_AW_Invade_Annex_2_79.Altis/scripts/%3DBTC%3D_revive/%3DBTC%3D_functions.sqf#L1149 ] вставляем сохранение батарейки:
```sqf
private['_curWep', '_laserbatteries'];
_curWep = currentWeapon player;
if("Laserdesignator" in assignedItems player) then
{
	player selectWeapon "Laserdesignator";
	if(currentMagazine player != "") then 
    { 
        _laserbatteries = currentMagazine player;
    };
};
player selectWeapon _curWep;
```
и после вызова `BIS_fnc_loadInventory` в строке 1168 [ https://github.com/TEHGAM/ADR/blob/master/co60_AW_Invade_Annex_2_79.Altis/scripts/%3DBTC%3D_revive/%3DBTC%3D_functions.sqf#L1168 ] добавляем батарейку:
```sqf
if(_laserbatteries) then
{
	if ("Laserdesignator" in assignedItems player) then {
	    player selectWeapon "Laserdesignator";
        if(currentMagazine player == "") then {
            player addmagazine "laserbatteries";
	    };
	}
	else
        {
            player addmagazine "laserbatteries";
        };
}
```
Код не тестировал, написал на коленке примерный вариант (sqf язык не знаю если честно, но трабла с батарейками надоела).

**Comment by Noart537** [comment]
Возможное решение (надо проверить)
{_x AddMagazineGlobal "Laserbatteries"; _x addWeaponGlobal "Laserdesignator"; } FOREACH  allUnits; 
в файл onPlayerRespawn

**Comment by Noart537** [comment]
if player hasWeapon "Laserdesignator" then {
AddMagazineGlobal "Laserbatteries";
};

**Comment by ToxaBes** [comment]
Исправил батарейки - проблема была в скрипте BTC_revive + BIS-овый баг. У себя потестил - отлично работает вне зависимости нажато сохранено снаряжение или нет. 
@Noart537 - проверь пожалуйста. Если работает в мультиплеере то мы также сможем исчезающее оружие исправить.

**Comment by ToxaBes** [comment]
@malashin , @Noart537  - новый патч для батареек в новой ветке 370_laserbatteries_bug
Я проверил его на своем тестовом сервере с игроком Corel - все работает. Нужно применять на TG2 и смотреть результат.

**Comment by Noart537** [comment]
Антон если все работает, то заливай в dev ветку. В субботу утром зальем на сервер потестим.

**Comment by ToxaBes** [comment]
Смерджил в dev ветку.
