### ISSUE TITLE
Mag repack 

### ISSUE THREAD

**Issue by rlex** [TEHGAM/ADR#378]
Можно http://www.armaholic.com/page.php?id=19692 интегрировать? За отсутсвием эйса на Tehgam 2 очень скучаю по этой фиче. Могу PR прислать.

**Comment by Noart537** [comment]
Позже гляну, как с обновлением миссии закончу.

**Comment by Noart537** [comment]
В ближайшем обновлении протестируем, переведем и если все работает, то добавим.

**Comment by malashin** [comment]
Мод не понравился, много лишней возни мышкой.

Сделаю простой скрипт который сам все магазины перепакует.

**Comment by Noart537** [comment]
Как закончите скрипт, закрывайте эту тему

**Comment by malashin** [comment]
Я закончил. Пускай пока повисит, нужно на живом сервере потестить.
