### ISSUE TITLE
Невозможно загрузить лоадаут в арсенале

### ISSUE THREAD

**Issue by rlex** [TEHGAM/ADR#379]
Tehgam 2.
Собрал себе несколько наборов в арсенале в зависимости от роли.
Работали пару дней назад
Сегодня захожу - все серые. Ладно, мало ли апдейт какой.
Собрал новый с нуля. Сохранил. С сервера не выходил, роль не менял. 
Набор серый, загрузить невозможно. 
Перезашел, сохранил дефолтный набор для снайпера.
Тоже серый, загрузить невозможно.
Частично, конечно, решается VASом, он сохраняет и грузит нормально, хоть и выдает ошибку скрипта.

UPD: никаких модов при игре на tehgam 2 не использую.

**Comment by Noart537** [comment]
Проверь, не выбран ли у тебя модуль БПЛА. Он по умолчанию вешается. И если собираешь в арсенале, потом в VAS что-то добираешь и сохраняешь снова в арсенале, то он будет серым.

**Comment by rlex** [comment]
Модуль БПЛА = UAV Terminal? Если да, то нет такого в кармашках, обычный GPS только есть.

**Comment by Noart537** [comment]
Поработаю в выходные над арсеналом. Он у нас реализован белым списком. Что внесено в список, то отображается. Переделаю в черный список. Если все получится, запустим в ближайших обновлениях.

**Comment by a11archer** [comment]
То что арсенал не грузится если сохранен запрещенный (отсутствующий в белом списке арсенала Item) Item это недосмотр Бисов. Есть даже мод исправляющий эту проблему. Думаю они вскоре должны исправить. Иначе если меняется баланс либо разрешенное оружие - каждый раз придется удалять слот в арсенале.
[URL="http://www.armaholic.com/page.php?id=27155"]Ссылка на мод исправляющий проблему"[/URL]

**Comment by malashin** [comment]
Как я понял, это баг у Бисов. Я делал один и тот же лоадаут в арсенале два раза, в первый раз он серый был, во второй всё нормально. В итоге, просто, при сохранении лоадаута сохраняю его в новый слот, выхожу из арсенала и смотрю можно его загрузить или нет. Если нельзя, то заново делаю.
