### ISSUE TITLE
CHVD

### ISSUE THREAD

**Issue by rlex** [TEHGAM/ADR#380]
В своих миссиях активно использую вот [этот](http://www.armaholic.com/page.php?id=27390) скрипт для управения дистанцией, гораздо удобнее TAW_VD (раздельные настройки прорисовки объектов для пешего/наземного/авиации), плюс сохраняет настройки в профиль (настройку в скрипте тоника каждый раз заново подкручивать надо). 
Было бы неплохо увидеть его в миссии.

**Comment by Noart537** [comment]
Спасибо, протестируем и возможно обновим.

**Comment by malashin** [comment]
Оставляем старый. Польза не существенная от изменений.
