### ISSUE TITLE
Исчезает оружие и/или вещи из инвентаря

### ISSUE THREAD

**Issue by ToxaBes** [TEHGAM/ADR#381]
Описание: После того как медик поднял павшего игрока у последнего пропадает оружие и/или почти все содержимое в инвентаре.

Есть подозрение что дело в используемом [скрипте BTC_Revive](https://github.com/TEHGAM/ADR/blob/master/co60_AW_Invade_Annex_2_79.Altis/scripts/%3DBTC%3D_revive/%3DBTC%3D_functions.sqf#L1168):
```sqf
[player,[player,"KilledInventory"]] call BIS_fnc_loadInventory;

if (!isNil killed_PrimaryWeapon) then {
    player addWeapon killed_PrimaryWeapon;
    {player addPrimaryWeaponItem _x;} count killed_PrimaryWeaponItems;
};
```
В этих строках мы загружаем обратно все что было в инвентаре и суем игроку в руки primary weapon. Проблема в том что ни `KilledInventory` ни `killed_PrimaryWeapon` / `killed_PrimaryWeaponItems` не заданы явно в скрипте перед смертью. Я предлагаю заполнять эти параметры прямо после смерти в момент "затухания" экрана. Например изменить код (строка 1146) с:
```sqf
BTC_player_killed =
{
   private ["_type_backpack","_weapons","_magazines","_weapon_backpack","_ammo_backpack","_score","_score_array","_name","_body_marker","_ui"];
   titleText ["", "BLACK OUT"];
```
на:
```sqf
BTC_player_killed =
{
   private ["_type_backpack","_weapons","_magazines","_weapon_backpack","_ammo_backpack","_score","_score_array","_name","_body_marker","_ui"];
   titleText ["", "BLACK OUT"];
   [player,[player,"KilledInventory"]] call BIS_fnc_saveInventory;
```
Эта вставка позволит загружать убитому бойцу именно то что было в момент смерти в инвентаре. Если заработает, можно туда же добавить сохранение текущего оружия с обвесами на момент смерти.

**Comment by Noart537** [comment]
Спасибо, проверю и отпишусь.

**Comment by malashin** [comment]
@ToxaBes посмотри, что с этой задачей и закрой её.

**Comment by ToxaBes** [comment]
Потестил на локальной версии миссии с игроком Keiz - работает. Смерджил в dev ветку.

**Comment by ToxaBes** [comment]
При исчезновении оружия игроку дается новое оружие - базовое для его класса, а не то которое было.

**Comment by ToxaBes** [comment]
Поправка: игроку дается такое же оружие как у поднявшего. Это баг addWeaponGlobal + баг локальности чтения переменных из профиля игрока. Нужно переносить вызов функции восстановления оружия на клиент (к тому кого подняли).

**Comment by ToxaBes** [comment]
Нужно обновить миссию на TG2 и проверить.

**Comment by ToxaBes** [comment]
Закрываю тикет до новых проявлений бага.
