### ISSUE TITLE
Закрытие наградной техники

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#385]
Наградную технику закрывать на 10 минут, чтобы бойцы могли успеть добраться до нее.

**Comment by Noart537** [comment]
Если у нас наградная техника вся _veh то если _veh lock; закроется вся? Как думайте?

**Comment by ToxaBes** [comment]
Локально - по идее да. В мультиплеере - надо тестить.

**Comment by Noart537** [comment]
Старая техника не закрывается. Проверил, закрываю.
