### ISSUE TITLE
Настроить "Headless clients"

### ISSUE THREAD

**Issue by ToxaBes** [TEHGAM/ADR#397]
Предлагаю продолжить тему с безголовыми клиентами тут.
Как успехи? Нужна ли помощь? На подходе вторая миссия из режима Спецопераций в связи с чем хотел бы услышать какой-нибудь status update по этой теме.

**Comment by malashin** [comment]
Пока времени не было. Я посмотрел как там, что делается. Всё понятно. Осталось, просто, сделать это.

**Comment by ToxaBes** [comment]
Спасибо за ответ, это здорово что понятно как сделать. Просьба добавить 2 безголовых клиента. Первый клиент для ботов основы. Второй для ботов допок и спецопераций. Все что не боты можно оставить на процессе сервера. Как-то так.

**Comment by malashin** [comment]
Что-то пока ничего хорошего не вышло. Клиенты подключаются нормально. Чтобы они управляли ботами, нужно у них локально их создавать. Когда боты на HC появляются, почему-то нагрузка растет еще и на сервере и достаточно сильно. В итоге получается, что  ядер задействовано больше, нагрузка общая на процессор больше, а производительность падает.


Только сервер
![Image](http://i.imgur.com/ezFjKXI.jpg)

Сервер и один HC, все боты локально у HC созданы
![Image](http://i.imgur.com/xnriok8.jpg)

Сервер и два HC, боты распределяются round-robin скриптом.
![Image](http://i.imgur.com/8L5LGO8.jpg)

Во всех случаях на один процесс при высокой нагрузке уходит ~100-125% мощности одного ядра (без hyper-threading'а у меня 400% максимум, т.к. 4 ядра всего). При трех процессах CPU почти под 400% используется. Если один сервер использовать, то 100-125% при более высоком фпс.

Всё это дело на Линуксе. Миссия пустая, только боты.

**Comment by ToxaBes** [comment]
Похоже что проблема в том что ты тестил на линуксе и не использовал sched_setaffinity/taskset. В итоге у тебя процессы по ядрам раскидывал стандартный планировщик, которому мешала навешенная балансировка по round-robin, т.к. они оба пытались делать одно и тоже :) 

Безголовые клиенты имеют смысл только на Windows, т.к. суть данного действа - иметь AI в отдельном процессе которому можно назначить конкретные процессорные ядра. В таком случае планировщик не участвует и рулит только балансировка.
В Windows можно прямо через через диспетчер задач мышкой жестко задать каждому процессу отдельные ядра, либо указать их в ярлыке запуска с помощью ключа /AFFINITY:

>If the Arma 3 Headless Client and a Arma 3 Dedicated Server are running on the same Windows computer (VM or physical), it may be beneficial to set processor affinity to prevent execution intensive threads from being scheduled across the same (v)CPUs. The operating system will generally schedule threads efficiently, but manual CPU allocation is possible. This can be achieved by right-clicking on the process (e.g. Arma3Server.exe(*32)) in the processes tab of the Windows Task Manager and selecting Set Affinity.... Be aware that on a physical intel CPU, the odd numbered CPUs are Hyper-thread cores.
Note: You can use automated solution for affinity assign via batch file with commandline
CMD /AFFINITY HEXvalue e.g. CMD /C START /AFFINITY 0xF3 arma3server.exe

В итоге получается что-то типа:
arma  server - 1 core
headless client 1 (с ключом -cpucount=2) - 2 cores
headless client 2 (с ключом -cpucount=2) - 2 cores
Если ядер не хватает, можно всем по одному дать.

Вот ребята использовали headless client для миссии с 500 ботами: https://www.youtube.com/watch?v=Unx5aHGWyF0

**Comment by ToxaBes** [comment]
Похоже что основная проблема была в ширине интернет-канала. Текущий вариант хорошо работает.
