### ISSUE TITLE
Ошибка icon_debug_ca.paa

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#398]
файл co47_ADR_Red_Lynx.Altis/scripts/=BTC=_revive/=BTC=_functions.sqf
строка 20,23,24,25. 
Ошибка: не найден файл icon_debug_ca.paa
![7ebc346f34e153a86d20151113095224](https://cloud.githubusercontent.com/assets/8770445/11142667/f6662362-8a10-11e5-8ffc-dccd5778218f.jpg)

**Comment by malashin** [comment]
Я не дома, проверить не могу. Но путь, по-моему, такой должен быть:

```sqf
\a3\ui_f\data\gui\rsc\rscdisplayarcademap\icon_debug_ca.paa
```
