### ISSUE TITLE
Артиллерия

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#399]
Экипаж артиллерии это красные бойцы. Ее тут же расстреливает собственная охрана.
![2015-11-18_00001](https://cloud.githubusercontent.com/assets/8770445/11240851/a526530e-8e17-11e5-935e-0edf9cacfdb5.jpg)

**Comment by ToxaBes** [comment]
Замени строку https://github.com/TEHGAM/ADR/blob/dev/co47_ADR_Red_Lynx.Altis/mission/side/missions/priorityARTY.sqf#L72 на 
```
_priorityGroup = createGroup west;
```

Тоже самое для "Приоритетная цель: Зенитная батарея":
https://github.com/TEHGAM/ADR/blob/dev/co47_ADR_Red_Lynx.Altis/mission/side/missions/priorityAA.sqf#L83

**Comment by Noart537** [comment]
Поправил, спасибо!
