### ISSUE TITLE
Допилить синих и запустить на сервере.

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#401]

**Comment by PR9INICHEK** [comment]
Не знал куда написать, написал сюда. Восстановите мой аккаунт на форуме TEHGAM.
P.S. Демобилизовался

**Comment by malashin** [comment]
Арт для синей миссии.

![adr_blueshark_loading](http://i.imgur.com/AuBphYr.jpg)
http://i.imgur.com/AuBphYr.jpg

**Comment by Noart537** [comment]
PR9INICHEK придется тебе заново регистрироваться. У нас сменился движок форума. Те аккаунты, под которыми не заходили долгое время, удалены.

**Comment by PR9INICHEK** [comment]
Noart537 Понял, спасибо за быстрый ответ!
