### ISSUE TITLE
Переделать основное задание

### ISSUE THREAD

**Issue by malashin** [TEHGAM/ADR#412]
Нужно переделать основное задание. На данном этапе собираем идеи, которые нужно будет реализовать и обсуждаем их. Список будет дополнятся.
___
## Список задач:
1. **Выполнение основы должно что-то давать игрокам, что они бы теряли в случае проигрыша обороны. Или, просто, как-то наказывать за проигрыш обороны.**
  * Самый простой вариант это не заканчивать оборону по таймеру, а обязать игроков убить почти всех атакующих ботов. Поставить очень долгий таймер на случай, если боты застряли где-нибудь.
2. **Добавить новые задачи.**
  * В двух километрах от точки появляется небольшой лагерь с охраной. Из него выезжает грузовик с отрядом солдат или просто отряд пешком идёт к основной точке. Если этот отряд уничтожен, то через 5 минут появляется новый отряд в лагере и снова идёт на основу. Если лагерь уничтожить, то отряды больше не появляются. (Лагерь можно взорвать, можно перебить охрану, можно нажать что-то внутри, убить радиста/офицера и т.д.).
3. **Добавить разнообразия.**
  * Набор войск и задач на основе не постоянный, а выбирается случайным образом.
  * Динамические изменения на основе. Например прибытие подкрепления, десанта, вертолета и т.д.
4. **Сделать количество солдат противника зависимым от количества игроков на сервере.**
  * На основе в любом случае должно быть достаточно много ботов, но можно урезать тяжелую и легкую технику, вертолеты на основе в случае если на сервере мало человек.
5. **Переписать саму структуры вызова заданий.**
  * Сейчас в миссии вызываются пять разных скриптов, каждый из-них сделан под разные географические части острова. Сами скрипты внутри одинаковые, просто разные массивы в начале. На мой взгляд, это крайне кривая реализация.
6. **Добавить новые географические позиции в варианты появления основы.**
7. **Добавить возможность отключения основы и допзадания для проведения миссий Зевса.**

**Comment by malashin** [comment]
Главная проблема это продумать общую концепцию того как влияют результаты разных задач (основа, допки, спец операции) на геймплей. Сейчас т.к. у игроков есть почти всё на базе им ничего и не надо. Нужно, либо что-то урезать и давать за задания, либо придумать другой вариант награды.

Как вариант можно убрать маршал с базы. Получается, что у игроков есть только легкий транспорт. За допки они получают один пул техники попроще. За спец операции танки и боевую авиацию.

**Comment by ToxaBes** [comment]
Также на основе можно немного защитить вышку. Вокруг вышки поставить один 
![Land_Cargo_HQ_V1_F]
(https://community.bistudio.com/wikidata/images/e/e2/Arma3_CfgVehicles_Land_Cargo_HQ_V1_F.jpg)
и парочку
![Land_Cargo_House_V1_F]
(https://community.bistudio.com/wikidata/images/e/e5/Arma3_CfgVehicles_Land_Cargo_House_V1_F.jpg)
и заселить их пехотой.

**Comment by malashin** [comment]
Вокруг вышки можно еще бетонные блоки накидать, чтобы в неё заехать нельзя было и заложить заряд быстро. Опять же сделать это рандомным, иногда они есть, иногда нет.

**Comment by malashin** [comment]
На счет лагеря который спавнить ботов постоянно, можно развить тему. Сделать казарму из котором пехота появляется. Сделать гараж из которого ифриты появляются.

**Comment by ToxaBes** [comment]
Вместо бетонных блоков можно поставить ПТ-шников на втором этаже военного бункера.
По лагерю надо будет продумать какие здания использовать. Например можно купол-ангар и большую военную вышку. Пока военную вышку не подорвут - из ангара будет спавниться грузовик с пехотой и ехать на основу. Если его уничтожат то через 10 мин поедет следующий грузовик и т.д.
![Land_Dome_Small_F]
(https://community.bistudio.com/wikidata/images/a/a9/Arma3_CfgVehicles_Land_Dome_Small_F.jpg)
![Land_Cargo_Tower_V1_F]
(https://community.bistudio.com/wikidata/images/3/3f/Arma3_CfgVehicles_Land_Cargo_Tower_V1_F.jpg)

**Comment by tym32167** [comment]
Для начала, я предлагаю изменения внедрять по очереди, а не всё сразу. Внедрить одно изменение, выждать недельку, потом второе. 
Также каждое изменение прогнать через наш процесс http://www.tehgam.com/showthread.php?t=1718 , документ по процессу http://1drv.ms/1Lu3NJK
Далее, пункты от Эвила:
1. Наказывать за проигрыш обороны смысла не вижу. Максимум - это респать основу на том же месте. 
2. По поводу новых задач - мысль интересная, но бесконечный поток пехоты, мне кажется, не самая лучшая идея. Мне кажется, надо что то геймплейное придумать. Например, побочное задание основы с наградой. Или, если основа в городе, заселять дома пехотой. Ну, или, не знаю, при падении вертолета на основе нужно забрать с него разведанные, а куда он упал - высаживается срочно десант для охраны. 
3. Набор войск это да, только не случайным образом, а сменить на что то более жесткое
4. Это зря, мне кажется. Народ моджет толпой прибежать и толпой убежать. И что, на основе сначала респанется гора техники и потом самоустранится? 
5. Не понимаю зачем это делать. Какие плюсы от этого и кому?
6. Я за. 

По поводу вышки. Самое эффективное, что я делал, это 3 зенитки вокруг вышки, обложенные мешками (такие высокие квадратные, как на артиллериии). Обложены с той целью, чтобы сложнее было их подбить титаном. Ни разу на моей памяти такое быстро не взяли. Если ещё и подход вышки для транспорта перекрыть, будет тоже круто. 
Также я предлагал сделать 2 вышки, и подорвать их можно только синхронно. То есть в одного основу не сделать. И вышки чтобы вызывали не только самолет, но и технику и пехоту. А то сейчас можно замочить всех на основе, оставить только вышку.
На допках, которые в городе, определенно не хватает пехоты в зданиях. Я вчера добавил 60 пехов на прерванном полете (Тохиным скриптом), взятие допки растянулось на несколько часов. 

Накидать сюда хотелок - это хорошо, и я предлагаю одминам это обсудить и взяться за самые простые.

**Comment by ToxaBes** [comment]
Вы главное помните что цель не усложнить основу и сделать ее интереснее. Т.е. зенитки у вышки это по-моему перебор (хотя проходятся одним страйдером на раз - я тебе показывал уже). Синхронный подрыв - тоже сильное усложнение. Основа должна быть проходима в одно лицо, пусть и с десятком смертей в процессе.

**Comment by malashin** [comment]
Мы сейчас кидаем идеи и приходим к общей концепции, так как она не ясна сейчас. Как будут идеи толковые можно за них голосовать админам. Делаться всё это будет не сегодня и не завтра. Основная задача и разнообразние, а не сложность.

2. Я тоже об этом подумал. Можно задачи с легких допок реализовать на основе. Допустим в этот раз на основе появилась группа зениток и омечен район на карте, их нужно уничтожить для выполнения основы. В следующий раз не зенитки, а что-то другое.

3. Не просто случайная мешанина, а случайный выбор из заготовленных наборов. Я это на обороне делал.

4. Если людей на сервере мало, то техники не много и не нужны горы станционаров и ПТшинков. Если зашло больше людей, то на следующей основе техники будет больше. Проверка идет только при создании основы.

5. Плюсы разработчикам. Изменяя одну строчку приходится изменять её в пяти файлах. Они абсолютно одинаковые. Их логичнее вызывать функцией кидая в них нужные локации для основы.

**Comment by tym32167** [comment]
4. Проблема в том, что респанешь ты кучу пехов, а потом игроки толпой выйдут и оставшиеся не вывезут основу. Или респанешь мало пехов, и зайдет толпа, которой, чтобы начать играть интересно, надо будет сначала задушить кучку пехов на основе и полчаса держать оборону, только после этого появится основа с кучей пехов. Мне кажется, это излишне. Да и добавит только сложности в код миссии, а профита для игроков я не вижу. 
5. За это, имхо, можно и не голосовать, так как для игроков ничего не изменится. Соберитесь разработчиками, решите, надо или нет, и, если надо, сделайте.

**Comment by AlexVDem** [comment]
За проигрыш обороны конечно наказывать не надо, но хотя бы сообщать что оборона была провалена стоит. И может быть поместить на базе "доску позора" с этим сообщением до конца сл. основной миссии. Насчёт задания - предлагаю вместо 2-х типов вышек делать несколько, не только радио, но и сторожевую вышку, купол, здание и т.д., которые надо взорвать.

**Comment by AlexVDem** [comment]
Кстати, было бы прикольно, если бы в случае успешной обороны на базе появлялась какая то наградная техника, и если это не авиация, пользоваться ей мог бы только тот, кто был в триггере все время обороны.

**Comment by tym32167** [comment]
>пользоваться ей мог бы только тот, кто был в триггере все время обороны
Это может быт лишним. Остался ты один в обороне, всех перебили, а ты ушел с сервера - награда без хозяина. 
Решил получить награду за оборону - убил себя и лежи в триггере, пока не кончится - куча трупаков-халявщиков
и тд. Такие усложнения все только усложнят )

**Comment by AlexVDem** [comment]
Ну может быть. Но всеравно хотелось бы сделать оборону интереснее, какой то стимул дать. А то сейчас она заканчивается одинаково для всех, что с тобой, что без тебя.

**Comment by ToxaBes** [comment]
Давайте как-то разделим эти улучшения на категории: захват основы, вышка, оборона.

**Comment by ToxaBes** [comment]
Из того что есть сейчас из годнго для дальнейшего рассмотрения:
**Общее**
* Добавить новые географические позиции в варианты появления основы. (Много основ в чистом поле с минимумом укрытий. Даешь основу в Кавале)
* Переписать 5 скриптов вызова основы в один.
* За основу не должно быть никакой награды. Основа сама по себе награда.

**Вышка**
* Около вышки поставить один бункер, пару будок и заселить пехотой и ПТ-стрелками.

**Захват основы**
* В двух километрах от точки появляется небольшой лагерь с охраной. Из него выезжает грузовик с отрядом солдат или 1 ифрит (рандомно) в зону и там патрулирует. Если этот отряд уничтожен, то через 10 минут появляется новый отряд в лагере и снова идёт на основу. Если лагерь уничтожить (вариант: зайти в бунер и нажать на кнопку самоликвидации базы), то отряды больше не появляются. Наземный аналог вышки и штурмовика на основе.
* Если в зоне основы есть дома, то заселять часть пехоты в зданиях.

**Оборона основы**
* Не заканчивается пока не уничтожено 90% наступающих.
* Если в круге обороны в течении минуты нет ни одного живого игрока. Оборона проиграна и следующая основа появляется там же.
* Сделать больше мелких отрядов противника, атакующих с 2х, 3х сторон.

Админы - добавляйте/исправляйте тут пункты которые потом будете обсуждать.

**Comment by malashin** [comment]
> Если в круге обороны в течении минуты нет ни одного живого игрока то оборона проиграна и следующая основа появляется там же.

Мне не нравится такое решение. Просто скучно делать основу в том же месте второй раз. Если мы наказать никак не можем, то пускай убьют почти всех атакующих ботов, а не просто убегают с обороны, как сейчас.

Есть еще баг в старом триггере. Мертвые игроки которых не поднял медик еще лежат на обороне и считаются как обороняющиеся.

**Comment by ToxaBes** [comment]
> Просто скучно делать основу в том же месте второй раз.

Это и есть наказание за провал обороны.

>
Мертвые игроки которых не поднял медик еще лежат на обороне и считаются как обороняющиеся.

Потому я и написал "нет ни одного живого игрока".

**Comment by malashin** [comment]
Это не наказание усложняющее жизнь или добавляющее интереса и разнообразия игровому процессу.

**Comment by ToxaBes** [comment]
Мне кажется это единственное что может заставить игроков ехать на оборону - нежелание захватывать основу еще раз в этом же месте. Т.е. тут или вводить такое "наказание" за провал основы или не вводить никакого наказания вообще. Оставь пока этот пункт для админского голосования, там разберетесь.

**Comment by AlexVDem** [comment]
Может всё-таки введем пока хоть какое то уведомление о проведённой обороне и наградную технику за удачную. А потом решим как наказывать.

**Comment by ToxaBes** [comment]
Если честно, я не могу понять - зачем давать награду за основу? Это же ломает всю логику.
Смысл тогда наград на допках/спецоперациях? Ценность награды исчезает если ее дают за все.
Если давать награду за все миссии, то наградной техники будет больше чем надо. 
Сейчас на допке/спецоперации заработали технику, затем на основе ее успешно про..потеряли. Круговорот техники на сервере.

Представь что выиграли 2-3 основы подряд + пару допок -> у игроков начнут появлятся танковые клинья из наградной техники которыми будет выполнять миссию все проще и проще...Смысл?
Награда за основу это интересный захват и интересная оборона. Именно это мы и стремимся сделать.

**Comment by AlexVDem** [comment]
Награда не за основу, а за оборону, оборона не всякий раз появляется. Это тоже своего рода спецмиссия. Можно за оборону дать что-то менее ценное, несколько "одноразовых" страйдеров, страйдер с пулемётом, разноцветные джипы, квадрики, ещё один буззард, тару с модулем сидений, мору (её и так нет в наградных) и пр. А за спецмиссии давать что-то серьёзное, зенитки, танки, ударные вертушки.

**Comment by ToxaBes** [comment]
@AlexVDem - разумно. Добавил в список на голосование.

**Comment by malashin** [comment]
Может за проигранную оборону ставить зенитный комплекс на её месте? Не в цикле допок, а новый цикл. Проиграли оборону, появился "Укрепление: Зенитный комплекс", если до следующей проигранной оборону никто его не вынес, то он стирается и появляется на новом месте. На нём минимум ботов: отряд ПТ, камыш и сами зенитки.

**Comment by ToxaBes** [comment]
Допиши как вариант в список на голосование

**Comment by AlexVDem** [comment]
Не, на полкарты не надо. Обычные зенитки - можно. Иначе пилоты туда не полетят, и вообще никуда не полетят. Игрокам придётся переть на задания своим ходом, а это мало кто любит, значит играть будет менее интересно.
