### ISSUE TITLE
Обозначение на карте полезных мест на базе

### ISSUE THREAD

**Issue by ToxaBes** [TEHGAM/ADR#413]
**DeD Pikhto =rus=** [предложил](http://www.tehgam.com/showthread.php?t=695&page=32&p=14705&viewfull=1#post14705) толковую идею:

- [x] Указать ящики с вооружением/снаряжением на карте.
- [x]  Обозначить посадочные площадки для пехов на карте.
- [x] Обозначить место включения ПВО/очистку базы.
* ~~Обозначить место стоянки ремонтной техники (бобкет).~~
- [x] Немного расширить площадь наградной техники, так как парковать самолёты на траве неправильно.
- [x] Таблица доступного вооружения для разных классов.
- [x] Передвинуть ремонтную площадку для вертолетов чуть подальше от ангара на 5-6 метров.
- [x] Передвинуть медицинский грузовик чуть подальше от ремонтной площадки.
- [x] Передвинуть вертолетные посадочные площадки в сторону от столба.
* ~~Добавить скрипт, запрещающий пассажирам открывать рампу Тару, Хурона или модуля.~~

___

Может вместо текста использовать какие-нибудь иконки и вверху на карте дать им расшифровку (или расшифровку при наведении на них, если возможно).

Также можно описать каким классам разрешено какое оружие (например прикрепить тему на форуме с таблицей класс игрока/разрешенное оружие и возможно оружие/разрешенные прицелы). Новички очень много времени тратят пытаясь выяснить что можно/нельзя из оружия.

Как считаете, стоит делать? И кто займется?

**Comment by malashin** [comment]
Маркеры и обозначения я могу сделать. Можно поставить билборды рядом с арсеналом и крупно написать АРСЕНАЛ.

Иконы с легендой можно сделать только если легенда будет прям рядом с базой. Но лучше всё таки подписывать.

С описание классов сложнее. На форум подавляющее большинство не заходит. Придётся писать это в описании при открытой карте. Новички туда не зайдут тоже, но можно будет туда отсылать людей при вопросах. Я таких вопросов обычно не встречаю. Можно опять же сделать билборд с какой-то инфографикой о классах, но это тяжело изобразить будет.

**Comment by ToxaBes** [comment]
Инфографика: строки - картинка оружия + название, столбцы - иконка класса игроков + название. На пересечении - галочка, если доступно и пустое место если не доступно. Можно сделать не билбордом (все не влезет) а пунктом меню рядом с пунктом арсенала и т.д. при вызове пункта будет показан UI (как при установке дальности, меню отрядов и тд) с двумятабами. Первый таб - оружие/классы игроков, второй таб оружие/прицелы. В табах будут таблицы с вертикальной проктуткой. Если подготовишь таблицы - сделаю UI под них.

**Comment by tym32167** [comment]
>Также можно описать каким классам разрешено какое оружие (например прикрепить тему на форуме с таблицей класс игрока/разрешенное оружие и возможно оружие/разрешенные прицелы). Новички очень много времени тратят пытаясь выяснить что можно/нельзя из оружия.

Этому место в инструктаже на карте.

**Comment by ToxaBes** [comment]
Дело в том что там фиксированная ширина и я не знаю как ее поменять или добавить прокрутку. Большая таблица просто не влезет.

**Comment by tym32167** [comment]
Если в таком виде добавить нет возможности, измени вид :)

**Comment by ToxaBes** [comment]
Я подумаю что можно сделать.

**Comment by AlexVDem** [comment]
Может имеет смысл поставить на базе лицом к респу большой биллбоард и написать на нем крупно "ПОМОЩЬ! / HELP!" и написать простой скриптик, который открывает окошко если игрок подходит к биллборад на 3-4 метра? Тогда даже делать ничего не надо будет, просто подойти.

**Comment by tym32167** [comment]
Билбоард, как идея, норм, но вплытие окошка для тех, кто подошел - не гут, оно мешать будет всем, кто будет мимо проходить/пролетать/проезжать. 
Можно билбоард с каким то базовым текстом, например, адрес форума, адрес ТС, отсылка к правилам и кнопку, на нажатие которой перекинет в нужный раздел инструктажа на карте.

**Comment by AlexVDem** [comment]
Ну можно радиус активации скрипта до 2-х метров сократить, а кнопку делать неэффективно, всеравно это лишнее действие, многие не поймут что надо делать, а многие поленятся. Тут простой расчет на любопытство.

**Comment by tym32167** [comment]
Не, тут без вариантов, если ты ничего не нажмешь, а у тебя всплывет какое то окно - это плохо, это будет мешать 100%

**Comment by malashin** [comment]
![Image](http://i.imgur.com/93kCe9q.jpg)
![Image](http://i.imgur.com/MbULZq3.jpg)
![Image](http://i.imgur.com/DUKCa9A.jpg)
![Image](http://i.imgur.com/iKInjxW.jpg)
![Image](http://i.imgur.com/ZBujflz.jpg)

**Comment by tym32167** [comment]
:+1:

**Comment by malashin** [comment]
Я про бобкэт не особо хочу писать на карте. Он стоит вместе с другой тяжелой техникой.

**Comment by malashin** [comment]
Обновил список в первом посте.

**Comment by AlexVDem** [comment]
Предлагаю еще парочку мелких улучшений:
- передвинуть ремонтную площадку для вертолетов чуть подальше от ангара на 5-6 метров.
- передвинуть медицинский грузовик чуть подальше от ремонтной площадки
- передвинуть вертолетные посадочные площадки в сторону от столба...

**Comment by malashin** [comment]
@AlexVDem, какие площадки от какого столба?

**Comment by AlexVDem** [comment]
Рядом с посадочной площадкой вертушек на базе столб торчит. Мешает посадке.

**Comment by ToxaBes** [comment]
Таблицу разрешенного оружия/прицелов можно показывать прямо в снаряжении по кнопке, но нужен доброволец заполнить HTML-файл. Добавим кнопку "Таблица":
![1](https://cloud.githubusercontent.com/assets/3309152/12222887/97ace08a-b7d9-11e5-80e3-b890685b2a09.jpg)
и по нажатию будем показывать окно:
![2](https://cloud.githubusercontent.com/assets/3309152/12222888/9d8e6910-b7d9-11e5-9548-54e872a9d90c.jpg)

**Comment by malashin** [comment]
Таблица должна быть доступна без VAS интерфейса. Не все его используют. Можно вешать как действие рядом с Арсеналом. Вещать кнопку в список рядом с Снаряжение, Арсенал.

**Comment by malashin** [comment]
Пару строк из таблицы напиши, что бы я понял как она оформлена и сколько там чего. Остальное могу доделать.

**Comment by malashin** [comment]
> Рядом с посадочной площадкой вертушек на базе столб торчит. Мешает посадке.

@AlexVDem Столб этот часть самого острова. Такой столб есть еще восточнее, его на старте миссии взрываем артилерией. Этот столб очень близко к игрокам и так близко стрелять уже опасно. С ACE3 так еще и шрапнель разлетается соседние дома разносит.

Можно только сдвинуть площадку на юго-запад.

**Comment by malashin** [comment]
По поводу расширения площадки наградной техники.

Сейчас она появляется на случайном маркере из массива маркеров. Т.е. чтобы на траве не появлялись самолеты нужно, либо убрать все маркеры с травы, либо для самолетов сделать отдельные маркеры.

В принципе, перед аэропортом асфальтированная зона свободна и можно все маркера передвинуть.

Нужно ваше мнение.

**Comment by AlexVDem** [comment]
Я и предложил сдвинуть площадку, т.к. знаю что столб это часть ландшафта.

**Comment by Ded-PikhTo** [comment]
Таблички- это правильно и они хорошо выглядят на скринах. Можно сдавать рекламные места))
Смысл этих обозначений в том, чтобы не объяснять через чат что и где находится, а просто отослать или к инструктажу или к карте или обратить внимание на таблички. 
Не забываем проверять орфографию: "ОЧИСТКА".
Готов заполнять файл. Только скажите, как это сделать.

**Comment by ToxaBes** [comment]
Пока оставил вызов таблицы по кнопке в Снаряжении. Потом добавим как дейтсвие или попробуем добавить кнопку в Арсенал тоже.

@malashin  - как заполнять таблицу: [вот](https://github.com/TEHGAM/ADR/blob/dev/co47_ADR_Blue_Shark.Altis/scripts/VAS/table.html) html-файл.
Никакой таблицы на самом деле нет, все колонки отбиты пробелами т.к. вот [список](https://community.bistudio.com/wiki/HTML-Files) html тегов которые осилили БИСы.

Самое сложное тут вставить картинку оружия. Сначала идем [сюда](https://community.bistudio.com/wiki/Arma_3_CfgWeapons_Weapons) и находим оружие, например arifle_MXC_F. Затем подставляем имя оружия в кусок кода приведенные ниже и выполняем:
```sqf
_pic = getText (configFile >> 'CfgWeapons' >> 'arifle_MXC_F' >> 'picture');
copyToClipboard format ["%1", _pic];
player sideChat format ["%1", _pic];
```

В результате получаем url картинки вида 
```sqf
\A3\weapons_F\Rifles\MX\data\UI\gear_mx_cqc_X_CA.paa
```
Вставляем ее в html файл как
```html
<img src="\A3\weapons_F\Rifles\MX\data\UI\gear_mx_cqc_X_CA.paa">
```

**Comment by Ded-PikhTo** [comment]
А где выполнять код? В какой проге? Я с HTML сталкиваюсь только, когда картинки с жадных сайтов вытаскиваю))

**Comment by ToxaBes** [comment]
Код нужно выполнять в отладочной консоли, для этого нужно запустить миссию локально у себя либо быть админом Tehgam2. @malashin займется этим.

**Comment by Ded-PikhTo** [comment]
А может сделать не таблицу доступного вооружения, а такую схему: когда заходишь в снаряжение   выбранным классом, там имеется только доступное этому классу снаряга? И не нужно писать инструкции и памятки.

**Comment by AlexVDem** [comment]
Чисто теоретически это сделать можно, убрана же часть снаряжения, например форма OPFOR. Но сделать это намного более трудоёмкость, т.к. придётся рестрикшн писать отдельно для каждого класса игрока.

**Comment by malashin** [comment]
Нет смысла. Игрок видит всё, что можно одеть на сервере. Если что-то одеть нельзя ему говориться почему он не может это одеть и нужно сменить слот. Если чего-то не будет видно, то он будет думать, что этого на сервере вообще нет.

**Comment by malashin** [comment]
Забыл в коммите референс указать.
ef21082d2cf442b0d10f4744851eb904c98e79ee

Таблицу я не вижу в самой игре, просто пустое окно с заголовком из stringtable. Изменил charset, таблицу заполнил, но нужно пробелы проставить под столбцы.

**Comment by Noart537** [comment]
В оригинальной миссии при входе на сервер появляется окно с правилами. Там я так понял тоже html. Можно от туда код взять и оформить окошечко как сделал TohaBes в VAS.

**Comment by ToxaBes** [comment]
Добавил вызов в меню действий по скролу, пока без учета дистанции до арсенала. Изменил размер картинок оружия в таблице и попытался отбить колонки пробелами. Оказалось что внутренние моноширинные шрифты в Арме не моноширинны. Я перепробовал все что есть  - не получается сделать ровные колонки. 

Скриншот для наглядности:
![1](https://cloud.githubusercontent.com/assets/3309152/12270981/fa058782-b969-11e5-909e-6135628388ba.jpg)

**Comment by malashin** [comment]
У меня так и не отображается эта таблица. Место где она должна быть пустое. Заголовок и скрол справа есть. Т.е. всё работает, кроме html таблицы. Содержание таблицы значения не имеет. Проблема при её вызове скорее всего.

Проверял на 1920х1200, 1920х1080. На английском и русском языках интерфейса. Запускал только из редактора, pbo не собирал.

**Comment by ToxaBes** [comment]
Я не пробовал смотреть в редакторе, сразу собирал pbo-файл. Проверь пожалуйста в собранной миссии.

**Comment by ToxaBes** [comment]
Про моноширинность моноширинных шрифтов в Арме: http://feedback.arma3.com/print_bug_page.php?bug_id=20895

**Comment by malashin** [comment]
> вот как можно было накосячить с шириной букв и пробела....?

Вау! Главное, что это никогда не исправят уже.

В таблице можно отбивать столбцы невидимыми картинками. Тэг высоты и ширины картинки растягивает её или просто ставит в заданные рамки не изменяя соотношения сторон?

**Comment by AlexVDem** [comment]
Кстати, маленькое предложение. Может кому будет интересно заняться. Неплохо бы сделать какое то инфоокно (может в менеджменте групп), которое бы показывало роли игроков - кто у нас пилоты, кто снайперы, ПТ-шники и пр. На карте это не всегда очевидно.

**Comment by ToxaBes** [comment]
Теги будут растягивать картинку, т.е. вариант с невидимой картинкой может сработать если ставить высоту такую же как у картинки с оружием а ширину менять под наши нужды. А есть такая картинка в системной библиотеке картинок Армы?

**Comment by tym32167** [comment]
Всем привет. 
Только не переусердствуйте с окнами :)
И если вставить таблицу такой гемор, может, заскринить всю таблицу и вставить картинкой? Юзер же, Как я понял, всё равно не будет тыкать в неё мышкой или копипастить или ещё как интерактивничать?

**Comment by ToxaBes** [comment]
Роли игроков видны на карте при приближении к ним на определенное расстояние (1-2 км).

**Comment by ToxaBes** [comment]
Привет Тим, про картинку думали в самом начале но не стали делать т.к. сделать красивую и четкую таблицу картинкой сразу для всех разрешений будет еще сложнее чем то что мы сейчас делаем.

**Comment by tym32167** [comment]
@ToxaBes понял, печалька.

**Comment by Ded-PikhTo** [comment]
Про предложение AlexVDem.
Роли на карте видны, но смысл в том чтобы быстро посмотреть, кто каким классом играет. Было бы удобно класс игрока прописывать в "списке игроков", когда открываешь карту.

**Comment by Noart537** [comment]
Вы разделите оружие по классам. Пистолет/ПП, автомат, пулемет, снайперская винтовка, тяжелая сн.винтовка, ПТ. И иконку любого оружия из этой категории.

И классы в столбик, а оружие в стоку. Если классов будет больше. Медик, инженер, оператор БПЛА, можно сделать как - Остальные, у них по оружию не меняется ничего. Так и места меньше будет занимать.

**Comment by ToxaBes** [comment]
@AlexVDem, @Ded-PikhTo - классы игроков  давайте обсуждать [тут](https://github.com/TEHGAM/ADR/issues/415).

@Noart537  - нам сначала нужно научиться делать ровные колонки тем или иным способом. При классах в столбик получим горизонтальный скролл на некоторых разрешениях, я уже пробовал. К тому же проблему колонок он не пофиксит. Текущий вариант самый наглядный как по мне т.к. видно каждое оружие из арсенала.

**Comment by Noart537** [comment]
Еще как вариант
Класс
картинки

Снайпер
картинка название
картинка название
...
Пулеметчик
картинка название
картинка название
****

**Comment by ToxaBes** [comment]
@Noart537 - и получаем один длинный вертикальный скорлл, одну колонку и кучу неиспользуемого места. Идея с невидимой картинкой должна сработать. Главное найти ее в стандартных картинках армы, неважно какого размера.

**Comment by Noart537** [comment]
Можно создать нужных размеров и в миссию затолкать

**Comment by ToxaBes** [comment]
@Noart537 - размер столбцов не работает потому что в арме нет столбцов/таблиц.
Из всех HTML-тегов БИСы осилили: p, b, br, h1-h5, hr, img. И крутись как хочешь :)

**Comment by Noart537** [comment]
ссылку на форум, и тут уже красиво))

**Comment by ToxaBes** [comment]
Давай попробуем доделать таблицу. Осталось то невидимую картинку найти в самой арме или засунуть свою в миссию.

**Comment by malashin** [comment]
Картинка прозрачная есть. Но нужно попиксельно их подбирать. Растягиваются они, я проверял уже.

<img width="100" height="25" src="\A3\ui_f\data\igui\rsctitles\static\entitytransit\variant1\vr_entitytransit_00.paa">

На счет выравнивания пришол к одному упрощению. Сделать сначала + - + + и т.д. за ними уже указать иконку и название оружия. Тогда выравнять их будет значитьельно проще. Проблемы только с выравниванием первой строки под + + -. Сами + - я заменил на иконки в итоге.

Просто возни с этим ну очень много получается. И учитывая, что проверить сразу в редакторе нельзя, а приходится pbo делать это еще больше угнетает.

**Comment by ToxaBes** [comment]
Не давай по-человечески, сначала картинка оружия с названиями, затем плюсы/минусы. Напиши сюда картинки для плюса/минуса и я все сделаю.

**Comment by malashin** [comment]
Сейчас такие иконки, но мне они не нравятся. Я хочу заменить.
```sqf
<img width="25" height="25" src="\A3\ui_f\data\map\diary\icons\tasksucceeded_ca.paa">
<img width="25" height="25" src="\A3\ui_f\data\map\diary\icons\taskfailed_ca.paa">
```

Посмотри valign работает на картинки. Сейчас иконка оружия выше текста, т.к. прозрачная внизу.

**Comment by ToxaBes** [comment]
Спасибо, вечером займусь.

**Comment by ToxaBes** [comment]
Кое-что начало получаться, но это не быстрый процесс:
![1](https://cloud.githubusercontent.com/assets/3309152/12334110/39cee07a-bb09-11e5-9844-648aab235d7b.jpg)

**Comment by malashin** [comment]
Титаническая работа )

**Comment by Noart537** [comment]
:thumbsup:

**Comment by Ded-PikhTo** [comment]
Это так будет выглядеть окончательный вариант?
Может, поменять цвет кружочков? Белый не смотрится.

**Comment by AlexVDem** [comment]
Клёво, да... ;)

**Comment by ToxaBes** [comment]
@Ded-PikhTo - по виду/цвету иконок у нас @malashin и @Noart537. Моя задача сделать чтобы колонки были ровными. Если они затем найдут более подходящие иконки (или может ты найдешь что-нибудь из стандартных иконок армы) то заменить их дело 2х минут.

**Comment by AlexVDem** [comment]
В продолжение темы вчерашнего разговора в ТС - предлагаю в список предложений добавить скрипт, запрещающий открывать рампу Тару, Хурона или модуля (аналогично запрету стрельбы из БлэхкХоука).

**Comment by ToxaBes** [comment]
html-вариант не тянется корректно при разных разрешениях. Переписал "таблицу" на такой же контрол как в списке серверов. 
Из хорошего - теперь есть честные колонки которые правильно тянутся и выделенная строка подсвечивается.
Из плохого  - выравнивание текста/картинок внутри колонок можно задать только как единое для всех (слева/по центру). Также картинка всегда ставится вначале колонки какой бы текст там ни был. Получился вот такой вариант (1920х1080):
![1](https://cloud.githubusercontent.com/assets/3309152/12432606/51256dfe-bf0d-11e5-9b6b-72cd0c897e66.jpg)
осталось побороть размер шрифта, чтобы он динамически менялся под разрешение экрана. Пример под 1600х900:
![2](https://cloud.githubusercontent.com/assets/3309152/12432646/74604334-bf0d-11e5-9c7f-b91b35008ab5.jpg)

**Comment by malashin** [comment]
Через getResolution попробуй
https://community.bistudio.com/wiki/getResolution

По идее, по мимо разрешения, нужно еще и UI scale учитывать, он тоже в этой команде возвращается.

**Comment by ToxaBes** [comment]
Добавил фиксированную строку заголовка (не прокручивается) и динамический размер шрифта на основе высоты всего грида (этот метод использует редактор армы). Попробовал с разными разрешениями - более менее выглядит, колонки не плывут. @malashin - проверь пожалуйста.

**Comment by malashin** [comment]
@ToxaBes вот такая фигня вылезла при первом открытии таблицы.

![img](http://i.imgur.com/i360GuT.png)

От иконок ты отказался?

**Comment by ToxaBes** [comment]
Добавь пожалуйста в самое начала файла https://github.com/TEHGAM/ADR/blob/dev/co47_ADR_Blue_Shark.Altis/scripts/VAS/info.sqf#L5 
вот эту строку:
```sqf
disableSerialization;
```
т.е. получится
```sqf
disableSerialization;
_display = uiNamespace getVariable['VAS_Info_Dispaly', displayNull];
```
О иконок отказался - их нельзя выровнять по центру в колонках.

**Comment by malashin** [comment]
```sqf
disableSerialization;
```
Добавил, ошибки нет.

Я вот думаю "Командир Отделения" переименовать в "Командир". У меня он единственный заходит в соседний столбец.

**Comment by ToxaBes** [comment]
>Я вот думаю "Командир Отделения" переименовать в "Командир". У меня он единственный заходит в соседний столбец.

Странно, у меня на 1920x1080 и 1600x900 не заходит. Но ты прав, название слишком длинное, меняй на "Командир".

**Comment by malashin** [comment]
Он заходит у меня на 1920х1200. Аспект меняется и шрифты увеличиваются.

**Comment by malashin** [comment]
Скрипт с рампами вертолетов вынес в отдельную задачу. По этой всё закончили. Тестим и закрываем.
