### ISSUE TITLE
FOB миссии

### ISSUE THREAD

**Issue by malashin** [TEHGAM/ADR#414]
Ahoy World в версии 2.85C добавили новый тип миссий идущий параллельно с Основой и Допзаданиями.

Детально еще не разбирался. Но смысл в том, что на острове появляется мелкая база в которую даются задания отвозить припасы грузовиком, по пути встречаются засады. Если грузовик довезти, то дают наградную технику в этой мелкой базе.

http://www.ahoyworld.co.uk/topic/726-aw-invade-annex-changelog-and-download/

Нужно решить нужно оно нам или нет.

На мой взгляд фигня и примитивно очень. Просто появляется один отряд пехов между грузовиком и этой базой и атакует его.

Но сама идея отвезти припасы хорошая и можно построить на этом допки или задания основы.

**Comment by Noart537** [comment]
Как вариант, добавить задачу для выполнения основной миссии. Сначала зачищают точку, тем временем нужно увезти с базы появившиеся там грузовики или контейнеры на основную миссию в определенный триггер. Можно давать за это небольшую награду. В виде джипа с пулеметом и 1 птуром.

**Comment by Noart537** [comment]
Можно сделать как и они отдельную задачу, для пилотов. Увезти 15 контейнеров. За это дадут, верт с какой-нибудь текстуркой техгама например)

**Comment by ToxaBes** [comment]
Они таки сделали свои "спецоперации", только они однотипны, отличаются только содержимым которое надо доставить. В том виде как оно есть по-моему не очень интересно, но можно использовать как идею для основы. Например, у нас много кто добирается до основы на транспорте с оружием - мы можем спавнить им небольшие засады. Для вертолетчиков которые везут на основу - пару ПВО-шников по маршруту следования со взводом охраны.

**Comment by AlexVDem** [comment]
Можно сделать это на время, за 20 минут это не решил - миссия пропадает. + въезд на базу рандомно заминирован - надо расчистить проезд.

**Comment by ToxaBes** [comment]
В текущем виде FOB-миссии не нужны. Если есть предложения которые улучшат их и позволят использовать на основе - пишите [сюда](https://github.com/TEHGAM/ADR/issues/412).
