### ISSUE TITLE
Показывать класс игрока в разделе Игроки на карте

### ISSUE THREAD

**Issue by ToxaBes** [TEHGAM/ADR#415]
В списке игроков на карте после имени игрока вставить через дефис текущий класс игрока, например "ToxaBes - медик" либо если не позволяет ширина колонки - вставить новую строку под логотипом отряда игрока.

**Comment by AlexVDem** [comment]
Да. Это будет удобно для пилотов, к примеру если вылет на задание, у тебя сидит в вертушке 10 чел., и все снайперы. ;) Нужно медика подождать.

**Comment by ToxaBes** [comment]
Оказалось что в список игроков вставить свой текст невозможно, поэтому добавил прямо в HUD на экране (см. скриншот). @malashin или @Noart537 проверьте пожалуйста и если все ок - закройте тикет.
![2016-01-16_00001](https://cloud.githubusercontent.com/assets/3309152/12372288/ca2f5efc-bc61-11e5-8713-a9d9d0813b1b.jpg)

**Comment by AlexVDem** [comment]
Да, ок, это очень удобно. Правда доступно это будет только для тех юнитов, которые в технике сидят. Однако, если я везу тару с контейнером или машиной с юнитами я не буду видеть, кто в контейнере или машине. Да или просто кто на сервере есть кто - будет понятно только по карте.

**Comment by ToxaBes** [comment]
На карте класс игроков которые рядом - отображается. В раздел "Игроки" на карте ничего не добавить к сожалению. Поэтому вывел информацию в HUD техники.
