### ISSUE TITLE
S.W.A.T. говорил что вам нужен человек знакомый с HC

### ISSUE THREAD

**Issue by rlex** [TEHGAM/ADR#416]
...В ТСе просил отписаться.
Мол, были какие-то вопросы по headless client. В чем суть?

**Comment by tym32167** [comment]
Я не в курсах. 
Вызываю @vosur @Noart537 @ToxaBes @malashin

**Comment by ToxaBes** [comment]
https://github.com/TEHGAM/ADR/issues/397

**Comment by tym32167** [comment]
То бишь вопросов больше нет, я верно понял? :)

**Comment by rlex** [comment]
А, окей, припозднился. Тогда закрываю, наверное.

**Comment by ToxaBes** [comment]
Да, вопрос иссяк )

**Comment by tym32167** [comment]
@rlex Спасибо за инициативу и попытку помочь :)
