### ISSUE TITLE
Добавление реализма при атаке на обороняющегося противника.

### ISSUE THREAD

**Issue by AlexVDem** [TEHGAM/ADR#417]
Друзья, подумал тут, а не добавить ли в атаку немного динамики? В основном чтобы усложнить жизнь снайперам. ;) Хотя я и сам за снайпера частенько воюю. Но и всем остальным тоже, дабы добавить элемента разнообразия и ухода от обычной рутины. Поясняю что я имею ввиду. Сейчас как происходит? Приезжает народ на точку, располагается в 2-3 км. от точки, выносит из линксов, титанов или стационарок все, до чего может дотянуться, потом идет в город. ПТ-шники вообще красавцы, берут страйдер, в него полусотня ПП-шных ракет и шмалают как в тире, пока все живое не выкосят. Так в реале не воюют. Так вот, в связи с этим предложения:

- Добавить на карту 2-3 минометных расчета противника, окруженных барьером из мешков (в Арме есть такой модуль - полукруглый барьер) , + виртуального минометчика, который будет выпускать залп по нашим позициям пока игроки не уничтожат все минометные расчеты. Причем, залпы тем чаще, чем больше остается на карте минометных расчетов. Логика в этом простая: в реалии всегда основной огонь сосредотачивают на позициях стационарных орудий, гранатометчиках, пулеметчиках и снайперах. При этом частоту огня по позициям можно варьировать: AI должен условно выбирать рандомно какого то игрока, смотреть его класс и выпускать по нему залп. Если игрок не сидел на одном месте больше чем какое то время - то AI выбирает следующего игрока и так далее по кругу, пока в радиусе огня есть хоть один игрок. Если игрок более заметный (ПТ-шник, игрок в стационарной установке или игрок в Охотнике с пулеметом или иной технике), то залпы идут чаще, если менее заметен - медик, то реже, если снайпер - то реже всего. Чем более заметная цель, тем меньше время можно сидеть на точке без движения. Радиус огня - 3 км (примерный предел дальности линкса и стационарных орудий). Если можно сделать скриптово что этот сценарий будет запускаться только в том случае, если противники заметили игрока (или он стрелял в зоне поражения), то совсем здорово.
- Ограничить радиус поражения Титана: ПП-шных ракет - 600 м., ПТ-шных ракет - 900м., стационарных Титанов - 1.5 км., ПЗРК - без ограничений. Если ракета летит до этой точки - она самоподрывается или просто пропадает (типа упала). Не знаю можно ли это сделать скриптово, но думаю стоило бы.
- Усилить броню зениток, чтобы их можно было уничтожить только с 3-й ракеты.

Чтобы не переусердствовать со сложностью, можно сделать такую миссию - основу не каждый раз, а через 2 например. Т.е. 2 обычные, а третья - усложненная, "темно красная", к примеру. Ну и без обороны её реализовать, как вариант.

Чтобы слегка уравновесить баланс сил предлагаю дать Аламут гранотометчикам и командирам отделений. Командир по сути ничего не умеет сейчас делать, пусть у него хоть Аламут будет. Еще командиру можно дать возможность наводить авиацию с НУРС и ВПУ, о которой я как то писал: http://www.tehgam.com/showthread.php?t=1587 Такой скрипт у меня есть, он очень маленький, и не повлияет на производительность, зато придаст смысл существованию командиров отделений и полетов на легких ударных вертушках, типа вооруженных Хэллкетах, Касатках или Пауни.

Есть еще мысли насчет зенитной батареи, которая доп миссия. Сейчас этот скрипт работает не совсем реально, т.е. выносит вертушки если они поднялись на какую то высоту над ландшафтом (по моему 30 метров). Но это неправильно, ни одна ЗРК ПВО не может на такой высоте найти вертушку. Предлагаю всетаки повысить планку хотя бы до 50 метров, и сделать эту высоту плавающей, т.е. зависимой от уровня моря. Иначе говоря, если игрок летит над морем, то эта высота априори 50 метров, если над текущем ладшафтом высотой более 100 м., то высоту обнаружения понизить до 30м., если высота ландшафта - 150м., то высота обнаружения - 5 мтеров. Это будет более реалистичная картина, хоть и всеравно далекая от реальной жизни, но чуть ближе к ней.

**Comment by ToxaBes** [comment]
>Приезжает народ на точку, располагается в 2-3 км. от точки, выносит из линксов, титанов или стационарок все, до чего может дотянуться, потом идет в город.

И огребает в городе (заселение города ботами предложено в #412 )

>ПТ-шники вообще красавцы, берут страйдер, в него полусотня ПП-шных ракет и шмалают как в тире, пока все живое не выкосят. Так в реале не воюют.

ПТ-шники не мобильны (побегай с 3мя ракетами в рюкзаке). И при использовании страйдера они привязаны к нему. Очень часто все заканчивается тем что страйдер сожжен штурмовиком/ответкой бронетехники либо просто сломалось колесо... Так что тут более-менее баланс есть.

>Добавить на карту 2-3 минометных расчета противника, окруженных барьером из мешков

Которым прилетит от того же ПТ-шинка ПП-ракетой. 

>Ограничить радиус поражения Титана: ПП-шных ракет - 600 м., ПТ-шных ракет - 900м., 

Это РАКЕТЫ, они должны лететь дальше чем летят пули.

>Усилить броню зениток, чтобы их можно было уничтожить только с 3-й ракеты.

Не вижу смысла ставить броню зениток на один уровень с танками.

>Есть еще мысли насчет зенитной батареи, которая доп миссия. Сейчас этот скрипт работает не совсем реально... ни одна ЗРК ПВО не может на такой высоте найти вертушку. 

Посмотри внимательно на зенитку, у нее наверху будет небольшая "тарелка" системы спутникого наведения.

![зенитка](https://community.bistudio.com/wikidata/images/c/c6/Arma3_CfgVehicles_O_APC_Tracked_02_AA_F.jpg)

>Чтобы слегка уравновесить баланс сил предлагаю дать Аламут гранотометчикам и командирам отделений. Командир по сути ничего не умеет сейчас делать, пусть у него хоть Аламут будет. 

Про командира отделений потом будет отдельная тема. Ему не аламут нужен, а то что будет помогать управлять отделением. Например только у него будет ЛЦУ с термо-режимом (у остальных ЛЦУ без терморежима). Или еще что. 
Этот тикет закрываю, идеи нужно сначала покрутить в  http://www.tehgam.com/issue.php?issueid=31
