### ISSUE TITLE
Сделать вызов ящика с патронами для перевозки вертолетами

### ISSUE THREAD

**Issue by malashin** [TEHGAM/ADR#418]
Сделать в меню вызова модулей для вертолетов, вызов одного-двух ящиков с разными патронами. Ящик можно будет подцепить стропами и отвезти на передовую.

Ящик сбрасывается с парашютом если если он был сброшен с большой высоты.

**Comment by AlexVDem** [comment]
Это же уже реализовано, в меню вызова модулей. Просто добавить в ящик разных патрон, и все.

**Comment by Noart537** [comment]
Скрипт уже готов, сейчас тестирую, допиливаю.

**Comment by Noart537** [comment]
Не получается сделать проверку на стропы (прицеплен объект или нет). Получилось только активация парашюта после набора 300м.

**Comment by AlexVDem** [comment]
А может определять не по стропам, а по высоте, если высота ящика больше 10 м., то запустить проверку парашюта, если высота ящика за секунду уменьшается на 20 метров - раскрыть парашют?

**Comment by ToxaBes** [comment]
>Не получается сделать проверку на стропы (прицеплен объект или нет).

Вариант 1:
```sqf
if (count (ropes _heli) > 0) then {
    // ящик висит на стропах	
} else {
	// ящик отцеплен
};
```
Вариант 2:
```sqf
//_box - груз (объект)
_obj = getSlingLoad _heli;
if (_box == _obj) then {
    // ящик висит на стропах	
} else {
	// ящик отцеплен
};
```

**Comment by Noart537** [comment]
Тут видишь, мы вызываем ящик игроком. Скрипт запускается. Потом только мы садимся в вертолет, взлетаем, и подцепляем стропами. 
1 Вариант нужно прописывать в init самого вертолета тогда.
2 Вариант возможно подойдет, спасибо попробую.

**Comment by ToxaBes** [comment]
Можно еще попробовать
```sqf
if (!isNull (ropeAttachedTo _box)) then {
   // ящик все еще на стропах
};
```

**Comment by Noart537** [comment]
спс работает. waitUntil{!isNull (ropeAttachedTo Supply_Ammo)};

**Comment by AlexVDem** [comment]
А вот так можно дымовую гранату прицепить, чтобы был дым на месте сброса...

detach _crate;
		_crate setPos [position _crate select 0, position _crate select 1, 0];
		_smoke = _smokeType createVehicle [getPos _crate select 0, getPos _crate select 1,5];
			hint "UH-80: Supply dropped!";

**Comment by Noart537** [comment]
С оружием ящик делать будем? Для тех кто потерял? #381

**Comment by malashin** [comment]
> С оружием ящик делать будем?

Я против. Патроны нужны почти всем. Оружие единицам и очень редко. Везти ради одного человека ящик с тоннами оружия странно и толку мало в самой игровой механике. Если потерял, то есть где подобрать на задании (трупы союзников или противников). Можно попросить привезти с базы.

**Comment by Noart537** [comment]
Хорошо. С парашютами при сбросе на малой высоте, хочу сделать такой эффект https://youtu.be/OutDET_-YgA?t=4m27s

**Comment by Noart537** [comment]
Красиво выглядит анимация вращения, но с новым обновлением на стамину, ящики стали тяжелые и падают как каменные. Приходится парашют делать главным объектом, в этом случае при раскрытии парашюта, все это висит на месте пока полностью не раскроется парашют, только тогда спускаться начнет.

**Comment by malashin** [comment]
А с массой так и не получилось ничего сделать?
https://community.bistudio.com/wiki/setMass

Посмотри массу разных объектов и поставь нужную ящику.
https://community.bistudio.com/wiki/getMass

Например пехотинец игрок сколько весит с тяжелым обвесом. Его парашют должен выдерживать.

**Comment by Noart537** [comment]
да я пробовал. ставлю 99999 он падает быстро, и при падении отпрыгивает от земли и летит хз куда)) как попрыгун. ставлю 0.3 или 1 никакого эффекта на падение.

**Comment by Noart537** [comment]
буду еще пробовать. Возможно ящик другой подберу поменьше.

**Comment by malashin** [comment]
На крайняк можно еще velocity брать и рассчитывать более медленый, давать его ящику и парашюту.

**Comment by Noart537** [comment]
да в моде velocity используется.

**Comment by malashin** [comment]
У него там не совсем то. Он берет ускорение падающего ящика, и ставит это ускорение прикрепленному парашюту.

Если у нас ящик камнем падает, то мы должны изменить его ускорение тем самым снизить скорость падения.

**Comment by AlexVDem** [comment]
Друзья, а не могли бы вы парашют и дымовую гранату для вертолетных модулей прикрутить? Я пока не за компом, не могу посмотреть скрипты как это сделать для модулей, только вечером до них доберусь, но может кто уже знает готовое решение? Знаю что это возможно, т.к. это уже реализовано в Xeno Taru Pod

**Comment by Noart537** [comment]
Сделаем. Как с ящиком разберемся.

**Comment by ToxaBes** [comment]
С массой все просто: подберите объект который будет нормально опускаться на парашюте, например MRAP. А потом посмотрите его массу через getMass и используйте это значение. Подозреваю что адекватные значения для воздуха будут в пределах 1000-2500.

**Comment by AlexVDem** [comment]
Скрипт, который позволяет сбрасывать модули Тару с парашютом (и присоединять их к вертушке). Сам не пробовал, протестируем?

**Comment by Noart537** [comment]
У нас раньше стоял, после обновления со снайперами перестал работать. Из-за чего не разберался. На тот момент мы миссию откатывали из-за лагов. И не стали вводить этот скрипт. Там единственный минус, это если пассажиры сядут в модуль (присоединенный к вертушке) они не смогут осматриваться. Камера блокируется. 

Еще одна интересная вещь. Мы с Ice-ом проверяли фризы вертолета во время транспортирования пассажиров в модуле\машине. Я поставил вертолет тару, модуль с сидениями и модуль пассажирский (на "пустой" карте). У пассажиров все-равно вертолет лагает со стропами. Видимо здесь не оптимизирован сетевой трафик, либо зависит от пинга. Когда садишь бота пилотом, то лаги исчезают и все плавно.

**Comment by Noart537** [comment]
А скрипт потестируем. В выходные планиурю арму поставить, и смогу продолжить работу над этой веткой.

**Comment by AlexVDem** [comment]
Это другой скрипт, хотя я допускают что с ним может быть та же фигня. В конце концов если будет глючить можно отключить присоединение и использовать его только для парашюта.

**Comment by AlexVDem** [comment]
> А скрипт потестируем. В выходные планиурю арму поставить, и смогу продолжить работу над 

> этой веткой.

@Noart537 А не прицепить ли парашют и дымовую гранату на всю технику, и все объекты, которые может поднять вертушка? А не только на ящик с оружием? Активируется например если высота техники или объекта выше 100м., а раскрывается если отцеплен от вертушки. Если высота меньше 100м. то объект просто падает без парашюта.
Я потестил вот такой простой скрипт в консоли дебагера, со скамейкой Taru, работает неплохо, выглядит красиво. Наверное надо сделать как то, чтобы object был не конкретный, а то что прицеплено к вертушке и чтобы скрипт высоту понимал, когда парашют раскрыть. Это сложно сделать? У нас по моему в скрипте ящика с припасами что-то подобное реализовано?

`_smokeType1 =  "SmokeShellPurple";
object = ["Land_Pod_Heli_Transport_04_bench_F",position player,100] call para_drop;
para_drop = {
    private "_obj";
    (if (typeName (_this select 0) != "OBJECT") then [{_obj = createVehicle[_this select 0,[(_this select 1) select 0,(_this select 1) select 1,((_this select 1) select 2) + (_this select 2)],[],0,"NONE"]; _obj},{_this set [1,position (_this select 0)]; _obj = _this select 0; _obj}])
    attachTo [
        createVehicle ["B_parachute_02_F",[(_this select 1) select 0,(_this select 1) select 1,((_this select 1) select 2) + (_this select 2)],[],0,"CAN_COLLIDE"]
    ,(if (count _this > 3) then [{_this select 3},{[0,0,0]}])];
	    _obj;
			};
 _Signal1 = createVehicle [_smokeType1, position object, [], 0, 'NONE'];
 _Signal1 attachTo [object, [0, 0, -1]]; `

**Comment by Noart537** [comment]
Модули с парашютом. Проверил все работает. Позже соединю в одни файл через case или if
