### ISSUE TITLE
Предложение

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#419]
Давайте делать изменения в разных ветках. Закончив одно изменение, мы сможем его сразу залить в основную. И быстрее продвинуть на сервер. И закрыть ветку и тему. В данный момент ведется работа над несколькими проблемами, и такую сборку не хотелось бы выкладывать и объединять с основной.

Как вариант предлагаю оставить основную master ветку. Это как проверенный и стабильный вариант. Ветка dev - это последние изменения в миссии и которая уже тестируется на боевом сервере. Остальные ветки считать в разработке ( не законченные). Что скажете?

**Comment by tym32167** [comment]
Инфа по теме
http://habrahabr.ru/post/106912/
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

Мы юзаем это в наших проектах более полугода, полет нормальный.

**Comment by ToxaBes** [comment]
Так можно у себя локально сколько угодно веток делать, а на гитхабе держать только master и dev (как сейчас). Т.е. перед заливом в dev разработчик мерджит у себя локально и проверяет.

**Comment by ToxaBes** [comment]
Я на работе использую cherry-pick для перекидывания коммитов между ветками. Например, сделал ты коммит d54143e в dev ветку. Залил, проверил - все ок. Прошло какое-то время, появились новые коммиты в dev и master ветках. И теперь хочешь применить dev коммит в master ветку:
```php
// переключился на master ветку
git checkout master
// стянул все изменения и обновил индекс
git pull --rebase
// применил коммит из  dev ветки в текущую (master)
git cherry-pick d54143e
// отправил изменения на сервер
git push origin master
// переключился обратно на dev ветку
git checkout dev
```

**Comment by tym32167** [comment]
@ToxaBes так нам надо функционал выделять и вести в отдельной ветке, пока он не будет допилен и потом мерджить его в дев. Сделали что то стОящее, протестировали в отдельной ветке и если всё хорошо - смерджили в дев. Кидаться отдельными коммитами - это, по моему, упячка какая то. Мы это можем сделать во время какого то хотфикса или типа того, но не на постоянной основе. Локльно ветки, конечно, хранить можно, но что если я помочь кому с работой захочу или историю разработки какой то фичи поглядеть или ещё чего? :) В общем, может и не стоит раскручивать gitflow на полную, но ведение отдельных фич в отдельных ветках считаю более чем целесообразным.

**Comment by ToxaBes** [comment]
>так нам надо функционал выделять и вести в отдельной ветке, пока он не будет допилен и потом мерджить его в дев.

```php
git stash
git stash apply
```

И не надо заниматься 5ю задачами одновременно.

>Кидаться отдельными коммитами - это, по моему, упячка какая то.

Не надо коммитить построчно :) Один коммит - один логически завершенный кусок задачи (подзадача). В среднем одна задача это 1-3 коммита. Вызвать 3 раза cherry-pick вместо одного не проблема.

>Локльно ветки, конечно, хранить можно, но что если я помочь кому с работой захочу или историю разработки какой то фичи поглядеть или ещё чего? :)

И часто ты это делаешь с задачами на tehgam? :) 

Есть одно эмпирическое правило - чем больше веток, тем больше тимлиду разгребать в итоге когда сыграет человеческий фактор (разраб думал что переключил ветку и смерджил не то и тд).

**Comment by Noart537** [comment]
Например ситуация была, я закончил свою задачу, проверил и хочу ее смержить с master веткой. Но т.к. у нас висят другие не завершенные задачи, я этого сделать не могу т.к. не знаю на какой стадии у других разрабов код в других коммитах. Можно ли их уже использовать или они залиты для тестирования. Получается мержить я могу только все. А отдельно свой коммит не смогу. 

Поэтому я  и обратился к вам с просьбой на каждую задачу использовать отдельную ветку. Закочили. Проверили. Залили в Dev. Раз в неделю собираю Dev (если были изменения). Заливаю на сервер игровой. Проверяем массово, если все отлично  закрываем задачу и ветку.

**Comment by ToxaBes** [comment]
Ок, только у тебя в итоге при проверке в dev ветке каждая смердженная ветка будет идти одним отдельным коммитом. И если вдруг тебе нужно будет в master перекинуть не все что в dev находится - ты все равно будешь делать это покоммитно.

Ладно, я не буду спорить - каждый по своему видит workflow. Если считаешь что будет удобнее с ветками - ок, буду использовать их. Напиши правила именования веток чтобы тебе было проще понять какая ветка к какой задаче относится.

**Comment by tym32167** [comment]
>В среднем одна задача это 1-3 коммита.

Это не так. По крайней мере, у нас на работе. У нас любое изменение, более-менее законченное - это коммит. Наши прогеры приучены коммитить часто. В среднем задача получается на несколько десятков коммитов. И это хорошо. 

>Вызвать 3 раза cherry-pick вместо одного не проблема.

Не проблема, пока задача одна. Это проблема, когда задачи больше одной.

>И часто ты это делаешь с задачами на tehgam? :)

Коммиты не делаю, но часто смотрю код и изменения. 

>чем больше веток, тем больше тимлиду разгребать

После мерджа в дев ветки надо удалять. Вот и всё. То есть все активные ветки - это задачи, над которыми сейчас работают. Как тимлид пишу, у меня нет описанной тобой проблемы. 

>  И если вдруг тебе нужно будет в master перекинуть не все что в dev находится - ты все равно будешь делать это покоммитно.

Это редкая операция и именно для таких случаев нужен черри пик. Больше ни для каких.

> Ладно, я не буду спорить - каждый по своему видит workflow

Тоха, я описываю, как это работает прямо сейчас у нас. Мы пробовали всякое, но вот такой подход сейчас нам очень удобен. Конечно, мы не слепо делали по книжке и наш процесс слегка отличается от gitflow, но общая суть та же. 

>Напиши правила именования веток

У нас вот так:

![image](https://cloud.githubusercontent.com/assets/610799/12505140/0d1d6d28-c106-11e5-9af1-177662694979.png)

**Comment by malashin** [comment]
В ace3 ветки называют по названию фичи обычно. Некоторые с номерами таска. На мой взгляд хороший вариант. Плюс на один такс может быть несколько веток.

![img](http://i.imgur.com/E3Tm2rd.png)

Таск или баг это нам абсолютно не важно.

**Comment by ToxaBes** [comment]
>Это не так. По крайней мере, у нас на работе. У нас любое изменение, более-менее законченное - это коммит. Наши прогеры приучены коммитить часто. 

У нас с тобой просто по разному организован процесс разработки ) Мои кодеры приучены коммитить вдумчиво. Т.е. в dev попадает только тот код в котором они уверены и хотят отдать на финальную проверку. Все "более-менее законченное" остается локально у разработчика пока не будет закончено.

>Мы пробовали всякое, но вот такой подход сейчас нам очень удобен.

Так я и не спорю что этот подход отлично работает на твоей работе. А подход без веток очень удобен на моей работе. Так что тут все субъективно. 

По названиям веток - предлагаю использовать #номертикета_краткоеназвание. Визуально можно быстро находить то что надо + сразу будет удобная сортировка в списке веток на гитхабе.

**Comment by tym32167** [comment]
>У нас с тобой просто по разному организован процесс разработки

это понятно :)

> Мои кодеры приучены коммитить вдумчиво

аналогично, просто твои кодеры думают при коммите о бОльшей задаче, чем мои. Мои коммитом могут решить какую то мелкую вещь и зафиксировать её. Это даже может быть просто перенос функции или изменение с рефакотрингом теста или что то типа того.  

>Т.е. в dev попадает только тот код в котором они уверены и хотят отдать на финальную проверку.

У нас также. У нас, когда кодер заканчивает работу и сдаёт в тест, он не мерджит ничего никуда. Тестер разворачивает его ветку на стенде и проверяет. Только после проверки, если всё хорошо, тимлид или кодер могут изменения смерджить в дев. И после этого тикет ещё раз проверяется на работоспособность уже в дев ветке. То есть у нас  в деве всегда только проверенные задачи.

>По названиям веток - предлагаю использовать #номертикета_краткое-название

Плюсую.

**Comment by ToxaBes** [comment]
Перешли на ветки, вопрос можно закрывать.
