### ISSUE TITLE
Баг системы наказаний, при стрельбе из техники.

### ISSUE THREAD

**Issue by AlexVDem** [TEHGAM/ADR#421]
При наказании игрока, убившего другого игрока находясь в технике, кик получает водитель, а не стрелок.
Известный и давний баг. Особенно неприятен тем, что ценная вертушка вроде каймана падает без пилота, в ней нет возможности взять управление. Да и пилот не виноват в том, что его стрелок убил своего. Иногда стрелок убивает своего не в группе, се ля ви, кто там свой-чужой из вертушки разглядеть нереально. ;) Тоже относится к другой технике, танки, бтр и пр.
Необходим скрипт, который будет при наказании учитывать то, кто был стрелком на момент выстрела.

**Comment by ToxaBes** [comment]
Проблема в том что мы используем ["Killed" event] (https://github.com/TEHGAM/ADR/blob/dev/co47_ADR_Blue_Shark.Altis/scripts/%3DBTC%3D_TK_punishment/%3DBTC%3D_tk_init.sqf#L115)

У БИСов в этом событии есть баг который они обозвали фичей: [Be careful when the killer has been a vehicle. For most cases the reference of the vehicle is the same as the effectiveCommander, but not always.](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#Killed)

Техника может задавить, расстрелять из основного или вспомогательного орудий. Это 3 разных игрока. Возможно кто-нибудь видел какой-нибудь скрипт который мог отлавливать это?

**Comment by malashin** [comment]
Я в наш скрипт добавил сохранение тимкилов в лог сервера. Т.е. всегда в лог записывается кто кого убил. Плюс если в технике убийца сидел, то записываются все кто сидит в технике на позиции с которой можно убить.

```sqf
14:00:37 "//========================================"
14:00:37 "TEAMKILL: 'CAPMAT[76561198005686396]' killed 'Vlad[76561198029555435]'"
14:00:37 "TEAMKILL: 'B_APC_Wheeled_01_cannon_F' driver 'CAPMAT[76561198005686396]'"
14:00:37 "TEAMKILL: 'B_APC_Wheeled_01_cannon_F' gunner 'Smokemon[76561198018161146]'"
14:00:37 "//========================================"

15:26:53 "//========================================"
15:26:53 "TEAMKILL: 'Stenka[76561198151578998]' killed 'Buffmaster[76561198004209204]'"
15:26:53 "TEAMKILL: 'I_MRAP_03_F' driver 'Stenka[76561198151578998]'"
15:26:53 "TEAMKILL: 'I_MRAP_03_F' commander 'Madrahim[76561197983485890]'"
15:26:53 "//========================================"

15:40:47 "//========================================"
15:40:47 "TEAMKILL: 'keiZ[76561198057709361]' killed 'Dima[76561198273688791]'"
15:40:47 "TEAMKILL: 'B_MRAP_01_hmg_F' gunner 'keiZ[76561198057709361]'"
15:40:47 "//========================================"

17:21:26 "//========================================"
17:21:26 "TEAMKILL: 'DeD PikhTo =rus=[76561197994763606]' killed 'Fatherst[76561198156891202]'"
17:21:26 "TEAMKILL: 'B_Heli_Transport_03_F' driver 'DeD PikhTo =rus=[76561197994763606]'"
17:21:26 "TEAMKILL: 'B_Heli_Transport_03_F' Turret 'Astarses[76561198032705838]'"
17:21:26 "//========================================"
```

Это может помочь админам в спорах на счет баннов игроков и их отмазок. Но автоматом "Killed" никак не поможет.

В принципе можно это реализовать через "HandleDamage", но это будет очень навороченный скрипт и в любом случае не будет работать на 100%.

Псевдокод:
```
Если HandleDamage вывел 1 (игрок умер), то {
    Взять источник повреждения (техника) и найти всех игроков в ней
    Взять тип патронов которыми был убит игрок и сопоставить с вооружением игроков в технике
    Если возможный убийца только один, то наказать его, если несколько, то не наказывать.
}
```
Несколько возможных убийц может быть в случае если они сидят пассажирами и могут стрелять. У нескольких из них может быть одинаковое оружие в руках.

**Comment by ToxaBes** [comment]
Да, проблема в том что арма не возвращает конкретного убийцу. Можно попробовать использовать событие [MPKilled](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#MPKilled) вместо Killed.

**Comment by ToxaBes** [comment]
Похоже что это нельзя пофиксить by design. В большинстве событий нет  типа боеприпасов или орудия, в тех что есть вызываются не всегда. Наиболее подходящее событие - HitPart, но в нем не указано какой урон был нанесен в результате его воздействия, только номинальные характеристики боеприпаса. Событие происходит до подсчета урона т.е. нельзя сказать какой выстрел был смертельным.
