### ISSUE TITLE
Ошибка при возрождении пилота

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#422]
Наблюдается ошибка скрипта при возрождении пилотом. 
![2016-01-23_00002](https://cloud.githubusercontent.com/assets/8770445/12545739/bac3a372-c366-11e5-9fb7-d3b25d312e43.jpg)

**Comment by Noart537** [comment]
Вижу ошибку уже поправили, с оптикой. Проверю сегодня ошибку с возрождением, отпишусь

**Comment by malashin** [comment]
Оптику я правил. По пилотам не ясно в чем косяк.

**Comment by Noart537** [comment]
Обновил
![2016-01-25_00002](https://cloud.githubusercontent.com/assets/8770445/12546561/7d83c78e-c36c-11e5-940f-99aa4a79f8b8.jpg)

**Comment by Noart537** [comment]
Это не влияет на игровой процесс, но если будет время, гляньте.

**Comment by malashin** [comment]
Проверь сейчас.

**Comment by malashin** [comment]
@Noart537 посмотри, что с этой ошибкой. Та, что из fatigue прошла, а с пилотам у меня не было её.

**Comment by Noart537** [comment]
Как сервер будет доступен, проверю, отпишусь.

**Comment by AlexVDem** [comment]
Кстати, бывает так, что пилот респаунится не у ангара, а рядом с площадкой где респаунится пехота.
Редко, но раза 3 такое было.

**Comment by malashin** [comment]
Не помогло всё таки. Двух этих переменных как-бы нет. Хотя они есть и все остальные работают.

**Comment by ToxaBes** [comment]
PARAMS_Fatigue я пофиксил в #430 .

Для PARAMS_PilotRespawn замени 
```sqf
if (PARAMS_PilotRespawn == 0) exitWith {};
```
на
```sqf
if (!isNil "PARAMS_PilotRespawn" && {PARAMS_PilotRespawn == 0}) exitWith {};
```

**Comment by malashin** [comment]
Я понять не могу почему он говорит, что переменных этих нет. Параметры эти указаны и все остальные параметры работают корректно.

**Comment by ToxaBes** [comment]
В desciption.ext я вижу class PilotRespawn, но где он объявлен как PARAMS_PilotRespawn?

**Comment by malashin** [comment]
Вот пример работающего параметра. Нигде кроме discription.ext и этой строки его нет.

https://github.com/TEHGAM/ADR/blob/dev/co47_ADR_Blue_Shark.Altis/description.ext#L198
https://github.com/TEHGAM/ADR/blob/dev/co47_ADR_Blue_Shark.Altis/functions/fn_AOenemy.sqf#L165

**Comment by malashin** [comment]
А здесь написано, что они в массиве должны быть и доставать их надо через
```sqf
paramsArray select 0;
```

https://community.bistudio.com/wiki/Arma_3_Mission_Parameters

Как тогда у нас это работает с другими параметрами?

**Comment by malashin** [comment]
Вот оно как
https://github.com/TEHGAM/ADR/blob/dev/co47_ADR_Blue_Shark.Altis/initServer.sqf#L33

**Comment by ToxaBes** [comment]
https://community.bistudio.com/wiki/missionConfigFile :
Since introduction of the Eden Editor, scenario attributes can be configured in the editor itself, not only in the external Description.ext file. To access desired value independently on where it's stored, use the following commands instead:
* getMissionConfigValue
* getMissionConfig

Т.е. нужно либо инициализировать каждый параметр по имени, а не в цикле по всем, либо попробовать использовать в [этой](https://github.com/TEHGAM/ADR/blob/dev/co47_ADR_Blue_Shark.Altis/initServer.sqf#L37) строке  вот такой вариант:
```sqf
configName ((missionConfigFile/"Params") select _i,
```

**Comment by Noart537** [comment]
`if (params_PilotRespawn == 0) exitWith {sleep 0.1};`
если так поставить, ошибки нет.

**Comment by ToxaBes** [comment]
Странно, в SQF регистр названия переменных имеет значение. Если работает - закрывай тикет.
