### ISSUE TITLE
Мины после спецопераций не удаляются

### ISSUE THREAD

**Issue by ToxaBes** [TEHGAM/ADR#424]
После выполнения спецоперации остается кольцо мин-растяжек которое не удаляется.

**Comment by ToxaBes** [comment]
Возможно это связано с тем что скрипт очистки мин и стационарных орудий переписан на очистку каждый 6 часов в #404 . Нужно написать свою очистку в тех спецоперациях где используются мины.

**Comment by malashin** [comment]
Сейчас другой срипт очистки работает. Все найстроки в начале файла видно.
https://github.com/TEHGAM/ADR/blob/dev/co47_ADR_Blue_Shark.Altis/scripts/clean.sqf

У тебя в спецоперациях ошибки есть при создании. В некоторых с минами, в заложниках что-то еще было. Запусти Арму с -showScriptErrors и в редакторе позапускай свои миссии. Сразу видно будет где ошибка. В логах более подробно уже.

**Comment by ToxaBes** [comment]
Ок, посмотрю.

**Comment by ToxaBes** [comment]
> У тебя в спецоперациях ошибки есть при создании.

Нашел 2 ошибки и исправил. По минам изменил механизм удаления - работает, смерджил ветку в dev, будем смотреть на живом сервере.
