### ISSUE TITLE
Гауптвахта

### ISSUE THREAD

**Issue by ToxaBes** [TEHGAM/ADR#425]
Предлагаю сделать гауптвату на сервере для наказания за тимкилы. Примерный вид:
http://www.armaholic.com/page.php?id=18524

Особенности:

* нарушитель умирает и попадает в клетку только если пострадавший нажал на кнопку "Наказать". 
* клетка находится рядом с основным респом и вертолетной площадкой.
* время нахождения в клетке 5 мин.
* если наказывает несколько пострадавших - время наказания складываются.
* это наказание не работатет для пилотов (неадекватных пилотов кикает админ).
* попытки перезайти в игру на таймер не влияют.
* рядом с клеткой нужна табличка "Гауптвахта" (за клеткой можно поставить "Животных не кормить!").
* (опционально) для арестованного раз в минуту выводить окошко с текстом, "Я больше не буду убивать своих" и кнопкой "Ок". Таймер не отсчитывает время пока игрок не нажмет на кнопку.

**Comment by ToxaBes** [comment]
Нужно выбрать место где будет находится клетка.

**Comment by AlexVDem** [comment]
Можно поставить за посадочной площадкой для вертушек, метрах в ста. Там как раз места свободного куча.

**Comment by AlexVDem** [comment]
Кстати, как вам такая идея:
- если статус игорока - пилот
- если за последние 10 минут он погиб 3 раза,
  тогда делаем вывод, что летать он не умеет, или воюет не пилотом на земле...

тогда: 
- сажаем его на "губу" за порчу вертушек или невыполнение обязанностей пилота
- если игрок зашёл другой ролью - с "губы" выпускается
- если зашёл опять с ролью пилота - но через час (потренировался в редакторе) - тоже выпускаем.

Основная цель автоматизировать работу админа по указанию "сменить слот" и снижению количества неадекватных пилотов или пилотов не играющих за свою роль.

**Comment by Noart537** [comment]
Может лучше сделать просто предупреждение? Если продолжает падать какое-то кол-во раз, то заносить его id  в массив, который будет проверяться при залезании в вертолет. Если его id будет, то его будет выкидывать из ветра. После рестарта обнуляется. Злостных нарушителей можно таким же образом заносить в черный список id. который проверяется при залезании в технику. Но это дополнительная работа администраторам.

**Comment by ToxaBes** [comment]
Пилотов на гауптвахте не будет т.к:
* хорошие пилоты тоже разбиваются
* если пилот будет сидеть на гауптвахте - слот пилота будет занят впустую

Поэтому предлагаю обсуждение о том что и как делать с пилотами вынести в отдельный тикет.
Объедините оба ваших предложения: если пилот разбил вертолет х раз в течении у минут то при заходе в вертолет на место пилота/второго пилота его будет высаживать с надписью "Надо бы вам по-потренироваться в редакторе...". Через z часов его ограничение исчезает.

**Comment by AlexVDem** [comment]
Не, это предложение тоже не очень, т.к. игрок пилотом побежит и сядет в БТР к примеру и поедет на задание. Была мысль принудить его добровольно сменить слот, т.к. сидеть на губе никто не станет, если можно зайти стрелком и поехать на миссию.

**Comment by ToxaBes** [comment]
@Noart537 , @AlexVDem  - дальнейшее обсуждение по пилотам [тут](https://github.com/TEHGAM/ADR/issues/431).

**Comment by ToxaBes** [comment]
Предлагаю использовать вот это место для гауптвахты
![1](https://cloud.githubusercontent.com/assets/3309152/12757733/4913f706-c9ea-11e5-912c-234934fb3691.jpg)
![2](https://cloud.githubusercontent.com/assets/3309152/12757737/4e8147fc-c9ea-11e5-8937-8cea13931577.jpg)

Плюсы:
* близко к респу и вертолетке
* никому не мешает
* все видно как изнутри так и снаружи
* находится в безопасной зоне где запрещена стрельба (арестованные сидят без оружия)

Также после экспериментов понял что крыша не нужна, т.к. каждые 5 сек идет проверка на положение арестанта, если дальше 10м от центра гауптвахты - телепорт в центр. В машину тоже не запрыгнуть.

**Comment by AlexVDem** [comment]
Может собак ещё по периметру запустим? ;) Для антуража.

**Comment by ToxaBes** [comment]
У нас Гауптвахта а не зона.

**Comment by Noart537** [comment]
Котят?)

**Comment by ToxaBes** [comment]
Обойдутся, это Гауптвахта а не ми-ми-ми зона )

**Comment by Noart537** [comment]
5 мин наверно много, может по 1 мин за одну жалобу?

**Comment by ToxaBes** [comment]
5 минут это минимальное наказание. 1 мин есть сейчас и по факту не является наказанием. Ради одной минуты нет смысла все это затевать.

**Comment by RK3QRZ** [comment]
1. Пять минут это много.
2. Наказание не должно суммироваться, у нас было полно случаев когда с вертолетов, самолетов и танков случайно убивали своих. Кто будет сидеть 15-20 минут и тыкать дурацкую кнопку Я ТУТ. Проще пойти на другой сервер чем терять время тыкая кнопку.
3.Табличка про животных это перебор, давайте уважительно относиться к игрокам. Никто не застрахован от случайного тимкила.
4. Про наказание пилотов совсем не понятно. 
"это наказание не работатет для пилотов" Что это значит? Если два чувака полетели на блэкфуте, стрелок убил союзника, наказание будет? Если в гостхоке например пилот пересел за пулемет и расстрелял своих, будет наказание?

**Comment by malashin** [comment]
Место подходящее.

Без крыши тимкиллеров могут троллить пилоты вертолетов.

1 минута это очень мало.

**Comment by tym32167** [comment]
Скопирну себя с форума
>  складывать время не стоит, просто 2-3 минуты тюрьмы после последнего наказания. Таблички, оскорбляющие игроков вообще недопустимы. Окошко с кнопкой для арестованного тоже лишнее. Мы же хотим наказанием просто на время отлучить игрока от игрового процесса, но издеваться над ним надписями, табличками или долгим сроком наказания не стоит, так мы рискуем потерять адекватных игроков.

**Comment by malashin** [comment]
На счет суммирования. Вы на него странно смотрите.

Человека запирают на стандартное время, допусти, 3 минуты. За все остальные жалобы к этому времени добавляется меньшая величина, допустим, по 1 минуте. Множитель в данной ситуации не подходит.

**Comment by AlexVDem** [comment]
Мне тоже кажется, что за рецидив надо наказывать строже.
Первый случай -5 минут (обязательно сказать при наказании, сколько времени надо отсидеть), второй случай - 5 минут + 3 минуты, к примеру, третий случай, 5 + 3 + 3. Потом можно и банить.

**Comment by tym32167** [comment]
Я не пойму, зачем нам нужно это суммирование? Мы теперь разделяем степени вины тимкиллера? Теперь расстрелять двоих сокомандников страшнее, чем подорвать союзный наградной танк с одним водителем? Как это повлияет на достижение нашей цели наказаниями - уменьшения тимкиллеров? Зачем нам вносить в скрипт наказания такие сложности? 
К тому же, я думаю, максимальное время наказания 2 минуты. Дольше просто никто сидеть не будет, просто уйдет с сервера. У нас вообще то куча конкурентов, потому святой поход против тимкиллеров может легко превратиться в потерю игроков. У нас основная цель сервера какая? Привлечение новых игроков (в первую очередь новичков), а новички неизбежно будут убивать своих, и их обязательно будут наказывать. Как продолжительная отсидка со всплывашками с кнопкой и оскорбляющими плакатами пояснят такому игроку, что убивать своих-плохо, но при этом сохранят для него интерес играть на нашем сервере? Давайте не забывать о целях сервера и о мотивах внедрения системы наказаний. С моей точки зрения, у системы наказаний несколько целей: 
1. При наличии явных нарушителей дать нормально играть другим игрокам. 
2. Если нарушитель не паталогический убивалец, то дать ему время на осознание вины, при этом не отпугнув его от игры на сервере. 
3. При попадании за решетку по случайности, не отпугнуть наказанного игрока от дальнейшей игры на сервере. 
Возможно, это не полный список. Но его надо учитывать при проектировании системы наказаний.

**Comment by ToxaBes** [comment]
Ох, постараюсь ответить всем и сразу:

@RK3QRZ
> Пять минут это много.

Меньше 4-5 минут смысла не имеет. Сейчас у нас в виде наказания 2 минуты черного экрана (что психологически дольше и тяжелее). Вчера меня "наказали", так вот - 2 мин это вообще ни о чем.

> Наказание не должно суммироваться. Кто будет сидеть 15-20 минут и тыкать дурацкую кнопку Я ТУТ.

Ок, забыли про суммирование времени и кнопку.

Кстати, у нас сейчас вроде  в https://github.com/TEHGAM/ADR/blob/dev/co47_ADR_Red_Lynx.Altis/scripts/=BTC=_TK_punishment/=BTC=_tk_init.sqf есть BTC_tk_last_warning = 10
Т.е. после 10 наказаний человек изгоняется с сервера до следующей перезагрузки с надписью "ВАС НАКАЗАЛИ ЗА УБИЙСТВО СВОИХ \ ВАМ ЗДЕСЬ БОЛЬШЕ НЕ РАДЫ". Не знаю работает ли это или отключено.

> Про наказание пилотов совсем не понятно. 

Я имел ввиду делать исключение для пилотов занимающих место основного пилота в вертолетах перевозящих игроков. Но чем больше я над этим думаю тем больше склоняюсь к мысли что исключений быть не должно ни для кого.

@malashin
>Без крыши тимкиллеров могут троллить пилоты вертолетов.

Согласен, добавим крышу.

@tym32167

> складывать время не стоит, просто 2-3 минуты тюрьмы после последнего наказания.

2 минуты есть сейчас, и этого мало. 5 минут оптимально. Я тестил :) Но можно немного поторговаться и сойтись на 4х минутах :)

> Таблички, оскорбляющие игроков вообще недопустимы. 

Согласен, не все игроки обладают самоиронией. Оставим одну табличку с обозначением места "Гауптвахта".

> Окошко с кнопкой для арестованного тоже лишнее. 

Окошко и кнопку не будем делать.

> К тому же, я думаю, максимальное время наказания 2 минуты. 

Так, давай убедимся что мы говорим об одном и том же. 2 минуты перед черным экраном тянутся гораздо медленнее чем 4-5 минут в гауптвахте, из которой все видно. Я в первый раз когда тестил эту клетку провел там ~8 минут - пошел проверил нет ли щелей по кругу, посмотрел что откуда видно и тд. Сделал пару скринов для себя и тд. Не забывай что это не черный экран.

> У нас вообще то куча конкурентов, потому святой поход против тимкиллеров может легко превратиться в потерю игроков. 

Лично я считаю что конкурентов у Вас нет. Покажи мне сервера-конкуренты с русскоговорящей аудиторией, интересными миссиями и отсутствием обязательных модов. Возможно есть похожие сервера, но я их не видел. Я считаю что уйдут только неадекваты - а скинуть их на сервера-конкуренты вообще милое дело.

> У нас основная цель сервера какая? Привлечение новых игроков (в первую очередь новичков).

Привлечение новых игроков (в первую очередь новичков) **куда** или **для чего**? Ведь цель это то ради чего привлекаются новые игроки. Например, ради роста игроков на других серверах TEHGAM. Вот только сервера (режимы игры) настолько разные на серверах что этот метод по-моему не работает (не вижу я заполненных остальных серверов кроме второго). Почему вы все относитесь ко второму серверу как к проходному этапу для игроков, мол обживется новичек и пойдет на другие сервера? Это давно уже самодостаточный сервер со своими сообществом игроков которые не собираются переходить на другие сервера TEHGAM т.к. им нравится именно этот режим игры. 

> новички неизбежно будут убивать своих, и их обязательно будут наказывать. 

Это нормально. И именно так многие поймут что не надо стрелять по своим. И будут осторожнее. Вы же кикаете игроков и не боитесь что они не придут больше. И они приходят, и с банами пытаются зайти, и на форуме пишут просьбы о разбане.

> Как продолжительная отсидка со всплывашками с кнопкой и оскорбляющими плакатами пояснят такому игроку, что убивать своих-плохо, но при этом сохранят для него интерес играть на нашем сервере? 

Про кнопку/плакаты забыли. Отсидка в уютной, проветриваемой клетке лучше черного экрана объяснит что: хочешь играть, а не терять время в клетке - не стреляй по своим. 
Условно, на втором сервере есть 4 вида игроков:
* адекватный новичик: поймет свою ошибку, расскажет потом друзьям "прикиньте я на одном серврер на губе отсидел, за дело".
* неадекватный новичек: ничего не поймет, будет зол что его лишили треша и угара, помня о своей исключительности и незаменимости (да и найтсталкера у них нет!) - уйдет с сервера.
* адекватный не-новичок: скорее всего вообще не попадет на губу т.к. извинится, но если и попадет то уж точно не уйдет с сервера.
* неадекватный не-новичок: давно попался на глаза Свату или Рембо и сидит в перманентном бане.

Итого, корректирую предложение исходя из отзывов администраторов:

* никаких таблицек/плакатов кроме таблички с обозначением места.
* никаких кнопок всплывающих каждую минуту
* никаких суммирований времени
* никаких исключений для пилотов
* время отсидки 4-5 минут (сейчас 2 минуты)
* в углу экрана показывать таймер сколько осталось сидеть (мин:сек:мс от Х мин до 00:00:00).
* крыша обязательна

**Comment by malashin** [comment]
У суммирования есть плюс.

Если игрок не виноват, то отсидит он мало времени. Игрок может бросится под колеса специально и наказать вас.

Если игрок намеренно убивает и игрокам это не нравится, то жаловаться на него будут больше людей. Он отсидит нормальный срок.

3 мин + 1 мин за дополнительную жалобу, нормальный вариант.

За тех кто не намеренно убил, жаловаться много игроков не будут.

**Comment by AlexVDem** [comment]
Согласен с Тохой почти по всем пунктам. Единственное, для пилотов - если уж делать наказание, то для всех тогда, кто был в экипаже, а не только для пилота. Если не можем отдельно стрелка наказать.

**Comment by tym32167** [comment]
> никаких таблицек/плакатов кроме таблички с обозначением места.
никаких кнопок всплывающих каждую минуту
никаких суммирований времени
никаких исключений для пилотов
время отсидки 4-5 минут (сейчас 2 минуты)
в углу экрана показывать таймер сколько осталось сидеть (мин:сек:мс от Х мин до 00:00:00).
крыша обязательна

Согласен почти со всем, кроме времени отсидки. 

> 2 минуты есть сейчас, и этого мало. 5 минут оптимально. Я тестил 

Тебе было интересно, ты же разработчик. Надо исходить от игрока. Он эти 2 минуты играть может? Нет. Значит, есть вероятность, что игроку может быть и все равно, черный экран или решетка. Предлагаю начать с 2 минут, поглядеть на результат, и если этого будет явно недостаточно, то тогда увеличивать.

> Лично я считаю что конкурентов у Вас нет.

Уже не у **Вас**, а у **НАС ** :) Не смотря на то, что я играю нечасто, и 99.999% времени играю на втором сервере, я уже наслышан о конкурентах, будь то отстрел или уральский сервер или какой либо другой. Конкурентов полно. И кто говорил, что наши игроки могут играть только на русскоязычных серверах. Напомню нашу статистику http://www.tehgam.com/attachment.php?attachmentid=2430&d=1452087310

> Привлечение новых игроков (в первую очередь новичков) куда или для чего? 

К проекту TEHGAM. Я тут оказался со второго сервера, ты наверняка со второго и бОльшая часть всех других наших участников оттуда же. 

> Я считаю что уйдут только неадекваты - а скинуть их на сервера-конкуренты вообще милое дело.

Моя практика участия в проекте в течение 2х лет мне подсказывают, что это заблуждение. Мы можем терпеть присутсвие неадекватов и их наказывать, но мы не может себе позволить разбазаритьваться нормальными игроками.

> адекватный новичик: поймет свою ошибку, расскажет потом друзьям "прикиньте я на одном серврер на губе отсидел, за дело".

Это твои домыслы. При мне постоянные игроки валили с сервера, если на нем заканчивалась основа и народ долго не мог собраться для захода на новую основу. Я хочу сказать, что адекват также спокойно может свалить с сервера, если его наказали незаслуженно и он должен будет чего то там ждать, тем более 5 минут. 

Не надо ставить себя на место игрока и что то за него решать. У нас 60 тыс игроков играло на серверах. Они настолько разнообразны, что чуть ли не к каждому нужен свой подход, и разделение их на 4 группы ничего не даст. Мы не можем просто взять и выкатить наказание в 2.5 раза дольше, потому что мы так подумали, что игрокам будет норм, и при этом думать, что риска потерять игроков нет. 

> За тех кто не намеренно убил, жаловаться много игроков не будут.

Тоже домыслы. Я хоть и нечасто своих убиваю, но даже меня, админа, и после извинений, запросто наказывают. 


Как итог, предлагаю всё тоже, что отписал @ToxaBes , только время отсидки оставить 2 минуты, при необходимости увеличим. 

- никаких таблицек/плакатов кроме таблички с обозначением места.
- никаких кнопок всплывающих каждую минуту
- никаких суммирований времени
- никаких исключений для пилотов
- время отсидки 2 минуты (посте тестирования подумать над увеличением времени)
- в углу экрана показывать таймер сколько осталось сидеть (мин:сек от Х мин до 00:00) (миллисекунды то зачем ))).
- крыша обязательна

**Comment by ToxaBes** [comment]
>3 мин + 1 мин за дополнительную жалобу, нормальный вариант.

Поддерживаю, норм вариант.

> Единственное, для пилотов - если уж делать наказание, то для всех тогда, кто был в экипаже, а не только для пилота. 

Для всех точно не вариант. Арма не дает получить настоящего убийцу из техники, она возвращает пилота/водителя в большинстве случаев и мы тут ничего сделать не можем. Получается что арма считает ответственным effctiveCommander - он и несет ответственность за экипаж.

**Comment by tym32167** [comment]
> 3 мин + 1

Какая от этого польза?

> Единственное, для пилотов - если уж делать наказание, то для всех тогда, кто был в экипаже, а не только для пилота.

Не забывайте, что то же самое относится и к любой другой нелетающей технике.

Я вообще не вижу смысла менять логику наказаний. Зачем? 
Я понял, что тюрьма лучше, чтобы игроки видели, как другие играют, и больше не стремились косячить - это понятно и логично. 
Но зачем менять время и зачем менять логику расчета времени наказания и логику определения убийцы? Пилоты сейчас жалуются на наказания? Это проблема сейчас для нас?  Какой в этом смысл? Что это конкретно даст? Текущая логика не справляется со своей задачей?

**Comment by ToxaBes** [comment]
@tym32167 - я не буду отвечать развернуто, а то получится стена текста которая затрагивает более глобальные вещи на сервере.
Давай сосредоточимся на Гауптвахте. Главное расхождение у нас по времени отсидки. Я считаю что то что есть сейчас (2 минуты) мало чтобы почувствовать что это хоть какое-то наказание. Если оставить 2 минуты, то клетка будет ПОСЛАБЛЕНИЕМ а не УСИЛЕНИЕМ наказания, т.к. 2 минуты с темным экраном тянутся гораздо дольше чем 4 минуты в клетке из которой все видно, с таймером показывающим сколько осталось и возможностью двигаться внутри клетки. При таком тайминге я вообще не вижу смысла менять черный экран на клетку.

**Comment by ToxaBes** [comment]
>(миллисекунды то зачем )

Психологически время идет быстрее.

**Comment by tym32167** [comment]
Если это будет явно послаблением, мы ведь всегда можем это время увеличить, верно? Мы можем выставить 2 минуты, добавить клетку и поглядеть на результат пару дней?
Мои опасения лишь в том, чтобы не потерять игроков. Можно сделать гаупвахту и после всеми админами её потестить. Сейчас для меня это конь в вакууме, я не видел и не сидел там, потому, может ты и прав. Предлагаю сделать клетку и после думать о сроке, при этом надо это всё потестировать и выкатить взрешенное решение о сроке, а не взятое с потолка.

**Comment by tym32167** [comment]
> Психологически время идет быстрее.

это мне без разницы, как считаете нужным, так и делайте.

**Comment by ToxaBes** [comment]
>Сейчас для меня это конь в вакууме, я не видел и не сидел там, потому, может ты и прав.

Да, я говорю о 4-5 минутах потому что посидел в ней сам, потестил. Ок, давай оставим 2 мин в качестве теста и чтобы ты убедился в том что этого мало )

**Comment by tym32167** [comment]
Договорились :+1:

**Comment by RK3QRZ** [comment]
С таким вариантом я согласен. Единственное не совсем согласен со временем наказания. Две минуты это мало, пять вроде много. Идеальный вариант это 3+1 как предложил evil_c0okie ну или 2+1 или вообще 3 минуты для начала. Предлагаю открытое голосование по гауптвахте закрыть в связи с изменениями. За первоначальный вариант я проголосовал против.

**Comment by ToxaBes** [comment]
Гауптвахта готова и лежит в ветке 425_prison_feature. Сегодня протестировали ее с игроками AlexRus и IceSemper - все работает. @Noart - Добавь пожалуйста желтую табличку "Гауптвахта" рядом с клеткой, проверь и примени в dev.

**Comment by RK3QRZ** [comment]
По результату голосования за первую версию гауптвахты - гауптвахте не быть. За измененную версию гауптвахты голосования не было!

**Comment by tym32167** [comment]
@Noart537 даешь голосовалку! :)

**Comment by Noart537** [comment]
За 3
Против 1

**Comment by RK3QRZ** [comment]
1. По правилам 80%, у нас 75% "Критерии принятия изменений на сервере" пункт 1
2. Голосование считается состоявшимся при явке 90% "Порядок проведения голосования" пункт 4
3. Воздержание от голосования правилами не предусмотрено!
О каком исключении речь?

**Comment by Noart537** [comment]
У нас 8 голосующих.
почти в каждом голосовании учавствовали 7 чел = 87,5% - явка не 90% Получается все отменять? =)

**Comment by Noart537** [comment]
Позже создам голосовалку снова.

**Comment by RK3QRZ** [comment]
Пора провести чистку среди администраторов   имеющих право голоса! Среди прочего хочу отметить что оповещение о голосовании не всегда отправляется на почту как того требуют наши правила. Отсюда такой процент неявки.

**Comment by ToxaBes** [comment]
Эм, у Вас в голосовании за "Видимость правил при заходе на сервер" 3 воздержавшихся. В этом голосовании 4 воздержавшихся. Т.е. два голосования подряд 40-50% участников просто все равно как менять миссию.
 
Получается что 80% не наберется по большинству мелких вопросов. Участники не заинтересованы обсуждать ВСЕ вопросы на голосовании. Т.е. например кто-то воздержался по Гауптвахте т.к. на самом деле она ничего серьезного не меняет. Если бы голосовали за переписывание 4 скриптов основы в 1 скрипт т.к. неудобно добавлять изменения, а они фактически одинаковые, то было бы 2 голоса ЗА (ноарт, эвил) и все остальные воздержались бы и т.д.

Похоже что текущая система не работает, слишком много бюрократии либо слишком много участников. Вы голосуете уже в 3 раза дольше чем я делал эту клетку, это не нормально. 

У вас сейчас по правилам 80% надо. Ну так дополните его: "80% при 100% явке" (все на голосовании - вопрос серьезный). Если явка меньше 100% то считается простое большинство голосов между ЗА и ПРОТИВ (часть забила на голосование или воздержалась - вопрос мелкий).

В итоге те кому все равно не будут тормозить тех то занят развитием миссии.

**Comment by Noart537** [comment]
Ну вот поэтому и предлагал сделать исключение. Так и будем сейчас голосовать пока не наберем 90% явки. и 80% за. Сейчас прийдется снова 3 дня ждать)

**Comment by Noart537** [comment]
Что с пилотами? Тоже наказываем? Или оставим как сейчас есть?

**Comment by ToxaBes** [comment]
Оставляем как есть.

**Comment by RK3QRZ** [comment]
Система работает! Не нужно ничего выдумывать, это косяк Noartа. Он не разослал уведомления о голосовании. Нужно нам подумать над цифрами 80% и 90%. И заняться чисткой, тех кто не явился на голосование более 4 раз без уважительной причины, лишать права голоса навсегда. И ничего страшного, подождем окончания голосования еще 3 дня. Вас кто-то подгоняет куда- то?

**Comment by ToxaBes** [comment]
>Система работает!

Ага, я вижу. Если бы она работала этого обсуждения бы тут не было. 

>Вас кто-то подгоняет куда- то?

Да. Меня абсолютно не устраивает скорость принятия решений (3 дня на мелкий вопрос, на текучку?). Меня не устраивают эти качели когда один говорит да делаем, я трачу выходные на это, а потом второй говорит - мы не проголосовали. 

Чистки, проценты и прочее меня вообще не касаются и не интересуют. Я просто предложил один из вариантов избавления от бюрократии. Моя главная претензия в том что решение делать или не делать принимается дольше чем сам процесс реализации. Давайте закончим выносить все это в публичное поле, разберитесь там у себя и выдайте мне результат.

**Comment by RK3QRZ** [comment]
Тебе никто и не просил делать это до результатов голосования. Ты сам взялся бежать впереди провоза,  а теперь чем то недоволен.

**Comment by Noart537** [comment]
мой косяк, первый раз не отправились письма, сейчас только увидел что в исходящих висит. Повторное ушло в отправленные.

**Comment by ToxaBes** [comment]
@RK3QRZ
>Тебе никто и не просил делать это до результатов голосования. Ты сам взялся бежать впереди провоза, а теперь чем то недоволен.

Если ты промотаешь страницу вверх то увидишь:

>**tym32167** commented 4 days ago
это мне без разницы, как считаете нужным, так и делайте.
**ToxaBes** commented 4 days ago
Да, я говорю о 4-5 минутах потому что посидел в ней сам, потестил. Ок, давай оставим 2 мин в качестве теста и чтобы ты убедился в том что этого мало )
**tym32167** commented 4 days ago
Договорились :+1:
**RK3QRZ** commented 4 days ago
С таким вариантом я согласен.

* Тим - руководитель разработки. Так или нет? 
* Мы пришли к тому что делаем гауптвахту. Делаем с тем временем которое есть сейчас, по 
результату посмотрим. Тим сказал делать и ты написал что с таким вариантом согласен. Так или нет?

Если бы мне написали погоди, давай дождемся результатов голосования - я бы не делал ничего.

**Comment by tym32167** [comment]
@ToxaBes 
Не переживай, твой труд не пропадет, мы его обязательно запустим. 
Я уже не занимаюсь разработкой, разработкой занимается @Noart537 
С процессом да, есть проблема, но это необходимое зло, так как до этого было ещё хуже. Нам есть куда стремиться и мы обязательно подумаем, как можно было бы ускорить процесс принятия решений. Я знал, что ты начал разработку до нашего голосования, но решил, что дело ты делаешь полезное и его все примут, а пока это принятие будет длиться, ты уже можешь перегореть или у тебя не окажется уже времени. Потому я тебя не остановил. Все косяки можно списать на меня, но я точно знаю, что ты сделал полезное дело и не вкрутить его будет неразумно. Потому не стоит об этом заморачиваться, всё будет хорошо.

**Comment by ToxaBes** [comment]
@tym32167 - я не переживаю за гауптвахту. Если по голосованию она не пройдет - значит не нужна. Ничего страшного. Я переживаю за то с какой скоростью происходит принятие/отклонение предложений и то что система дает сбои. С текущей системой действительно легко перегореть т.к. видя что интересные вещи, которые можно сделать и забыть за несколько месяцев, придется делать годами -  пропадает всякое желание что-то предлагать и делать. 
Мы все тратим свое время на этот проект - так давайте тратить его эффективно. Все что я прошу - отладьте систему принятия решений.

**Comment by RK3QRZ** [comment]
Три дня это вполне нормальный срок. И ничего тут переделывать не нужно. У каждого помимо проекта есть свои проблемы, семья и т.д., вот я например сейчас в больнице лежу и у меня не всегда есть время зайти и почитать новости на проекте. К принятию решений тоже нужно подходить взвешенно,  чтобы потом игроки не испытывали дискомфорта на нашем сервере и приходили снова. Первый вариант гауптвахты тому яркий пример, слишком много вопросов возникло в процессе голосования которые требовали уточнения. Да я сказал, что согласен с последней версией гауптвахты, но помимо нас есть и другие администраторы которые принимают участие в голосовании и на гитхабе в обсуждениях не участвуют. Кто муже ты сам всегда  говорил что будешь делать ту или иную работу только после результатов голосования. Выходит ты сам противоречишь себе. Подводя итог скажу, что не нужно бежать впереди паровоза и потом искать виноватых.

**Comment by Noart537** [comment]
Одобрен. В ближайшее время добавим в миссию

**Comment by tym32167** [comment]
Ура ура

**Comment by Noart537** [comment]
Введен успешно, закрываю.
