### ISSUE TITLE
Спецоперация Желтый Туман

### ISSUE THREAD

**Issue by ToxaBes** [TEHGAM/ADR#428]
Вводная: нам поступила информация о странном складе ГСМ противника. Охрана склада часто ходит в противогазах и комплектах химзащиты. Есть подозрние что часть емкостей сожержит иприт. Командование назначило десантную спецоперацию.<br/><br/>
Цель: выдвинуться в указанный район, проникнуть на базу и обезвредить бочки с химоружием.

**Comment by AlexVDem** [comment]
А текстуры охраны в противогазах есть? По идее и диверсионному подразделению надо противогазы выдавать, вдруг шальная пуля в бочки с отравой попадет?

**Comment by ToxaBes** [comment]
Вся изюминка в том что противогазов нет )

**Comment by AlexVDem** [comment]
Ну хорошо, а у охраны тоже нет? Было бы здорово для реализма. Такая миссия в стиле Resident Evil. ;)

**Comment by ToxaBes** [comment]
Ни у кого нет.

**Comment by Noart537** [comment]
Можно пилотные шлемы =) https://community.bistudio.com/wikidata/images/a/a5/Arma3_CfgVehicles_B_Pilot_F.jpg

**Comment by ToxaBes** [comment]
Нет, вся соль в том что противогаз не поможет, нужен изолирующий дыхательный аппарат с костюмом полной хим защиты. А т.к. в них десантироваться невозможно, то приходится десантироваться как есть и быть очень осторожными с бочками...

**Comment by AlexVDem** [comment]
Кстати, это очень хорошая мысль -  десантирование. Предлагаю сделать эту задачу возможной только для десанта с воздуха. Т.е. легенда такая - вокруг базы сторожевые посты и датчики, и попасть по земле нельзя (включается тревога и через пару секунд тебя накрывает огнём). Единственный вариант - по воздуху с парашютом. Это можно скриптово прописать, например если высота игрока на подходе не менее 50 метров.

**Comment by ToxaBes** [comment]
>Кстати, это очень хорошая мысль - десантирование. Предлагаю сделать эту задачу возможной только для десанта с воздуха.

Так, давайте вы дождетесь релиза :) Она так и задумана что попасть можно с воздуха. Я добавил этот тикет не для обсуждения (все уже придумано), а для того чтобы можно было отдельной веткой разрабатывать эту миссию.

**Comment by AlexVDem** [comment]
Ну ок, ты же не сказал что там будет, вот и креатив попер... ;)
Готов буду потестить на своем сервере это задание, если надо.

**Comment by ToxaBes** [comment]
@Noart - поставь пожалуйста на голосование. Я не буду продолжать без подтверждения.
Описание спецоперации в первом посте. Из особенностей:
* можно попасть только с воздуха (воздушно-десантная).
* при попадании в бочки газ заполняет территорию склада и все погибают/миссия провалена.

**Comment by Noart537** [comment]
Антон, спец операции, которые ты делаешь будут добавляться без голосования!

**Comment by malashin** [comment]
Как реализовано ограничение, что попасть туда можно только с воздуха?

**Comment by ToxaBes** [comment]
>спец операции, которые ты делаешь будут добавляться без голосования!

ок, хорошо.

>Как реализовано ограничение, что попасть туда можно только с воздуха?

3х метровый бетонный забор по периметру с отключенным уроном и симуляцией.

**Comment by Noart537** [comment]
3-х метровый бетонный забор с электрической проволокой и стационарными пулеметами, за которым злые собаки, готовые растерзать каждого). С внешней стороны забора, ров с крокодилами, перед рвом минное поле. =)

**Comment by Noart537** [comment]
Антон, подскажу из личного опыта, заборы, ограждения, которые ты хочешь сделать неубиваемыми, применяй к ним не только this allowDamage, но и "this enableSimulationGlobal false;" теоритически клиент не будет их постоянно считывать.

**Comment by ToxaBes** [comment]
Ты бы хоть код сначала посмотрел :)
https://github.com/TEHGAM/ADR/blob/4c400ab0c3d092620bc118365358f02ae7f48d72/co47_ADR_Blue_Shark.Altis/scripts/%3DBTC%3D_TK_punishment/%3DBTC%3D_tk_init.sqf#L129

**Comment by Noart537** [comment]
аа ок :) да на работе некогда совсем) если уверен что все работает, то я могу залить в dev и на сервере сегодня-завтра запустим посмотрим.

**Comment by ToxaBes** [comment]
Там осталось сделать БОВ и можно будет тестить.

**Comment by AlexVDem** [comment]
Можем вечером затестить.

**Comment by ToxaBes** [comment]
Применил в dev.
