### ISSUE TITLE
Повторяющиеся ошибки в миссии

### ISSUE THREAD

**Issue by ToxaBes** [TEHGAM/ADR#430]
Есть 3 повторяющиеся ошибки:
* При заходе на сервер
![2016-01-31_00001](https://cloud.githubusercontent.com/assets/3309152/12702023/7c3fff0e-c82c-11e5-8669-8724385d829b.jpg)
* При сохранении снаряжения
![2016-01-31_00002](https://cloud.githubusercontent.com/assets/3309152/12702025/831dd88c-c82c-11e5-9f6e-b2fb175924b6.jpg)
* При возрождении на базе
![2016-01-30_00001](https://cloud.githubusercontent.com/assets/3309152/12702026/8969f392-c82c-11e5-81f7-34d70ad492b1.jpg)

**Comment by ToxaBes** [comment]
Последняя ошибка возможно та же что и в #422

**Comment by AlexVDem** [comment]
Ни разу такой ошибки не видел. Да и вообще скриптовых ошибок на этом сервере. Возможно оттого, что у меня стоит английская версия игры?

**Comment by ToxaBes** [comment]
Ты их не видел потому что у тебя не стоит флаг "Показывать ошибки в сценариях".

**Comment by AlexVDem** [comment]
А где поставить? Мог бы протестировать. Хотя, ошибка наито и ошибка, чтобы как то проявляться. Если не проявляется без флага - да и хрен с ней... ;)

**Comment by ToxaBes** [comment]
Ошибки пофиксил.
