### ISSUE TITLE
Наказание для пилотов

### ISSUE THREAD

**Issue by ToxaBes** [TEHGAM/ADR#431]
Нужно придумать как наказывать пилотов которые часто разбиваются на вертолетах (и нужно ли вообще это делать) т.к. на гауптвахту пилоты не попадают.

Предложения:
* @Noart537 <br>
Может лучше сделать просто предупреждение? Если продолжает падать какое-то кол-во раз, то заносить его id в массив, который будет проверяться при залезании в вертолет. Если его id будет в массиве, то его будет выкидывать из ветра. После рестарта обнуляется. ID Злостных нарушителей можно в ручную заносить в файл проверки на пилота "черный список", который проверяется при залезании в технику. Но это дополнительная работа администраторам.
* @AlexVDem
 - если статус игрока - пилот
 - если за последние 10 минут он погиб 3 раза, тогда делаем вывод, что летать он не умеет, или воюет не пилотом на земле...
<br>тогда:
 - сажаем его на "губу" за порчу вертушек или невыполнение обязанностей пилота
 - если игрок зашёл другой ролью - с "губы" выпускается
 - если зашёл опять с ролью пилота - но через час (потренировался в редакторе) - тоже выпускаем.

Основная цель автоматизировать работу админа по указанию "сменить слот" и снижению количества неадекватных пилотов или пилотов не играющих за свою роль.

**Comment by tym32167** [comment]
Можно ли во время убийства пилотом игрока отследить, если пилот находится в летающей технике, то работать с алгоритмом этого тикета, если нет, то работать в соответсвии с тикетом #425 ?

**Comment by ToxaBes** [comment]
Обычно при убийстве пилотом игрока сам пилот тоже погибает, т.е. нельзя получить чем он управлял, только его класс. Но можно проверять, жив ли пилот на момент проверки - если нет то это похоже на наш случай. Хотя и тут есть исключения вида: сел пилот в страйдер поехал на основу, уходя от обстрела сбил своего и получил от ботов Пт-ракетой. В таких случаях будет ложное срабатывание. Возможно есть смысл оставить так как есть сейчас - неадекватных пилотов кикают админы .

**Comment by malashin** [comment]
Технику жертвы и убийцы получить можно. Это уже реализовано. Нельзя получить кто именно убийца в технике, это всегда пилот по логике игры.

**Comment by ToxaBes** [comment]
>Технику жертвы и убийцы получить можно.

Да, в случае если пассажир погибнет раньше, но если пилот погибнет чуть раньше пассажира то убийцей пассажира будет Null. Ну и по технике все верно, возвращается не те тот кто убил а effectiveCommander в большинстве случаев.

**Comment by AlexVDem** [comment]
Хотел бы только напомнить, что скрипт наказаний и сейчас глюкавый, если убийца в технике сидел. И ничего с этим пока сделать нельзя, т.ч. разницы нет - пилот там был или не пилот. Тут задача стояла другая - заставить пилотов летать, летать хорошо, а если не умеешь - воевать пехотой. А если пилот взял БТР и из него всех своих расстрелял - это другой случай, для админов.

**Comment by ToxaBes** [comment]
К сожалению, мы не сможем программно со 100% уверенностью отделить опытного пилота, которому при посадке открыли рампу и он разбился от новичка который просто разбил верт. Предлагаю закрыть тикет.

**Comment by ToxaBes** [comment]
@AlexVDem  - сама идея хороша, но есть большая проблема в реализации. 
Ты хороший пилот, но представь что ты по-очереди:
* зацепился хвостом при посадке на склоне
* подбит штурмовиком
* подбит зениткой при подлете к зоне

и т.д., вариантов хватает. 
И все. Ты целый час не можешь летать - мы на час потеряли хорошего пилота. 
Тикет закрываю ввиду невозможности реализации.
