### ISSUE TITLE
Видимость правил при заходе на сервер

### ISSUE THREAD

**Issue by ToxaBes** [TEHGAM/ADR#433]
Есть предложение при заходе на сервер показывать диалог с правилами, кнопкой "Ок" и сноской "Нажимая Ок я соглашаюсь с правилами и обязуюсь не нарушать их".

**Comment by RK3QRZ** [comment]
Видимость правил при заходе на сервер где юзеру нужно нажать кнопку ОК (соглашение с правилами сервера) практикуется на многих серверах.Я за такое нововведени.

**Comment by malashin** [comment]
Давайте только хранить тогда GUID игроков в массиве, чтобы они не выскакивали каждый раз при заходе, а только после рестарта сервера.

**Comment by tym32167** [comment]
@malashin только что это отписал в голосовалке :)

**Comment by ToxaBes** [comment]
Напишите тут результат админского голосования по тикету.

**Comment by AlexVDem** [comment]
Я хоть и не админ, но могу сказать что это нафиг не нужно. Никто это не читает, только лишнее движение. Правила читают только в том случае если чел. был наказан админом и ему надо убедится, что его наказали справедливо. Но и это редкость. Поэтому пусть правила будут в разделе карты для галочки, а глаза мозолить лишним окном ни к чему.

**Comment by Noart537** [comment]
За 5

**Comment by ToxaBes** [comment]
@Noart537  - это Да или Нет? Пиши пожалуйста результат в виде "Принято на голосовании. Делаем" или "Не принято на голосовании. Не делаем".

**Comment by Noart537** [comment]
на повторное, не набрали 90%...

**Comment by Noart537** [comment]
Пока пусть ветка висит. Еще раз голосовать будем. Вот вступил бы к нам в админы, и смог бы видеть кто такой нехороший голосует против))

**Comment by ToxaBes** [comment]
Мне не важно кто против, это его право и у него есть свои аргументы для этого. Он может быть прав а мы ошибаться. Для этого и делается голосование чтобы решить.

**Comment by Noart537** [comment]
Да я с юмором).

**Comment by Noart537** [comment]
Одобрен большинством, в ближайшем обновлении будет добавлен.

**Comment by ToxaBes** [comment]
Необходимо рассмотреть, что из примечаний можно убрать. Я взял полный вариант с форума и сделал диалог с учетом всех разрешений экрана (диалог не переносит строки - не подстраивается под ширину). Получилось вот что:
![2016-02-12_00002](https://cloud.githubusercontent.com/assets/3309152/13017403/0e0e209e-d1d5-11e5-945a-eb529cca421b.jpg)

Могу ли перефразировать/убрать примечания, не затрагивая сами правила?

**Comment by ToxaBes** [comment]
@Noart537 - проверяй результат (смерджил в dev):
![2016-02-13_00003](https://cloud.githubusercontent.com/assets/3309152/13028464/d62c2bce-d280-11e5-9429-02f8f93c346d.jpg)

Если текст не устраивает, его можно менять в scripts/rules/info.sqf

**Comment by Noart537** [comment]
Все норм, надо пересмотреть будет п1, пп8. Для данного сервера не актуально.

**Comment by RK3QRZ** [comment]
Почему не актуален пункт 1? Еще как актуален!

**Comment by malashin** [comment]
Речь об 1.8 идет.

**Comment by RK3QRZ** [comment]
Ок.

**Comment by ToxaBes** [comment]
Сегодня видел форму на сервере - все работает. Тикет закрываю.
