### ISSUE TITLE
Предложение. А не сделать ли арсенал для загрузки техники?

### ISSUE THREAD

**Issue by AlexVDem** [TEHGAM/ADR#434]
Или подобную фичу для существующего арсенала? Как я себе это представляю? Подъезжаешь к арсеналу, открываешь его, в арсенале появляется кнопка "загрузить в технику" и все что там есть в списке  помещается в инвентарь Охотника. Предварительно естественно нужно сохранить это. Кнопка загрузки и сохранения профилей для техники доступна только тем, кто сидит в технике на месте водителя.
Это сильно упростит жизнь при наборе в инвентарь перед выездом на задание. То, что не помещается в инвентарь просто не загружается.

**Comment by tym32167** [comment]
Уже думали над этим. ИМХО, зачем нам пачка кемперов со стационарками на машинах? Чем их меньше, тем интересней. Иначе кидаешь портянку стационарок и в одного губишь хоть допку, хоть основу - ну куда это годится.

**Comment by ToxaBes** [comment]
Не забывайте закрывать тикет если предложение не дошло до голосования.

**Comment by AlexVDem** [comment]
Не только стационарки, я например часто патроны для линкс или мар кидаю, аптечки, подрывные заряды, гранаты и пр. мелочевку... СВАТ часто на допки ездит один со стационарками. Да и потом, второй сервер же это аркадный сервер, пусть игрокам будет удобнее...

**Comment by tym32167** [comment]
Сохрани снаряжение с рюкзаком с патронами, потом грузишь его и рюкзак кидаешь в технику - это быстро происходит. 
>Да и потом, второй сервер же это аркадный сервер, пусть игрокам будет удобнее...

Игрокам не будет удобнее, если точку будут убивать до того, как игрок туда сможет добраться. Я вот, к примеру, часто иду в бой с прямым контактом с противником и люблю технику подрывать минами и взрывпакетами, но я не смогу это сделать, если на сервере будет много кемперов с ПТ.

**Comment by AlexVDem** [comment]
Тут я согласен, но добавление реализма в данном случае могло бы быть посредством ограничения мощности и дальности действия титанов. Я это предлагал, но не нашло одобрения. Как и ограничить использование ПП ракет, сейчас один ПТшник легко может вынести всю миссию, забив страйдер ракетами под завязку. Так что дело тут не в стационарных установках, или не в инвентаре, а в балансе оружия. ;)

**Comment by ToxaBes** [comment]
>ПТшник легко может вынести всю миссию, забив страйдер ракетами под завязку.

Можно например сделать так: если больше 3х стационарных титанов либо больше 10 ПТ ракет в **легкой технике** - у нее ломаются передние колеса. В этом случае они будут ездить либо на тяжелой технике (хемты/бронетехника) что довольно медленно, либо возвращаться на базу после каждой основы.

**Comment by AlexVDem** [comment]
Надо чтобы при таком раскладе вылезало сообщение - "техника перегружена", и она не ехала быстрее 10 кмч, это будет лучше чем если она будет ломаться.

**Comment by tym32167** [comment]
Да, давайте напишем скрипт, а потом другой скрипт, чтобы первый скрипт мог работать :) По моему, проблема надуманная. Чем меньше скриптом, тем меньше проблем со скриптами. Хотите слоджностей для кемперов? Они уже есть - вручгую грузить/разгружать технику. Не надо ничекго добавлять.

**Comment by ToxaBes** [comment]
Ок, закрываем тикет.
