### ISSUE TITLE
Ошибка сценария после применения гаупвахты.

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#435]
![107410_2016-02-10_00001](https://cloud.githubusercontent.com/assets/8770445/12948822/4ba7aafc-d026-11e5-97b1-5a5d2dd11aa8.png)
Если не серьезная, то закрывайте.

**Comment by ToxaBes** [comment]
Это не гауптвахта. Это в ветке 381_weaponlost_bug
Попробуй в [этой]( https://github.com/TEHGAM/ADR/blob/dev/co47_ADR_Blue_Shark.Altis/scripts/%3DBTC%3D_revive/%3DBTC%3D_functions.sqf#L1055) строке заменить:
```sqf
[_injured,"BTC_addMissingItems",nil,true] spawn BIS_fnc_MP;  
```
на
```sqf
[[_injured],"BTC_addMissingItems",nil,true] spawn BIS_fnc_MP;  
```

**Comment by Noart537** [comment]
Завтра заменю. Спс.

**Comment by ToxaBes** [comment]
Применил.
