### ISSUE TITLE
Дать больше времени перед обороной

### ISSUE THREAD

**Issue by malashin** [TEHGAM/ADR#436]
Дать больше времени для подготовки перед обороной точки.

**Comment by Noart537** [comment]
1-2 минуты?

**Comment by malashin** [comment]
Я думаю
```sqf
sleep (60 + random 121)
```

**Comment by Noart537** [comment]
Отправляю на голосовалку

**Comment by AlexVDem** [comment]
Может тогда и таймер обратного отсчета предусмотреть, как на гауптвахте?

**Comment by Noart537** [comment]
не одобрили
