### ISSUE TITLE
Просьба добавить функционал приглушения звука (беруши).

### ISSUE THREAD

**Issue by AlexVDem** [TEHGAM/ADR#438]
На примере любого просто скрипта, хотя бы вот этого: https://arma3.ru/forums/topic/5331-ochen-prostoi-skript-berush-earplugs/
Почему лучше делать по нажатию клавиши на клавиатуре? Потому что скорость использования быстрее, для связи это критично, не надо крутить колесико мыши. Можно и продублировать - по клавише + пункт меню.

Пилоты вертолетов оценят, крайне необходимая штука. Да и все, рядом с кем села вертушка с включенным двигателем - и надо говорить в чат или в TS.
Сейчас такого функционала нет, приходится лезть в дебри настроек и убирать звук, что не удобно.
В идеале было бы здорово если был бы скрипт, позволяющий настроить уровень приглушения (т.е. в начале игры настроил, потом пользуешься, аналогично прорисовке).

**Comment by Noart537** [comment]
Уже голосовали недавно, не одобрили.

**Comment by AlexVDem** [comment]
Тут голосовали? Я предварительно посмотрел закрытые темы, прошелся поиском, такой темы не нашел.

**Comment by Noart537** [comment]
На форуме, в админском канале.

**Comment by AlexVDem** [comment]
А, понятно, туда у меня доступа нет.
Жаль, хоть и непонятно почему, это просто фича, которая не меняет игровой процесс. Кому надо - пользуется, кому нет - не пользуется. Голосовать против фичи, которая добавляет удобства пользователю и то исключительно по его желанию как то нелогично.

**Comment by ToxaBes** [comment]
У нас вертолеты возят десант - они не используют беруши, тут все верно. Но пилоты/стрелки в вертолете - используют их. И вот для них добавить беруши скриптом/через меню действий было бы неплохо.

**Comment by AlexVDem** [comment]
Тоха, кстати, хотел тебе написать в тимспике, но буду за игровым компом только вечером - т.ч. напишу тут, если сочтешь что не стОит, просто потри и все. 
Я насчет миссии спасения заложников - как то она непонятно кончается, заложники посреди минного поля спасаются, а дальше что? Может быть стоит сделать так: кто убил командира становится руководителем отряда из заложников (т.е. может управлять отрядом дружественных ботов). Ну или сделать какой то иной триггер взять отряд под контроль. После этого командир должен посадить ботов-заложнков в вертушку или в авто и довезти их до базы, а там посадить в хеммит или еще какой то триггер спасения. Хеммит уезжает и тогда миссия считается законченной, все спасены... )))

**Comment by ToxaBes** [comment]
Я думал над таким вариантом:
1. получается слишком много условий в миссии.
2. Везти ботов на базу - неинтересно, а добавлять еще и преграды на пути на базу - это слишком много для спецоперации. 
3. Ты пробовал давать команду 4м ботам чтобы они прошли именно в тот проход который разминирован? :)

Короче идя хорошая, но реализация настолько проблемная что не стоит того. А так штурмовая группа нашла/спасла заложников и передала другой группе которая их выведет (сделал просто исчезновением заложников).

**Comment by AlexVDem** [comment]
Как раз мне кажется что везти ботов на базу интересно, т.к. в один страйдер они не влезут, нужен либо грузовик либо Маршалл... Ну или адекватный пилот. По пути могут сбить или штурмовик уничтожить транспорт на земле. Т.е. эвакуация настоящая, а не "виртуальная". В учебке всегда говорили: "если стих огонь - еще не значит, что все кончилось, возможно самая жопа сейчас начнется..." )))

**Comment by ToxaBes** [comment]
@Noart - отдай пожалуйста на голосование вариант с берушами только для пилотов/стрелков вертолетов либо закрой тикет если такой вариант не подходит.

**Comment by Noart537** [comment]
Я понимаю что это удобно, сам неоднократно пользовался на RF3 Exile . Но зайти в настройку и убавить громкость двигателя это 5-10 секунд. Если будешь с берушами летать, не услышите пуски по вам).  Голосование с берушами было неделю назад, посчитали что ненужный.

**Comment by AlexVDem** [comment]
Я понял, жаль... 
Хотелось бы отключать / включать беруши не за 10 сек, а за 0.5 сек., это критично. Я тогда вообще звук не буду увеличивать. Хотя это и снижает атмосферу игры, но позволяет хоть как то общаться. Совершенно непонятно, кому этот дополнительный функционал может помешать?
Пуски ракет ты и так и так можешь не услышать, т.к. беруши делают ровно тоже самое - приглушают основной звук оставляя звук рации. Да и потом - не услышать звук БКО будет очень трудно даже при низком звуке, очень специфичная пищалка, лично я её всегда слышу.
