### ISSUE TITLE
Удаление воронок от взрывов

### ISSUE THREAD

**Issue by AlexVDem** [TEHGAM/ADR#439]
Часто на базе после взрыва вертушек происходит вот такая картина:

![https://lh3.googleusercontent.com/-OWi1BkwxvwI/VtFrXV5TTYI/AAAAAAAAIVg/86mB3Ff8Png/s2580-Ic42/2016-02-27_00001.jpg](https://lh3.googleusercontent.com/-OWi1BkwxvwI/VtFrXV5TTYI/AAAAAAAAIVg/86mB3Ff8Png/s2580-Ic42/2016-02-27_00001.jpg)

Из-за этого вертушки продолжают взрываться на респауне. Если повреждена взлетка - то мешает взлетать. 
Предлагаю вставить скрипт удаления воронок в скрипт очистки базы или дать эту возможность Бобкету. 
Скрипт например как вот тут: http://www.armaholic.com/page.php?id=28279

**Comment by Noart537** [comment]
Обновил миссию на сервере 29.02. Антон ускорил немного очистку рытвин. Посмотрим как пойдет далее.

**Comment by malashin** [comment]
Раньше 10 кратеров оставалось на карте всегда и удалялись только те, что давно уже существуют и их в сумме их больше 10, при этом 10 самых свежих оставалось. Или если небыло игроков в 5 км от кратеров.

То есть сейчас они очень быстро будут пропадать по сравнению с тем, что было. Все удаляются каждые 4 минуты, 8 минут если игроков меньше 24.

**Comment by AlexVDem** [comment]
я фотку не зря привел, то ли скрипт очистки глюканул, то ли взрыв вертушек порождает новые воронки и все начинается по кругу опять, но пока я не привез бобкет и не оттащил обломки подальше - вертушки взорвались несколько раз (до меня взрывались, и на моих глазах взорвались 3 раза)
