### ISSUE TITLE
Наказание для пилотов которые разбиваются на базе

### ISSUE THREAD

**Issue by ToxaBes** [TEHGAM/ADR#441]
Нужно уточнение:
1. Количество катастроф до посадки в клетку
2. Время отсидки в клетке
3. Радиус зоны на базе в которой действует это правило

**Comment by AlexVDem** [comment]
Хотел бы дать предложение. Поскольку цель - не выйти из игры совсем, а заставить сменить слот, то наказание должно быть продолжительным, но при смене слота оно снимается.

**Comment by ToxaBes** [comment]
>наказание должно быть продолжительным, но при смене слота оно снимается.

Набил вертушек -> перезашел на другой слот -> перезашел за пилота -> опять можно бить вертушки...

Нет уж - в клетку значит в клетку )

**Comment by AlexVDem** [comment]
А нельзя так - если в течении получаса зашел за пилота, то в клетку? Или тебя автоматом кикает, если зашел пилотом?

**Comment by Noart537** [comment]
Тим такой вопрос задавал. Как отследим, сам пилот разбил или негодяй какой ему винты посбивал специально его наказать? =)

**Comment by ToxaBes** [comment]
>А нельзя так - если в течении получаса зашел за пилота, то в клетку? Или тебя автоматом кикает, если зашел пилотом?

Слишком сложные правила. Накосячил - отсиди.

>Как отследим, сам пилот разбил или негодяй какой ему винты посбивал специально его наказать? =)

2 раза в течении 10 минут в радиусе 200-300м от базы - в клетку. Если в первый раз сбили на базе - не надо взлетать во второй раз пока не сбили вражескую авиацию, лучше пойти включить ПВО. Если тебя подбивает свой специально - то в клетку его или админ его кикнет. И лети спокойно.

**Comment by RK3QRZ** [comment]
Предлагаю:
1. Три разбитых вертолета/самолета
2. Не менее 5 минут (меньше делать не имеет смысла)
3. Вся база включая взлетные полосы и авиабазу.

**Comment by Ded-PikhTo** [comment]
плюсую

**Comment by Noart537** [comment]
Альтернативный вариант наказания не пускать в технику пилотом.

**Comment by Ded-PikhTo** [comment]
Тогда пилотом не пускать на время большее, чем отсидка на гаупвахте.

**Comment by RK3QRZ** [comment]
Если не пускать, то он продолжит дальше играть занимая слот пилота, а если наказать на 10 минут, то ему надоест сидеть в клетке и он свалит.

**Comment by Ded-PikhTo** [comment]
С другой стороны, сидя в клетке он тоже будет занимать слот пилота. Просто выкидывать со слота  на 5 минут с предупреждением. Также это могут видеть все игроки, чтобы понимать, кто бьёт технику и не умеет летать. Также любой игрок, видя это сообщение, может перезайти на освободившееся место пилота.  В клетку садить смысла нет, так как и так понятно, что это не пилот и трени на серве запрещены.

**Comment by RK3QRZ** [comment]
Сидеть в клетке надоест и он сам свалит. Смысл в неотвратимости наказания, за нарушения должен быть наказан, а не просто кик со слота.

**Comment by ToxaBes** [comment]
Голосованием одобрено сидение в клетке. Зачем обсуждать тут про в клетке/не в клетке? 
Я просил уточнить детали с первого поста, это реально так сложно сделать? (только S.W.A.T прочитал и ответил по пунктам свое предложение).
По прежнему жду от админов принятого решения по перечисленным пунктам.

Я предлагаю так:
1. 2 любых уничтоженных техники (самолет, вертолет, маршал и тд)
2. в течении 10 минут
3. 800м от центра базы (включает всю базу и взлетку)

Если расширим правило и на наземную технику, сразу сможем наказывать тех кто садится на базе в свою технику и расстреливает пустую.

**Comment by RK3QRZ** [comment]
1. Две уничтоженных техники мне кажется мало, нужно учитывать внезапные появления зенитных батарей и вражеских штурмовиков над базой.
2. Голосование было только о наказании пилотов, но я не против если это распространится на всех. Т.е любой игрок уничтоживший на базе 3 техники подряд в течении 10 минут отправляется в клетку. И было бы неплохо сделать оповещение за что он туда попал.
3. Тоха ты не написал про время наказания.

**Comment by ToxaBes** [comment]
Забыл про время, вот исправленный вариант:

1. 3 любых уничтоженных техники (самолет, вертолет, маршал и тд) в течении 10 минут
2. на 10 минут в клетку
3. радиус 800м от центра базы (включает всю базу и взлетку)

**Comment by malashin** [comment]
Я согласен.

Нужно написать игроку в клетке, что он сел за порчу техники на базе.

**Comment by RK3QRZ** [comment]
Согласен.

**Comment by ToxaBes** [comment]
ок, тогда делаю:

1. 3 любых уничтоженных техники (самолет, вертолет, маршал и тд) в течении 10 минут
2. на 10 минут в клетку
3. радиус 800м от центра базы (включает всю базу и взлетку)
4. сообщение меняю на "ВАС НАКАЗАЛИ ЗА УБИЙСТВО СВОИХ \ ПОРЧУ ТЕХНИКИ НА БАЗЕ!" (заодно перенесу в stringable.xml и переведу на английский)

**Comment by AlexVDem** [comment]
А зачем время, за которое игрок технику уничтожил учитывается?

**Comment by ToxaBes** [comment]
Затем что если время не учитывать то нормальные пилоты тоже попадут в клетку. Это правило для тех кто заходит на сервер и сразу бежит бить технику одну за одной рассказывая какой он крутой пилот и посылая всех в чате.

**Comment by AlexVDem** [comment]
Я про технику, а не про авиацию. По моему если чел на базе за полчаса потерял 3 танка или 3 страйдера, то это тоже повод усомнится в его адекватности.

**Comment by ToxaBes** [comment]
А если за час, за два? это уже адекватность или еще нет? 
Это правило не включает в себя все возможные варианты событий. Оно решает главную проблему - наказывает тех кто уничтожает техника на базе без перерыва, одну за другой, не важно в какой комбинации. 10 минут для этого - оптимально.

**Comment by ToxaBes** [comment]
Готово к проверке на втором сервере.
