### ISSUE TITLE
Спецоперация Гроздья Гнева

### ISSUE THREAD

**Issue by ToxaBes** [TEHGAM/ADR#443]
Откровение Иоанна Богослова 14:9-11, 18-20:

10будет пить вино ярости Божией, вино цельное, приготовленное в чаше гнева Его, и будет мучим в огне и сере пред святыми Ангелами и пред Агнцем... 
18обрежь гроздья винограда на земле, потому что созрели на нём ягоды. 
19И поверг Ангел серп свой на землю, и обрезал виноград на земле, и бросил в великое точило гнева Божия...

Последняя и самая сложная миссия из цикла спецопераций.

**Comment by Noart537** [comment]
Она в небе будет? =)

**Comment by ToxaBes** [comment]
Просто название придумал, а описание - не до конца )

**Comment by ToxaBes** [comment]
Миссия готова к тестированию на сервере (залил ветку в dev).

**Comment by AlexVDem** [comment]
Тоха, поправь в описании: спутник-шпион это не то, что ты написал, шпион он по определению наблюдает. А это ударный орбитальный комплекс.

**Comment by ToxaBes** [comment]
Это спутник-шпион двойного назначения :) может работать как в пассивном (наблюдение) так и активном (лазер) режиме. Твой вариант звучит серьезнее, исправил.
