### ISSUE TITLE
Пропадают ручные ПТ средства

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#444]
Когда играешь за Ракетчика ПТ при смерти пропадает (титан, pcml, аламут) и ты как ракетчик становишься бесполезным.

**Comment by ToxaBes** [comment]
Это тот же баг что был с основным оружием. Вторичное оружие я не фиксил в тот раз.

**Comment by Noart537** [comment]
Получится пофиксить?

**Comment by ToxaBes** [comment]
Проверяй.
