### ISSUE TITLE
Новое дополнительное задание "Узел связи и РЭБ"

### ISSUE THREAD

**Issue by AlexVDem** [TEHGAM/ADR#446]
Предлагаю новую допку, рассчитанную на инженеров и контактный бой с противником
Дело было вечером делать было нечего, да и игровой комп сломался. Т.ч. решил сделать допку, которую давно хотел.
Сюжет: противник развертывает на острове узел РЭБ (радиоэлектронной борьбы), поэтому у всех перестают работать приборы: Титаны (как переносные, так и стационарные) и NLAW (Аламут, простой как топор продолжает работать). Не работают также ночное видение и теплаки. (Есть мысль сделать недоступной технику и авиацию, а также ПВО, но это сложнее - поэтому в планах).
Для того, чтобы ликвидировать РЭБ на точку выдвигается группа. В группе должен быть минимум один инженер, он должен запустить генератор, похитить данные настройки РЭБ и узла связи, и взорвать станцию.
В планах еще сделать так, чтобы для этого надо было подвести горючее на вертушке, чтобы запустить генератор. Но это в планах, смогу попробовать сделать если миссию одобрят.
После ликвидации РЭБ на острове все продолжает работать в штатном режиме.
Миссия с допкой в файле.
Тестировочный файл прилагается (одна допка работает - эта, и нет противника на допке), поэтому чтобы сделать из него полноценную миссию надо раскомментить:

в файле: \mission\side\missions\poweron.sqf
//_enemiesArray = [sideObj] call QS_fnc_SMenemyEAST;

в файле: \mission\side\missions\missionControl.sqf
в _missionList = [ убрать признаки комментария: "/_" и "_/" напротив остальных миссий

Файл приложен.
[co47_ADR_Blue_Shark.Altis.zip](https://github.com/TEHGAM/ADR/files/190879/co47_ADR_Blue_Shark.Altis.zip)

**Comment by AlexVDem** [comment]
Файл миссии поправил чуть:
- более корректное отображение результата, когда миссия выполнена инженером
- добавил авто на точку миссии, поправил ситуацию когда миссия создается некорректно и тут же становится провалена
- одно из авто - ключевое для выполнения мисии, его нельзя уничтожать
- добавил немного инфо в описание задания, которое появляется в момент начала миссии
- добавил взрыв базы помощнее

Файл в корневом посте обновил.

**Comment by RK3QRZ** [comment]
Однозначно против ограничения на выполнение доп. задания только инженером.

**Comment by AlexVDem** [comment]
Поправил файл миссии, теперь миссия может выполняться любым игроком.
Файлы, которые были изменены по сравнению с оригинальным сценарием:

 \mission\side\missions\missionControl.sqf - добавлены комментарии на отключение остальных допок, комментарии надо убрать.

\mission\side\missions\poweron.sqf - добавлен новый файл доп. миссии, чтобы на миссии появился противник, надо раскомментить строку //_enemiesArray = [sideObj] call QS_fnc_SMenemyEAST;

mission\side\actions\getpower.sqf - добавлен файл выполнения задания, когда входим в здание узла РЭБ и подходим к ноуту

файл сценария игры в корневом посте обновил с учетом этих правок

**Comment by AlexVDem** [comment]
Ребята, из разговора в TS понял, что миссию надо доработать. Напишите конечный список, что надо доделать.

**Comment by Noart537** [comment]
Ограничение действия эми в радиусе 4-5 км от точки доп миссии.
И ПНВ не стоит отключать. Боты нас будут видеть, мы их нет).

**Comment by RK3QRZ** [comment]
Теплаков наверное а не ПНВ. Учитывая то  что боты и так супер меткие и убивают с одной пули да еще и с разворота, считаю отключение теплаков перегибом.

**Comment by ToxaBes** [comment]
Насколько я понял - суть миссии в том что пока работает РЭБ мы как слепые котята на основе. И поэтому ее нужно выполнить в первую очередь. Т.е. это не доп. миссия а полноценная приоритетная цель как Артиллерия или Пусковые установки (да я в курсе что сейчас она оформлена просто как допка).

Если убрать то что вы предлагаете - теряется ее суть. Зачем ехать выполнять ее если РЭБ работает только в радиусе 4-5х км и на основе все работает? (для справки: современная РЭБ работает на 300км). РЭБ должна накрывать весь остров. Это все равно что если бы у нас появилась "Приоритетная цель: Пусковые Установки" - но сбивали бы они все живое только в радиусе 4 км...

Далее, теплаки/ПНВ:
1) на сервере чтобы получить ночь надо хорошо попросить админов
2) если таки сделали ночь, то можно пользоваться фонариками/осветительными ракетами - недавно проходили так миссию от Рембо, очень даже можно играть без ПНВ.

Подумайте еще раз над этими ограничениями - очень легко сделать из действительно интересной идеи (а полноценную миссию типа "Приоритетная цель" - до Алекса не придумывал никто) обычную допку.

**Comment by AlexVDem** [comment]
Тоха - ты попал точно в цель. Именно это я и хотел, сложное задание в условиях когда нет преимуществ над ботами в виде титанов и теплаков. Да, я знаю, что запретов на пользование чем то на сервере нет. Но в том и интерес, т.к. в выполнении задачи будут заинтересованы все игроки на сервере, а не только группа из тех, кто регулярно допки выполняет. Тем более, это временно, до выполнения миссии.

**Comment by ToxaBes** [comment]
Предлагаю:
1. Переделать миссию из доп. задания в приоритетную цель (переделка займет минут 10).
2. РЭБ накрывает весь остров.
3. Во время работы РЭБ не работает все что предложил Алекс в первом посте.

**Comment by RK3QRZ** [comment]
(для справки: современная РЭБ работает на 300км)
Дай ссылку на официальный источник где это подтверждается. И где написано что РЭБ может подавлять современные ПТРК? 

Т.е. это не доп. миссия а полноценная приоритетная цель как Артиллерия или Пусковые установки (да я в курсе что сейчас она оформлена просто как допка).
Если за это подразумевается награда, то это уже допка, а не приоритетная цель.

Далее, теплаки/ПНВ:
1) на сервере чтобы получить ночь надо хорошо попросить админов
2) если таки сделали ночь, то можно пользоваться фонариками/осветительными ракетами - недавно проходили так миссию от Рембо, очень даже можно играть без ПНВ.
Еще раз хочу всем напомнить, что сервер ориентирован для новичков. Такие сложности на мой взгляд ни к чему. 

Тоха - ты попал точно в цель. Именно это я и хотел, сложное задание в условиях когда нет преимуществ над ботами в виде титанов и теплаков.
Учитывая то что боты на допках зверские, то теплак это не преимущество. И запрета на использование теплака согласно разработанной и утвержденной всеми администраторами концепции на сервере нет.

**Comment by ToxaBes** [comment]
>Дай ссылку на официальный источник где это подтверждается. И где написано что РЭБ может подавлять современные ПТРК?

http://rg.ru/2015/09/08/kret-site.html:
..."новейшие мобильные системы РЭБ. Это комплексы семейства "Красуха", способные на дальности до 300 километров обнаруживать и эффективно подавлять бортовые РЛС самолетов противника, препятствуя обнаружению и обстрелу целей."

подробнее о Красухе: https://ru.wikipedia.org/wiki/%D0%9A%D1%80%D0%B0%D1%81%D1%83%D1%85%D0%B0_(%D0%BA%D0%BE%D0%BC%D0%BF%D0%BB%D0%B5%D0%BA%D1%81_%D0%A0%D0%AD%D0%91)
..."Назначение комплекса — прикрытие командных пунктов, группировок войск, средств ПВО, важных промышленных и административно-политических объектов. Комплекс анализирует тип сигнала и воздействует на РЛС противника помеховым излучением. Осуществляют подавление спутников-шпионов, наземных радаров и авиационных систем АВАКС"...
..."Дальность действия комплекса «Красуха-4» оценивается в 150—300 километров."...

>И где написано что РЭБ может подавлять современные ПТРК?

ну это будущее, уже сейчас глушат спутники, беспилотники, самолеты, системы наведения в различных комлпексах. Почему бы не глушить Титаны? (понятно что Аламут не заглушишь)

Даже стационарные комплексы, стоящиие в Крыму (которые старше нас с тобой) уверенно глушат все вплоть до побережья Турции, а это ~300км.

>Если за это подразумевается награда, то это уже допка, а не приоритетная цель.

По своей сути это приоритетная цель, по текущему исполнению - допка. Я думаю Алекс сам решит что из это сделать, либо то либо другое.

>Еще раз хочу всем напомнить, что сервер ориентирован для новичков. Такие сложности на мой взгляд ни к чему.

В чем сложность выполнить ее днем? Официально на сервере нет ночи. Ночь делают админы, очень редко и только когда много игроков хотя поиграть ночью. Без этих ограничений теряется сама идея этой миссии.
Поставь пожалуйста этот вопрос на админское голосование.

**Comment by ToxaBes** [comment]
@AlexVDem - потестил миссию, нашел несколько моментов:
1. Зенитка появилась взорваной на ровном месте, ничего ей не мешало (отключай технике урон при создании и включай в конце всех манипуляций с ней)
2. Один из камазов появился в здании (проверяй чтобы техника не ресалась в твоих же зданиях - респ техники в стандартных зданиях на карте - норма :) )
![1](https://cloud.githubusercontent.com/assets/3309152/14061582/b66a31de-f394-11e5-86e1-1d7939a8ff65.jpg)
3. Текущее ограничение  1км от респа, увеличь хотя бы до двух а то я прямо на взлетке выполнял, часть ботов/ифриты пытались убежать/уехать на респ.
4. Проверяй удаление техники после миссии, оно кривое в стандартном варианте, посмотри как сделано в конвое (та же проблема была).
![2](https://cloud.githubusercontent.com/assets/3309152/14061585/bef20da4-f394-11e5-926e-c817264d1082.jpg)
5. Сейчас получается если инженер сделал то 2 награды (танк + наградная техника). Если не инженер, то просто наградная.
![3](https://cloud.githubusercontent.com/assets/3309152/14061594/ed27bc82-f394-11e5-96ae-d47c074c5309.jpg)
Может изменить на: если инженер выполнил то наградная, иначе "спасибо, молодцы, возвращайтесь на базу"?

**Comment by AlexVDem** [comment]
Насчет машин - я спецом не удалял их, это машина ремонтная и заряжания, мини-награды техникам за выполнение. 
Насчет остальных моментов - спасибо, постараюсь поправить.

**Comment by RK3QRZ** [comment]
За красуху  я знаю давно, только она не подавляет ПТРК :). Поэтому я и просил дать ссылку на РЭБ которая подавляет ПТРК.
Я против подавления титанов на всей карте. Сейчас на допках одни и те же люди, не всем нравятся допки. Кто-то хочет играть только на основе, пусть сами выбирают где им воевать.
По поводу отключения теплака и ПНВ:
Это противоречит концепции сервера. Для новичков это будет сложно, их и с теплаками убивают на раз-два. Не нужно думать только о себе, у нас полно новеньких игроков для которых это уже жесткач.

**Comment by RK3QRZ** [comment]
Пусть Ноарт выносит тогда вопрос на голосование, потому что это не просто допка, а допка которая противоречит концепции сервера и подразумевает не малые ограничения. В таком виде доп. задания, я буду голосовать против.

**Comment by AlexVDem** [comment]
> Один из камазов появился в здании (проверяй чтобы техника не ресалась в твоих же зданиях - респ техники в стандартных зданиях на карте - норма :) )
Поправил, теперь здание поста появляется не ближе чем 25 метров, должно хватит места для респа авто РЭБ

> Текущее ограничение 1км от респа, увеличь хотя бы до двух а то я прямо на взлетке выполнял, часть ботов/ифриты пытались убежать/уехать на респ.

Поправил - 3 км. должно быть достаточно. Подумал, может быть сделать не дальше 6 км. от базы, или не дальше 2 км. от основы, чтобы не далеко было ездить или чтобы был стимул с основы переключиться на новую приоритетную задачу как это например сделано с артой?

> Проверяй удаление техники после миссии, оно кривое в стандартном варианте, посмотри как сделано в конвое (та же проблема была).

Тут я спецом не удалял машины. Почему - написал чуть ранее

> Может изменить на: если инженер выполнил то наградная, иначе "спасибо, молодцы, возвращайтесь на базу"?

Если админы не против, так и сделаю.

**Comment by ToxaBes** [comment]
>Поправил - 3 км. должно быть достаточно. Подумал, может быть сделать не дальше 6 км. от базы, или не дальше 2 км. от основы, чтобы не далеко было ездить или чтобы был стимул с основы переключиться на новую приоритетную задачу как это например сделано с артой?

Подожди результатов голосования. Если админы отклонят вариант с отключением ПНВ/теплаков/Титанов, то это будет обычная допка, ничем не отличающаяся от тех которые недавно отключили (в стиле приехать и нажать на кнопку). Если примут этот вариант - тогда имеет смысл доработать до полноценной Приоритетной цели: недалеко от основы, награда только если инженером выполнили.

У нас 7 допок, 7 спецопераций и всего 2 приоритетные цели. было бы здорово иметь 7 интересных приоритных целей ) суть которых в усложнении взятии основы при их игнорировании.

Я бы хотел включить "Узел связи и РЭБ" в свою миссию в виде одной из Приоритеных целей с небольшими доработками если ты не против.

**Comment by AlexVDem** [comment]
> Подожди результатов голосования. 
Ok.

> Я бы хотел включить "Узел связи и РЭБ" в свою миссию в виде одной из Приоритеных целей с небольшими доработками если ты не против.
Конечно, я не против.

Поправил еще миссию.
Теперь для выполнения миссии надо сначала починить генератор, а затем уже в здании узла связи скачать данные. Что делать в этом промежутке (оборона?) я еще не придумал, подождем результатов голосования. :)
Файл в корневом посте обновил.

**Comment by tym32167** [comment]
Всем привет. 
Как идея звучит неплохо. Поиграть в это я не могу, потому постараюсь оставить обратную связь по описанию. 
* Для начала сверьте пожалуйста логику миссии [с нашей концепцией](http://1drv.ms/1Lu3NJK). На форуме она размещена [тут](http://www.tehgam.com/showthread.php?t=1718). Особенно обратите внимание, соответствует ли допка назначению сервера и проходит ли критерии изменений.
* Я давненько не играл, но есть такая мысль: сейчас те, кто любит делать допки, вполне себе делают их независимо от игроков на основе. Завязывая их вместе, мы можем получить такой эффект, когда парням на основе проще зафейлить допку, чтобы иметь возможность дальше играть с плюшками, но парням на допке это не понравится. Прошу проверить, будет ли такой конфликт интересов.
* Также, если я правильно понял, отключая теплаки и пнв, ночью снайперам и пехотным снаперам на допке и вообще на карте будет нечего делать. Если же ночь на сервере радкость - то зачем отключать ПНВ? Если отключать и пилотов, то будет совсем печаль. Прошу проверить, проблема ли это вообще?
* Нужно проверить, что допку в состоянии сделать один игрок. Ночью и ранним утром у нас на сервере народа мало, хочется, чтобы даже у одного игрока была возможность допку закончить.

Кстати говоря, у нас уже есть допка, которая связана с основной - это артиллерия. Однако, арта не ограничивает никак геймплей и не вводит никаких условий относительно класса игрока, потому с ней вроде проблем нет.

Что касается моего личного мнения. Мне кажется,  что миссия должна быть интересной, но, я бы выкладывал её не всю сразу. Например, дать возможность выполнить миссию не только инженером, просто инженер это сделает быстро, а другой класс - медленно (возможно я и  не прав, у нас есть допка с похищением вертолета, где без пилота не обойтись. Эта допка популярна?). Также действие допки ограничить радиусом, максимум километра 3, куда не должна входить ни база, ни основа. И спавнить допку только в светлое время суток. Можно было бы погонять миссию в таком виде, и поглядеть результаты.
Если очень хочется действия допки на основу, то её и спавнить стоит на основе, как одну из целей (типа вышки). 
Что касается реализма. Ребята, второй сервер - не хардкор. Потому логика, что, например, отключая теплак надо отключать и ПНВ, может не работать в миссии и это не страшно.

**Comment by tym32167** [comment]
По поводу голосовалки, насколько мне известно, @Noart537 на сессии, а кроме него голосовалку никто не сделает.

**Comment by RK3QRZ** [comment]
Предлагаю:
1. Ограничить действия РЭБ в пределах триггера доп. задания + 5 км.
2. Оставить ПНВ и теплак. В пределах действия РЭБ отключить теплак только в техники (если допка только для пехоты) если это возможно технически, у пехоты теплаки оставить.
3. Уровень интеллекта и меткость ботов повысить до уровня как на спец. операциях у Тохи.
4. По поводу выполнения: инженер мгновенно выполняет обычный пехотинец 2-3 минуты.
    награда: идея предложенная Тохой давать награду только в случае выполнения задания инженером не очень хорошая. У нас два понятия 1. допка выполнена, 2. допка провалена. За выполнение допки награду нужно давать в любом случае и не важно кто ее выполнил инженер или обычный пех.
P.S. Алекс если ты хочешь как-то напрячь инженера придумай что-нибудь для основы. Ведь основная масса игроков именно там. Я думаю что все будут только за если мы как-то разнообразим основную миссию. Для допки такое не очень катит, так как на допках всегда очень мало игроков, ты и сам это знаешь.

**Comment by RK3QRZ** [comment]
Может быть вообще стоит подумать над тем как интегрировать это задание в основную миссию.
