### ISSUE TITLE
Респавн техники

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#451]
В скрипт респавна техники, добавить очистку груз отсека и пополнение бк.
Сейчас у нас оставленная техника исчезает и появляется на базе с содержимым, чем была загружена. Оставленная боевая техника появляется с тем бк, с которомы исчезла (переместилась на место респавна).

**Comment by AlexVDem** [comment]
Насчет очистки грузового отсека - я всегда думал, что это не баг, а фича, причем очень хорошая фича. Допустим грузил ты страйдер полчаса всяким, приехал на точку, тебя убили, а страйдер респанулся опять на базе со всем содержимым, и грузить повторно ничего не надо, все уже есть. Очень удобно, сел и поехал. Если кому надо взять технику и грузить по своему, то достаточно нажать очистку грузового отсека. Просьба оставить эту фичу (баг?) ;)
Насчет БК - согласен.

**Comment by Noart537** [comment]
Сейчас она перемещается на место респавна, думаю проще будет чтобы она удалялась, и появлялась новая на месте респавна.

**Comment by Noart537** [comment]
Добавить таймер 5 мин для боевой наземной техники. Если нет игроков в радиусе 300 метрах, то ждать 5-10 мин, потом респавн.
