### ISSUE TITLE
Миссия "Конвой" вешает сервер в случае подрыва машины с зарядом.

### ISSUE THREAD

**Issue by AlexVDem** [TEHGAM/ADR#452]
Если взорвать машину с ядерным зарядом (подрывным пакетом, беспилотником или еще как то), то сервер иногда зависает. Это наблдалось в то время когда таймер уже был активирован.  Алгоритм воспроизведения ошибки непонятен, но она случается.
Пока это наблюдалась несколько раз, не всегда но довольно часто.

**Comment by ToxaBes** [comment]
Сервер зависает периодически и без подрыва ядерного заряда )
Нужно узнать точное время когда это призошло и поднять логи у админов сервера. Пока считаю что это совпадение.

**Comment by ToxaBes** [comment]
Проверил логи в момент последнего "падения" сервера - ошибок нет, сам сервер продолжил работать как обычно, похоже что отвалилась передача данных между сервером и клиентами внутри самой Армы. 
Т.е. это одно из периодических "зависаний" сервера, при которых он виден как работающий, с какими-то игроками, а по факту там никого нет.
Также попробовали воспроизвести этот баг подорвав машину с ТЯЗ - все сработало верно.
Со стороны кода миссии исправлять нечего - похоже на очередной фирменный косяк от БИСов. Пока тикет закрываю, продолжаем наблюдение.
