### ISSUE TITLE
Оператор БПЛА может пополнять боеприпасы из Арсенала на любом расстоянии

### ISSUE THREAD

**Issue by ToxaBes** [TEHGAM/ADR#453]

**Comment by Noart537** [comment]
Возможно нужно добавить проверку еще какуюнибудь проверку при обращении к ящику.

this addAction [""<t color='#F44336'><img image='\a3\ui_f\data\gui\Rsc\RscDisplayArsenal\spacearsenal_ca.paa' size='1.0'/> Снаряжение</t>"",""scripts\VAS\open.sqf"",[],10,true,true,'((vehicle player) == player) && ((player distance _target) < 2)'];

https://github.com/TEHGAM/ADR/blob/master/co47_ADR_Blue_Shark.Altis/mission.sqm#L1430

**Comment by ToxaBes** [comment]
Да, думаю будет достаточно проверять чтобы игрок не был подключен к UAV, например вот так:
```sqf
this addAction ["" Снаряжение"",""scripts\VAS\open.sqf"",[],10,true,true,'((vehicle player) == player) && ((player distance _target) < 2) && isNull (getConnectedUav player)'];
```
не тестировал но должно сработать. Нужно в 3х местах добавить:
https://github.com/TEHGAM/ADR/blob/master/co47_ADR_Blue_Shark.Altis/mission.sqm#L1430
https://github.com/TEHGAM/ADR/blob/master/co47_ADR_Blue_Shark.Altis/mission.sqm#L2828
https://github.com/TEHGAM/ADR/blob/master/co47_ADR_Blue_Shark.Altis/mission.sqm#L3694

**Comment by ToxaBes** [comment]
Сделал немного иначе, проверяй.
