### ISSUE TITLE
Предложение настроить скрипт генерации доп. миссий и приоритетных целей.

### ISSUE THREAD

**Issue by AlexVDem** [TEHGAM/ADR#454]
Предложение настроить скрипт генерации доп. миссий и приоритетных целей таким образом, чтобы одна и та же задача не появлялась 2 раза подряд. Хотя бы на 3-й раз. 
Иначе, в связи с тем, что порезали количество доп. миссий, появляется 2 раза подряд задача "Уничтожить артиллерию", "Зенитные установки" и пр. Оно и до этого так иногда было, но сейчас это стало происходить чаще. Не очень интересно.

**Comment by Noart537** [comment]
Поддерживаю

**Comment by AlexVDem** [comment]
Хм, странно, только сегодня с утра 2 раза подряд была миссия Склад.

**Comment by Noart537** [comment]
Пофиксил, но это будет в версии 4.4.3, а сейчас на сервере 4.4.2 ;)
