### ISSUE TITLE
Иногда перестают вызываться модули.

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#458]
Иногда не объявляется глобальная переменная.publicVariable "BACO_ammoSuppAvail"

**Comment by ToxaBes** [comment]
Перед проверкой переменной добавь проверку на ее существование:
```sqf
waitUntil {sleep 1; !isNil "BACO_ammoSuppAvail";};
```

**Comment by Noart537** [comment]
sleep 1; это частота проверки?

**Comment by ToxaBes** [comment]
да

**Comment by Noart537** [comment]
Осталось добавить проверку перед созданием нового модуля, если на маркере "Ammo_Supply_drop" уже стоит модуль, то его надо удалить. Есть желающие помочь с этим? =)

**Comment by ToxaBes** [comment]
```sqf
_modules = ["B_Slingload_01_Fuel_F", "B_Slingload_01_Medevac_F", "B_Slingload_01_Repair_F", "B_Slingload_01_Ammo_F", "Land_Pod_Heli_Transport_04_fuel_F", "Land_Pod_Heli_Transport_04_medevac_F", "Land_Pod_Heli_Transport_04_repair_F", "Land_Pod_Heli_Transport_04_ammo_F", "Land_Pod_Heli_Transport_04_bench_F", "Land_Pod_Heli_Transport_04_covered_F"];
_objects = nearestObjects [(getMarkerPos "Ammo_Supply_drop"), _modules, 100];
{
	deleteVehicle _x;
} forEach _objects;
```

**Comment by Noart537** [comment]
Спасибо!

**Comment by Noart537** [comment]
При одновременном скидывании с троссов двух модулей. Раскрытие парашютов проходит норм, у одного из модулей парашют остался при приземлении. (тестировалось до исправления ошибки с локальной переменной в глобальном пространстве). 
При сбрасывании одного модуля, такой проблеммы нет.
Пока оставляю на тестировании. Как будет время, протестирую ещё.
