### ISSUE TITLE
Объединить одинаковые по смыслу допки в один файл.

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#462]
`	"HQcoast",
	"HQfia",
	"secureRadar",
	"HQresearch",
	"HQind",
	"secureChopper",
`

**Comment by tym32167** [comment]
зачем? Не надо!

**Comment by tym32167** [comment]
это ж разные допки

**Comment by Noart537** [comment]
У них разница только в ноутбуке, ящике в\на бункере и ангар с вертолетом. Смысл один и тотже. заложить взрывчатку. Они у нас сейчас отключены большинство. Считаю что их будет лучше объединить в один файл и случайным образом запускать. В конечном счете Задания будут разными, а цель одина и таже.

**Comment by Noart537** [comment]
Там код создания одинаковый почти, разница только в объектах.

**Comment by tym32167** [comment]
а, понял. Тогда, может, будет лучше вынести общий скрипт отдельно и его вызывать, с указанием, чего там надо взорвать? Так можно? Чтобы эти объекты просто передавать как параметры.

**Comment by Noart537** [comment]
Можно и так.

**Comment by tym32167** [comment]
думаю, это было бы лучше. Тогда можно было бы рандомом указывать, что нужно хакнуть и чем. Типа вызываешь просто с ангаром и ящиком - у тебя ящик в ангаре. Вызываешь с ноутбуком и зданием - у тебя ноут в здании. Ну и тд.

**Comment by Noart537** [comment]
Реализуется в #489
