### ISSUE TITLE
Изменения по выдаче наградной техники

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#463]
Создать проверку для появления наградной техники. (Если такая техника уже существует, то создавать другую)

Например:
За первую допку дали танк "Кума"
За последующие допки танк "Кума" не будет выдаваться, пока он не будет уничтожен.
и т.д.
Копии техники не будут создаваться, пока оригинал жив.

**Comment by tym32167** [comment]
Не забудь учесть ситуацию, когда вся награда техника уже выдана

**Comment by tym32167** [comment]
И я тут подумал, так же можно и читерить. Выбить все, а использовать только танк и самолет. Потерял танк, выполнил допку, получил танк

**Comment by malashin** [comment]
Лучше не учитывать уже выданную технику, это сложно и затратно.

Просто делается список всех наград и рандомно выдается из него одна техника, после этого она из списка вычеркивается. Когда весь список будет пустой, он полностью востанавливается в изначальное состаяние.

**Comment by tym32167** [comment]
@malashin согласен, так уже не почитеришь

**Comment by Noart537** [comment]
:+1:
