### ISSUE TITLE
Ошибки в логах

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#464]
После завершения основной миссии в логах ошибки 
```
14:53:38 Error in expression <Each (units _obj);
} else {
if (!isNull _obj) then {deleteVehicle _obj;};
};
};>
14:53:38   Error position: <_obj) then {deleteVehicle _obj;};
};
};>
14:53:38   Error Undefined variable in expression: _obj
14:53:38 File mpmissions\__cur_mp.Altis\functions\fn_AOdelete.sqf, line 35
14:53:38 Error in expression <sArray select _c;
_isGroup = false;
if (_obj in allGroups) then {_isGroup = true>
14:53:38   Error position: <_obj in allGroups) then {_isGroup = true>
14:53:38   Error Undefined variable in expression: _obj
14:53:38 File mpmissions\__cur_mp.Altis\functions\fn_AOdelete.sqf, line 28
```

**Comment by ToxaBes** [comment]
Ошибкой является весь код в строках с 21 по 37 (fn_AOdelete.sqf). Этот код пытается использовать объекты которые уже могли быть удалены в строках 1-19. Рекомендую попробовать вместо fn_AOdelete.sqf вот [это](https://github.com/ToxaBes/ADR-Spec-Ops/blob/master/co30_ADR_Spec_Ops.Altis/functions/fn_TBdeleteObjects.sqf).

**Comment by Noart537** [comment]
Хорошо, как доберусь до этой задачи, попробую.

**Comment by Noart537** [comment]
```
16:14:43   Error position: <>
16:14:43   Error Local variable in global space
16:14:43 Error in expression <>
16:14:43   Error position: <>
16:14:43   Error Local variable in global space
16:14:43 Error in expression <>
16:14:43   Error position: <>
16:14:43   Error Local variable in global space
16:14:43 Error in expression <>
16:14:43   Error position: <>
16:14:43   Error Local variable in global space
16:14:43 Error in expression <>
16:14:43   Error position: <>
16:14:43   Error Local variable in global space
16:14:43 Error in expression <>
16:14:43   Error position: <>
16:14:43   Error Local variable in global space
16:14:43 Error in expression <>
16:14:43   Error position: <>
16:14:43   Error Local variable in global space
16:14:43 Error in expression <>
```
Косяк при вызове модулей. буду разбираться.

**Comment by Noart537** [comment]
Осталось найти из-за чего ошибка
```
16:47:58 Update of nonlocal object 2:707 called
16:47:58 Update of nonlocal object 2:707 called
16:47:58 Update of nonlocal object 2:707 called
16:47:58 Update of nonlocal object 2:707 called
16:47:59 Update of nonlocal object 2:707 called
16:47:59 Update of nonlocal object 2:707 called
16:47:59 Update of nonlocal object 2:707 called
16:47:59 Update of nonlocal object 2:707 called
16:47:59 Update of nonlocal object 2:707 called
16:47:59 Update of nonlocal object 2:707 called
16:47:59 Update of nonlocal object 2:707 called
16:47:59 Update of nonlocal object 2:707 called
16:47:59 Update of nonlocal object 2:707 called
16:47:59 Update of nonlocal object 2:707 called
```

**Comment by ToxaBes** [comment]
>Error Local variable in global space

проверь все переменные файлы с нижним подчеркиванием, объяви их в начале файла с помощью 
```sqf
private ["_someVar1","_someVar2"];
```

>Update of nonlocal object 2:707 called

Это не совсем ошибка. Зевсом ничего не спавнили?

**Comment by Noart537** [comment]
нет, сегодня админы еще не бывали на сервере, а уже 70мб логов. За сутки эта ошибка спавнит 1-1,5 ГБ логов. Скорее всего влияет на фпс.

**Comment by ToxaBes** [comment]
Сколько времени запущен сервер? Попробуй перезагрузить его, сообщение может исчезнуть (и появится еще через пару перезагрузок).

У меня такое сообщение появляется 1 раз на 20 перезапусков примерно.

**Comment by Noart537** [comment]
Запущен в  	17.04.2016 15:33:17 
ошибка появилась в 15.47.

**Comment by ToxaBes** [comment]
https://forums.bistudio.com/topic/113242-answered-update-of-nonlocal-object/ - это еще со второй Армы идет

ну и на сегодня ничего не поменялось: https://forums.bistudio.com/topic/189893-update-of-nonlocal-object-netid-called/

кстати багтрекер бисов лежит уже 2 месяца, нет багетрекера - нет багов.

**Comment by Noart537** [comment]
да я читал эти темы, советуют -nologs прописать. Но это не выход) Хочется найти в чем причина)

**Comment by ToxaBes** [comment]
[Отсюда](http://webcache.googleusercontent.com/search?q=cache:OE6cDMsMuAEJ:feedback.arma3.com/bug_revision_view_page.php%3Frev_id%3D24022+&cd=2&hl=en&ct=clnk): 
06-09-2013
•Fixed: Object variables were not assigned correctly when BIS_fnc_objectVar was called on non-local object. This affected for example respawn positions and communication menu items.

**Comment by Noart537** [comment]
Новая ошибка связанная с артой
```
if (!isNull _unit) then {
_targetPos = getPos _unit;>
 0:54:27   Error position: <_unit) then {
_targetPos = getPos _unit;>
 0:54:27   Error Undefined variable in expression: _unit
 0:54:27 File mpmissions\__cur_mp.Altis\mission\side\missions\priorityARTY.sqf, line 154
 0:54:30 Server: Object 8:14 not found (message Type_119)
 0:54:30 Error in expression <unt switchableUnits)));
};
```

**Comment by Noart537** [comment]
Если один игрок на сервере, то спамит ошибку 
`Group B Alpha 2-2 (0x47547100) - network ID 2:8185
 6:52:28  - no leader`

**Comment by Noart537** [comment]
Вызваны использованием зевса. Расставлением какойлибо техники, или объектов, которые синхронизируются с зевсом. Больше объектов видимых зевсу - больше текста в секунду.
Видимо это влияет на фпс хоть и немного. При создании миссий от зевса. (могу ошибаться)
```
19:40:34 Server: Object 3:48 not found (message Type_91)
19:40:34 Server: Object 3:49 not found (message Type_91)
19:40:34 Server: Object 3:26 not found (message Type_91)
19:40:34 Server: Object 3:70 not found (message Type_119)
19:40:36 Server: Object 18:21 not found (message Type_119)
19:40:36 Server: Object 18:30 not found (message Type_119)
19:40:36 Server: Object 3:71 not found (message Type_91)
19:40:36 Server: Object 3:70 not found (message Type_91)
19:40:36 Server: Object 4:48 not found (message Type_91)
19:40:36 Server: Object 18:29 not found (message Type_119)
19:40:37 Server: Object 3:71 not found (message Type_119)
19:40:38 Server: Object 18:20 not found (message Type_119)
19:40:40 Server: Object 19:13 not found (message Type_119)
19:40:40 Server: Object 19:12 not found (message Type_119)
19:40:40 Server: Object 13:86 not found (message Type_119)
```

**Comment by ToxaBes** [comment]
Object 3:71 not found - ошибки движка армы. Вылезают даже если не использовать зевс.
