### ISSUE TITLE
Терминалы на задании "Гроздья гнева".

### ISSUE THREAD

**Issue by AlexVDem** [TEHGAM/ADR#468]
Предлагаю их сделать с возможностью получения урона (и провала миссии по этой причине). Чтобы не было соблазна пригнать на точку ядерный заряд, взорвать все, и потом бегать по пустому городу и искать терминалы в развалинах.

**Comment by Noart537** [comment]
Либо сделать зоны-маркеры радиусом 50м, в которых находится терминал. Искать по всему городу уже никто не хочет). Онлайн вечером 5-10 чел и из них 2-3 чел на допке,  обыскивать весь город им долго, поэтому и взрывают. 
Маркеры могут появляться, когда к ним подходят на 150-200 м.

**Comment by malashin** [comment]
Можно еще в мелком радиусе (метров 50-100) делать поиск терминалов, брать самый ближний и раз в 15-30 секунд сообщать игроку, что обнаружен терминал на таком-то расстоянии и звук моушнтрекера из Чужих :)

**Comment by Noart537** [comment]
=)

**Comment by ToxaBes** [comment]
Если в зоне больше 30 зданий то рисовать 3 маркера радиусом 30 метров внутри которых будут терминалы.  Центр маркера не совпадает с позицией терминала.

**Comment by AlexVDem** [comment]
Лучше сделать так, появляется первый маркер - взламываем, появляется второй - взламываем, появляется третий... Это будет логично, сохранит до конца интригу где расположены терминалы, заставит зачищать город последовательно, надо будет обследовать весь населенный пункт, а не бежать сразу к ближнему.  В то же время будет понятно, где уже не стоит искать.

**Comment by ToxaBes** [comment]
@AlexVDem  - отличная идея. Так и сделаю: https://github.com/ToxaBes/ADR-Spec-Ops/issues/46
