### ISSUE TITLE
Разрешить аламуты всем бойцам

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#470]
Разрешить всем бойцам брать аламуты. С вводом стамины не каждый боец сможет взять аламут, так как придется тогда пожертвовать другим б.к и стаминой. Аламут с одним выстрелом практически бесполезная штука, а так вроде мы удовлетворим просьбы и никакого дисбаланса.

**Comment by Horizon1959** [comment]
Ничем они не жертвуют, только нагружаются больше. Тащат тяжёлый пулемёт, короба к нему, да ещё и гранатомёт. Сейчас командир отделения может таскать, так?

**Comment by Noart537** [comment]
Птшник только

**Comment by Horizon1959** [comment]
@Noart537 т.е. PCML и Аламут уже успели запретить командирам отделений?

**Comment by Horizon1959** [comment]
@Noart537 извини, спутал тред со SpecOps.
