### ISSUE TITLE
Добавить на сервер ключ для аддона Enhanced Movement

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#472]
Ввести необязательный аддон Enhanced Movement http://www.armaholic.com/page.php?id=27224 позволяющий перелезать через ограды и стены.

**Comment by ToxaBes** [comment]
Как видят процесс перелезания через стену те игроки у которых мод не включен? Тупой телепорт или они видят всю анимацию просто не могут повторить?

**Comment by Noart537** [comment]
Сегодня вечером будем проверять, отпишу результат.

**Comment by Noart537** [comment]
Игрок, который перелезает через стену, сначала появляется на стене на 1-2 сек, потом за ней.

**Comment by ToxaBes** [comment]
те стоит на стене ногами в полный рост?

**Comment by Noart537** [comment]
ага

**Comment by ToxaBes** [comment]
Я так понимаю боты тоже увидят игрока в полный рост на заборе ) 1-2 секунды для бота у которого мишень видна в полный рост... а потом игроки будут жаловаться - "я как ниндзя перелезал через забор а он все равно меня убил - надо что-то с этим делать!!!!"...

**Comment by 12st** [comment]
ну это и логично, что перелезая ты  становишься лёгкой мишенью.

**Comment by ToxaBes** [comment]
Одно дело перелезать обняв забор (так делает мод для тех у кого он включен) и совсем другое дело стоять на заборе в полный рост (так для всех у кого нет мода, в том числе и для ботов).

**Comment by ToxaBes** [comment]
Хотя это конечно выбор игрока -  если прям так надо лезть через забор, вперед.

**Comment by AlexVDem** [comment]
Клевая штука, для снайпера полезная.
