### ISSUE TITLE
Временно снизить шанс появления спецоперации рыба меч

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#473]
В виду не популярности спецоперации "Рыба меч" решили пока уменьшить шанс появления этой операции. 
Альтернативное решение, добавить возможность выполнения с суши.

**Comment by 12st** [comment]
Возможность выполнить с суши уже есть
https://github.com/ToxaBes/ADR-Spec-Ops/issues/12

**Comment by AlexVDem** [comment]
Я вообще хотел предложить сделать лимит времени на выполнение доп. миссии. Например если в течении получаса в радиусе 3 км. не появляется игрока, миссия пропадает и меняется на новую. Если игрок появился там, прошел в круг зоны мисии, погиб и через полчаса там не появлялось новых игроков - миссия считается проваленной. Ну, кроме приоритетных заданий, они висят пока не выполнены.
Это позволит менять миссии без админов (достаточно подождать), и как то повысит интерес, если текущая миссия не нравится.
Кстати, предлагаю приоритетное задание "Узел связи" внедрить на второй сервер.

**Comment by RK3QRZ** [comment]
Полностью поддерживаю Алекса!
1. Ракеты ПП давно нужно было убрать, это читерская вещь. Алекс правильно написал, что достаточно нагрузить полный страйдер ракет и в одиночку вынести всю допку. Я неоднократно это наблюдал на сервере, как жестко выносили допки и зевс миссии с помощью ПП ракет. Сравнение ПП ракет с стационарным гранатометом не корректное. ПП ракетами можно работать как минимум в 2 раза дальше. В ТС были неоднократные случаи когда мы ругались из-за того что zed выносил допки тем самым не давая нам поиграть пехотой.
Предлагаю:
а. запретить ПП ракеты или сделать ограничение, чтобы в любую технику можно было загрузить не более 5 ракет.

2. По поводу найтсталкера тоже не вижу особых причин для паники. Такие прицелы существуют в реальности. Раньше на сервере RW2 прицел был с отключенным тепловизором. Никаких проблем не было, никто ботов не нагибал.
Предлагаю:
а. вернуть прицел найтсталкер только для снайперов/пехотных снайперов
б. отключить тепловизор в прицеле

**Comment by RK3QRZ** [comment]
Поддерживаю решение снизить шанс появления этой допки. Допка крайне не популярная. Ее либо убирать, либо снижать шанс появления. Склонен к варианту №1, убрать ее вообще так как на сервере сейчас очень мало народу. Вариант с поиском бункера который никак не обозначен на карте и учитывая, то что описание допок у нас практически никто не читает, считаю не лучшим выходом.
