### ISSUE TITLE
Предложение по улучшению баланса оружия.

### ISSUE THREAD

**Issue by AlexVDem** [TEHGAM/ADR#474]
Предлагаю небольшие изменения в части баланса оружия.
1) Убрать их арсенала ПТшника ПП ракеты для Титана, но оставить ПП выстрелы для РПГ.
2) Разрешить Найтсталкер для снайперов (и только для них).
Логика следующая: ночью снайпера резко теряют в эффективности. По сути в ночное можно выходить из слота снайпера, заходить ПТ-шником, брать кучу ракет и выносить любую миссию в одиночку. Тепловик в Титане + страйдер набитый ракетами превращают ПТшника в убер-солдата, а так быть не должно. При  этом, дальность найтсталкера в 1 км. не дает ключевого преимущества снайперу в бою, но позволяет так же эффективно работать ночью.

**Comment by Noart537** [comment]
1) Убирать не вариант, также можно и с миномета подъехать все разколбасить, по логике его тоже прийдется убирать. Тут нужно бороться с техникой, чтобы она вмещала определенное кол-во ракет и стационарных установок.
2) Снайперы в ночное время могут использовать прицел NVG, с которым комфортно работать на расстоянии до 800 метров. Найтсталкеры будут использовать постоянно. В ближайшее время вводить прицелы не планируется. Посомтрим что будет в новом обновлении игры, возможно пересмотрим эту позицию. Осталось не долго.

**Comment by AlexVDem** [comment]
> Найтсталкеры будут использовать постоянно.
Я так не думаю, поскольку у него максимальная поправка на дальность всего 1000м. Ну, как вариант, можно ему отключить режим тепловидения, оставив только ночной и дневной режимы.

**Comment by 12st** [comment]
@AlexVDem Когда был разрешён этот прицел с ним бегал каждый второй снайпер, не надо отвлекаться на замер дистанции и на поиск противника всё есть в самом прицеле. А то что дальше 1000 м не стрельнешь большинству не важно.

**Comment by malashin** [comment]
Я против этих прицелов в первую очередь из-за указания дистанции. То есть не нужно самом больше замеры делать и нет смысла в спотере.

**Comment by AlexVDem** [comment]
То-есть, я правильно понимаю, что наличие управляемых ПП ракет в Титане с тепловизором, которая одним выстрелом кладет целое отделение пехоты за 2.5 км. никого не смущает, а наличие на снайперской винтовке ночного прицела с дальностью 1 км. кого то беспокоит? ;)
Я снайпером много побегал, новички пусть бегают с чем угодно, почему этого кого-то волнует непонятно, преимуществ он не дает особых днем, всеравно дальше 1 км. из него хрен куда попадешь. Я его использовал только для ночной охоты, для дневной лучше чем LRPS ничего нет.

**Comment by 12st** [comment]
@AlexVDem Отделение пехоты она не выносит, боты CSAT имеют хорошую защиту от взрывов, в самом лучшем случае вынесет 3-4 не более и то если они будут находится достаточно близко. Ракет нужно много грузить их долго, мало кто вообще так делает. Тоже самое можно сказать о снайперах сидящих за 1.5 километра от точки с машиной боезапас которой стремится к бесконечности, такому снайперу ничего не угрожает в отличии от пт который стразу привлечёт внимание.

**Comment by ToxaBes** [comment]
>Я снайпером много побегал

Ну видимо немного раз до сих пор хочешь вернуть этот прицел. Игра за снайпера это грамотное владение SOS/LRPS, а не TWS/Nightstalker.

>преимуществ он не дает особых днем

25-кратное увеличение, несколько режимов термовидения, автоматическая индикация цели, автоматический расчет расстояния до цели и все это в одном прицеле. Это ты называешь "не дает особых преимуществ"? 
Может еще пушку от танка в снайперку засунуть чтобы технику выносить? )

**Comment by AlexVDem** [comment]
> 25-кратное увеличение, несколько режимов термовидения, автоматическая индикация цели, автоматический расчет расстояния до цели и все это в одном прицеле

Да что толку, если у тебя линкс, который работает на 2 км, а у тебя прицел, дальность поправок которого 1 км? Понятно, что если найтсталкер повесить на пулемет, то это будет супероружие, а я то говорил сугубо о снайперах, смотрите внимательно что я написал в начале.
То, что ты перечислил, все это есть и в ЛЦУ, для снайпера гораздо более удобно выявить цель и замерить дистанцию через ЛЦУ и потом используя LRPS снять её с 1.5-2 км, чем рисковать собой и подползать к противнику на 1 км., рискуя попасть под огонь техники или снайперов. К тому же, я предложил убрать тепловой режим, оставив только ПНВ в нем.

**Comment by AlexVDem** [comment]
> Отделение пехоты она не выносит, боты CSAT имеют хорошую защиту от взрывов, в самом лучшем случае вынесет 3-4 не более и то если они будут находится достаточно близко. Ракет нужно много грузить их долго, мало кто вообще так делает. 

Да неужели? Не далее как вчера, загрузил штук 30 в страйдер ПП ракет (они легкие, их по 5 штук в рюкзак влезает), поехал на точку и убил за 2 км. штук сорок ботов. Просто ради прикола. Каждый выстрел - минус три -четыре бота за раз. По огневой эффективности против пехоты и по мобильности это круче зенитки получается. Если это мало кто делает - это не аргумент, мало кто из снайперов и Найтсталкером грамотно пользоваться умеет, или LRPS.

**Comment by ToxaBes** [comment]
>Да что толку, если у тебя линкс, который работает на 2 км, а у тебя прицел, дальность поправок которого 1 км? 

Что за бред? **2200** zero max of the Lynx(with LRPS), or the **2400** of the M320(with LRPS)

> то говорил сугубо о снайперах (это всего два слота)

На втором сервере 4 слота, но не суть.

>я предложил убрать тепловой режим, оставив только ПНВ в нем.

Проблема не только в тепловом режиме, 25-кратное приближение позволяет на расстоянии до 1 км рассматривать пломбы на зубах ботов и не требует вообще никаких усилий для попадания в цель. 

>Найтсталкером грамотно пользоваться 

Выбери 2 слова из 3х. Одно слово тут лишнее.

**Comment by AlexVDem** [comment]
> Что за бред? 2200 zero max of the Lynx(with LRPS), or the 2400 of the M320(with LRPS)
Я говорил про найтсталкер, а не про LRPS, у него максимальная дальность поправки - 1 км.

**Comment by RK3QRZ** [comment]
Полностью поддерживаю Алекса!
1. Ракеты ПП давно нужно было убрать, это читерская вещь. Алекс правильно написал, что достаточно нагрузить полный страйдер ракет и в одиночку вынести всю допку. Я неоднократно это наблюдал на сервере, как жестко выносили допки и зевс миссии с помощью ПП ракет. Сравнение ПП ракет с стационарным гранатометом не корректное. ПП ракетами можно работать как минимум в 2 раза дальше. В ТС были неоднократные случаи когда мы ругались из-за того что zed выносил допки тем самым не давая нам поиграть пехотой.
Предлагаю:
а. запретить ПП ракеты или сделать ограничение, чтобы в любую технику можно было загрузить не более 5 ракет.

По поводу найтсталкера тоже не вижу особых причин для паники. Такие прицелы существуют в реальности. Раньше на сервере RW2 прицел был с отключенным тепловизором. Никаких проблем не было, никто ботов не нагибал.
Предлагаю: 
а. вернуть прицел найтсталкер только для снайперов/пехотных снайперов 
б. отключить тепловизор в прицеле

**Comment by ToxaBes** [comment]
Еще раз (на этот раз в последний, надоело): с найтсталкером проблема не только в тепловизоре, но и во встроенном **валлхаке** (наведите на забор за которым противник или в кусты и на прицеле отобразятся метки найденной цели даже если его не видно). Я не видел вариантов отключения этой фичи (может и есть - надо искать). Паники нет - просто этот прицел дает необоснованные преимущества снайперам даже с отключенным тепловидением.

**Comment by RK3QRZ** [comment]
Специально зашел на сервер проверить. Да, такая шляпа есть, работает она глючно и показывает не всех пехов! По какому принципу она работает я х.з, из 20 пехов мне показала 2, плюс показала пустой танк, а технику которая ездила по точке не показала, плюс наводится на трупы. Короче это все фигня, никаких существенных и необоснованных преимуществ в этом прицеле я не увидел, скорее это глючная хрень которая сбивает с толку.

**Comment by ToxaBes** [comment]
Попробуй поводить этим прицелом по густому лесу где есть боты. Не видя их ты будешь знать их расположение. Прицел показывает текущее положение ботов, если они ушли за холм то показывает последнее известное положение, также показывает всю горячую технику (двигатель запущен) не важно есть в боты или нет. При использовании командиром отделения и включенной командирке вообще становится убер вещью.

>Короче это все фигня

Да, такая фигня что даже на exile серверах постоянно поднимают вопрос о том чтобы его выпилить нафиг ибо это чит. Ты просто с ним не разобрался.

**Comment by AlexVDem** [comment]
Все просто. В сети действительно нет описания как это работает, отсюда и мифы о wallhack и обвинения в читерстве и пр. )))
На самом деле, найсталкер не показывает противника, если вы его не видели. Для того, чтобы противник начал отслеживаться, надо подержать на противнике центральную метку, хотя бы полсекунды. После этого, при наведении на противника начинает показываться рамка из наклонных линий, означающая что противник был зафиксирован.
Это же рамка показывается, если противник за препятствием. Но! препятствие - это только трава и кусты. За забором, если противник хотя бы частично не виден, рамка не показывается. Аналогично и за рельефом местности прицел не видит противника, рамка пропадает. Это принцип работы фиксации цели по частичному тепловому излучению, которое немного проникает сквозь траву и кусты. Нет прямой видимости - нет и рамки.
Прицел правда иногда глючит, но только в том плане, что делает хуже, а не лучше! Т.е. не оттображает, что должен показывать, а не показывает что не должен. ;)))
Короче, нет предмета для волнений, просто отключить тепловик ему, и можно пользоваться как обычным ночным прицелом с хорошей кратностью. Тем более, что прицелы с дальномером в реальной жизни существуют, правда работают немного иначе, но результат такой же. Сам такой хотел купить, но больно дорого. 
Оффтопик: есть вообще космос! Вот такое например: https://www.youtube.com/watch?v=Pmteh_NChOQ оно само по цели стреляет, даже нажимать на спусковой крючок не надо.

**Comment by ToxaBes** [comment]
>На самом деле, найсталкер не показывает противника, если вы его не видели.

Показывает если противник попал на экран монитора, даже за деревьями или забором. При этом ты сам его можешь не заметить. Достаточно просто поводить бошкой туда сюда и прицел (не ты) заметит всех противников. Это и есть валлхак.

Я только сейчас понял что пытаюсь объяснить очевидную вещь 2м снайперам которые изначально были против убирания это прицела )

**Comment by AlexVDem** [comment]
> Показывает если противник попал на экран монитора, даже за деревьями или забором. При этом ты сам его можешь не заметить. Достаточно просто поводить бошкой туда сюда и прицел (не ты) заметит всех противников. Это и есть валлхак.

Попробуй повторить этот эффект. Я как то потратил время на то, чтобы понять, как эта штука работает, так вот ничего из того, что ты написал не существует. Если просто поводить прицелом из  стороны в сторону - он ничего не покажет. Ну, по крайней мере год назад так было, если БИС ничего не поменяли.
Вечером может быть видео даже запишу, как эта штука в самом деле работает.

**Comment by ToxaBes** [comment]
Без прицела поводи медленно бошкой туда сюда, потом поводи также с прицелом. Все. Автоспот выполнен.

**Comment by RK3QRZ** [comment]
Я сейчас на сервере взял через зевс прицел и телепортнулся на точку. Из 30 пехов (считал) ни на одном не сработало. Сработало только на перевернутом пустом танке.

**Comment by ToxaBes** [comment]
Странно, у вас не работает а у меня работает. Я вечером попробую, давно с ним не бегал.

**Comment by RK3QRZ** [comment]
Вот смотрите как работает https://youtu.be/xo9x4uKTavM .Лично я не играю когда на сервере ночь (не хочу добивать свое зрение), поэтому мне пофиг на этот прицел. Но я не вижу причин не добавить его игрокам.

**Comment by ToxaBes** [comment]
Термозрение и встроенный дальномер показан хорошо. Я вечером постараюсь записать видео об остальных его фичах.

**Comment by AlexVDem** [comment]
Скинул видео как это работает у МЕНЯ. Если у вас это работает иначе - значит у вас другая Арма, наверное! 
Обратите внимание, что указатель цели не работает через препятствие, через стены, заборы и двери, только через кусты и траву. Через рельеф местности тоже не работает, на видео этого нет, просто поверьте мне на слово! ;)
Через кусты работает, но, как я уже сказал, и как видно на видео, не сразу, для этого надо сначала уведить цель целиком. В целом, никакого особого преимущества этот режи не дает, не понимаю зачем эту фичу вообще сделали.

https://www.youtube.com/watch?v=7hMVlqGBEVM

**Comment by ToxaBes** [comment]
Это видео делает меня грустить: https://youtu.be/k6XgatQjmSM (подписываемся на канал, ставим лайки...)

На видео: 
* тест деревьев - прицелу вообще пофиг на них
* тест заборов - есть если виден хоть 1 пискель противника на экране (который вы не видите), то не важно есть забор или нет, наведись на забор - прицел все покажет

И вы на полном серьезе рассказываете что это не дает преимущества?

**Comment by RK3QRZ** [comment]
У тебя Арма не правильная просто, не лицуха наверное :) У меня так не работает, короче ладно если такая шляпа, то бог с ним тогда.

**Comment by ToxaBes** [comment]
>У тебя Арма не правильная просто, не лицуха наверное :)

А Steam содрал как за лицуху )

**Comment by AlexVDem** [comment]
Преимущество кого перед кем? Снайпера с 5 зарядным Линкс в густой растительности без тепловизора с одной лишь рамкой, пытающегося понять, где там в лесу пиксел бота? Да не смешите. Лучше уж взять ЛЦУ, посмотреть где светит и через LRPS выстрелить туда с дистанции в 1.5 км., чем через найтсталкер пытаться выцелить наугад. А проще вообще туда ППшной ракетой из титана шмальнуть, вообще не парясь про дистанцию.
Единственное, где будет найтсталкер полезен - это ночной бой, тут да, даст хороший шанс снайперу, гораздо удобнее вместо RCO.

**Comment by ToxaBes** [comment]
>Преимущество кого перед кем?

Все, я больше не отвечаю в этой теме. Это уже за гранью.

**Comment by AlexVDem** [comment]
Ну ладно. Просто ты оцениваешь, судя по твоим постам, преимущество игрока надо ботами, я же оцениваю преимущество одного класса игрока над другим. Название темы погляди. Поэтому, пофигу, что появляется рамка над ботами, тем более, как я уже написал, существенного повышения эффективность снайпера это не даст. Если у ПТ-шника не отобрать ПП ракеты, то таким образом как я написал можно хотя бы повысить эффективность снайперов ночью, а то они со своим дальнобойным линсксом 5зарядным и винтовкой весом как чугунный мост становятся вообще ночью убогими. Вот об том речь. А лучше сделать и то и это.

**Comment by tym32167** [comment]
Всем привет.
1. Очевидно, что нейтсталкер - убер прицел. Я, как заядлый кемпер, подтверждаю, что с ним можно вести эффективный отстрел на расстоянии до 1.5 км (независимо от того, что сам прицел выставляет поправку на 1 км). 
2. Как кемпер я обычно гружу машину патронами и могу относительно свободно на ней передвигаться, не подходя близко к точке. Также наряд снайпера, помимо аптечки, оружия и доп прицелов, способен вмещать порядка 25 обойм линкс или 30 обойм LRR. Да, бегать будешь медленно, но на расстоянии 1.5 км от противника это не сильно важно.
3. Нейтсталкер + Линкс позволяет намного проще уничтожать легкобронированные движущиеся цели, именно приводить в негодность легкую технику врага, уничтожать стрелков и водителей вражеских ЗСУ, приводить орудия ЗСУ в негодность, приводить в негодность пулеметы на танках, при должной сноровке выводить из строя вражеские вертолеты. Легкость это в основном в том, что нейтсталкер имеет встроенный дальномер, а значит для движущийся цели нам не надо переключаться между дальномером и прицелом, то есть техника не успеет далеко отъехать\отлететь, как мы уже знаем расстояние, можем оперативно выставить поправку на дальность в прицеле и сделать более меткий выстрел. 
4. Благодаря наличию коллиматора (хоть и не очень удобного), становится возможным использовать прицел и в ближнем бою.
В связи с вышеизложенными фактами, Нейсталкер становится убер прицелом на расстояниях 500-1500 метров, что уже проверено опытом и доказано 10 раз, когда любой боец, способый взять нейтсталкер, брал нейтсталкер. Также есть возможность вести бой на короткой дистанции. Таким образом, снайперу больше не будет необходимости брать с собой ни целеуказатель, ни корректировщика, ни прицелы ближнего боя, и при этом он будет способен стрелять гораздо точнее по движущимся целям, и гораздо оперативней, так как нет необходимости в переключениях между дальномером и прицелом. Это сделает снайпера практически машиной смерти, и дает преимущество как перед ботами, так и перед другими игроками.

**Comment by tym32167** [comment]
Справедливости ради, добавлю, что ночью снайперу действительно делать практически нечего. Как уже было отмечено, NVS позволяет вести огонь на расстоянии до 800 метров, что по эффективности можно сравнить даже с DMS, если вести огонь днем. Но как часто снайперы играют ночью на втором? Я, хотя давно не играл, припоминаю, что ночь на втором сервере - событие редкое.

**Comment by RK3QRZ** [comment]
Он убер как ты говоришь только из валлхака и не болеее.
1. Лично мне намного удобнее вести огонь на 1,5 км с прицелом LRPS
2. Хороший снайпер по может работать по движущейся цели замерив расстояние лишь один раз, далее просто корректирует огонь.
3. Коллиматор в найтсталкере полное говно.
4. Ни разу не видел чтобы снайпер брал корректировщика.
5. Кроме валлхака никаких преимуществ в данном прицеле не вижу, при условии отключенного тепловизора. Еще раз повторю: такие прицелы есть в реале, это не выдумка.

**Comment by tym32167** [comment]
1. Я и не спорил с этим. Однако, попробуй это сделать ночью\вечером\при плохой видимости. Днем, при ясной погоде да LPRS. Только попробуй с этого прицела пристрелить кого то, кто ближе 100 метров. LPRS - только для дальних дистанций. Нейтсталкер - для разных дистанций.
2. Хороший - может быть. Я играю 2 года и я, при наличии выбора, на расстояниях 500-1000 возьму нейсталкер. Потому что с цифрами точнее, чем замерять на глаз. Видимо, я не оч хороший снайпер. Как и большинство снайперов, что играют на сервере.
3. Не отрицал. Зато он есть и им можно пользоваться.
4. Я так иногда играл. Многие игроки, что со мной играли, если были поблизости, то сами меня наводили на цели. 
Повторю ещё раз - нейсталкер - это универсальный прицел. Он может быть использован для близких (<200 метров), средних (200-500 метров), дальних (500-1500 метров) расстояний, он может быть использован как ночью, так и днем, даже в городских боях. Да, для близких лучше коллиматор, для средних можно расстояние на глаз определять и стрелять с ДМС, для дальних можно LPRS\SOS, для ночи можно NVS для определения дальности и теплака можно целеуказатель. Но зачем это все, если все это вместе есть в одном прицеле? И при этом у снайпера с нейсталкером уйдет меньше времени на обнаружение цели, определения расстояния и выстрел, чем у снайпера с другим прицелом и целеуказателем. То, что ты не видишь этих преимуществ, не означает, что их нет.

**Comment by RK3QRZ** [comment]
И еще. Преимущество над ботами как ты говоришь, это когда ПТшник может возить с собой более 50 ракет ПП и выносить в одно лицо любую допку. Когда пехота может подсвечивать из ЛЦУ пилотам боевых вертолетов  врагов. Это то за что вы все так дружно проголосовал,  но еще не введено на сервер. Вот это настоящее преимущество над ботами. Все это даже ни в какое сравнение нельзя поставить с найтсталкером.

**Comment by tym32167** [comment]
Причем тут ПТ, если мы обсуждаем нейтсталкер? Тут обсуждали преимущества нейтсталкера. Я их указал. То, что есть ещё другие вещи с преимуществами я и не спорил. Ты что то хочешь доказать мне или к чему ты ведешь? С чем из моих слов ты не согласен?
Вводить или нет нейсталкер - решать не мне. Для этого есть голосования. Ты тоже там участвуешь и твой голос учитывается.

**Comment by RK3QRZ** [comment]
Лично мне он нафиг не нужен. Если у меня будет выбор между найтсталкером и LRPS, то я выберу LRPS. И прихвачу еще ARCO. И вообще, если не валлхак,  то я отдал бы этот прицел только пехотному снайперу.

**Comment by AlexVDem** [comment]
Ну, мне кажется это в корне неверно, если нет ночных миссии. Они тоже интересные, пусть хоть и короткое время, как например это сделано на первом сервере. Я бы с удовольствием бегал ночью, будь у меня нормальный прицел, а бе него приходится подходить на 500 метров, где тебя моментом снимает техника или суперпехота, а если к тому же миссия далеко от базы и ты один никакого желания ехать опять туда нет.
Если бегаю в одиночку, то беру снайпера, если группе то могу и пулеметчиком зайти.

**Comment by RK3QRZ** [comment]
Это я ответил тебе на твои слова о преимуществе над ботами. Для сравнения.Реальных вещей не замечаем, зато говорим о преимуществе над ботами.

**Comment by tym32167** [comment]
Я понял, чего вы хотите. Единственное, не надо никого вводить в заблуждения, говоря, что нейтсталкер не дает преимуществ. Ещё как дает. 
И зачем эти передергивания в дискуссии? Хочешь обсудить реальные вещи - сделай отдельный тред, давай обсудим. Видишь другие проблемы? - у нас есть тред на форуме с предложениями, или пиши предложения здесь отдельным тикетом. 
А то получается, Алекс вводит своё предложение, и вместо его обсуждения начинается демагогия на другие темы, хоть и релевантные данной теме, но другие. Так и получается, что ничего не происходит, так как на каждое предложение начинаем говорить о смысле жизни и о том, как все стало плохо. Треды с предложениями - для обсуждения предложений. Давайте этим тут и заниматься, а не разглагольствовать.

**Comment by tym32167** [comment]
И если ты не заметил, я не высказывал своего мнения относительно предложения Алекса, так как я не играл на сервере уже почти 4 месяца. Я лишь внес ясность в положение с прицелом, чтобы те, кто больше меня знаком с состоянием сервера, могли принять взвешенное решение, основанное на достоверной информации.

**Comment by tym32167** [comment]
Алекс, давай поглядим как сейчас есть. Насколько я понял, на сервере в данный момент нет ночных миссий и ночью почти никто не играет. Я вообще не припомню случаев, когда ночь на сервере не отпугивает игроков. Имеет и смысл вводить вводить нейсталкер, если ты его предлагаешь для ночных миссий, которых нет?
По поводу ПП снарядов подтверждаю, это было проблемой ещё когда я играл. Собственноручно выносил пачку ботов, используя ПТ-снайперку и технику как хранилище снарядов.

**Comment by RK3QRZ** [comment]
Я еще раз повторяю! Сказанное мною было ответом на твое утверждение о преимуществе над ботами. Вижу что правда тяжело воспринимает. Глупо вообще говорить о преимуществе не видя его там где оно реально есть.

**Comment by tym32167** [comment]
Еще раз повторяю, я в курсе, что у игрока есть другие преимущества над ботами. Но это не отменяет тот факт, что добавление нейтсталкера этих преимуществ добавит.

**Comment by RK3QRZ** [comment]
Добавление найтсталкера пехотным снайперам никаких существенных преимуществ игрокам не добавит.

**Comment by 12st** [comment]
Учитывая, что пехотные как раз таки и стреляют на дистанцию найтсталкера, не дальше.

**Comment by tym32167** [comment]
Обычные снайперы и другие специальности также могут стрелять на дистанции до 1000 метров, перед ними у пехотных снайперов не будет преимуществ?

**Comment by AlexVDem** [comment]
>  Имеет ли смысл вводить вводить нейсталкер, если ты его предлагаешь для ночных миссий, которых нет?

Если ночных миссии нет - то и смысла в этом прицеле нет. Но ночь там иногда бывает, дадим прицел снайперам - появляется дополнительный плюс к игре ночью.  Учитывая тотальный дефицит игроков в последнее время на 2-м сервере (да и на первом их не так уж и много, в основном 5-10 постоянных), не вижу причин этого не сделать. Если это позволит как то разнообразить игру и привлечь игроков - то почему бы нет?
Просто такая игра за снайпера ночью (без теплака в найтсталкере) - это дополнительный режим, довольно интересный, чем тупо гасить ботов из титана за пару км.

**Comment by RK3QRZ** [comment]
Пехотный снайпер стреляет дальше чем обычный пехотинец и имеет соответствующий прицелы. Пострелять на 1000 метров используя RCO или ARCO я посмотрю каков будет твой результат за 1 час игры. И загугли кто на какие дистанции стреляет в современных ВС.

**Comment by RK3QRZ** [comment]
В общем пока есть валлхак данная тема про найтсталкер считаю не стоящей для обсуждения.

P.S. Лучше обратите внимание на то где есть реальное существенное преимущество игроков над ботами.

**Comment by tym32167** [comment]
Я стреляю на дистанцию до 1000 с DMS. Насколько я помню, он разрешен для всех.

**Comment by Noart537** [comment]
Создам голосование, там и решится судьба прицела. Тему закрываю.

**Comment by AlexVDem** [comment]
Ок. Предлагаю соломоново решение. Есть 1-й сервер где запрещены ЛЦУ, вид от 3-го лица, найтсталкеры, но разрешены ПП ракеты, так пусть будет 2-й сервер, где разрешено это все (но не все вообще) но запрещены ПП ракеты. Так каждый сам для себя выберет, где ему воевать, и все будут счастливы. ;) Демократия.
