### ISSUE TITLE
Модули не удаляются

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#475]
Добавить таймер удаления для модулей.

**Comment by malashin** [comment]
Я на первый сервер весь скрипт переделал. Можно его взять. После сброса модуля он удаляется через 15 минут.

https://github.com/ToxaBes/ADR-Spec-Ops/blob/master/co30_ADR_Spec_Ops.Altis/scripts/supplyCrate.sqf

**Comment by Noart537** [comment]
ок

**Comment by malashin** [comment]
Вот на это стоит обратить внимание
https://github.com/ToxaBes/ADR-Spec-Ops/blob/master/co30_ADR_Spec_Ops.Altis/scripts/supplyCrate.sqf#L36

Делал, чтобы модули с патронами для техники кончались и загружали только 12 ракет в сэндсторм. Аналогичные оперции проделываются и с грузовиком патронов и на сервисе техники. Сервис раньше вообще карго патроны не заряжал.
