### ISSUE TITLE
Переход на Таноа

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/ADR#487]
###  Карта
- [x] Выбрать местоположение базы.
- [x] Выбрать места основных миссий.
- [x] Выбрать места дополнительных миссий.
- [x] Выбрать место для наградной техники.
- [x] Выбрать место для гаупвахты.
- [x] Разместить сервисы техники.
- [x] Обустройство базы.
- [x] Выбрать место для модулей.
- [x] Выбрать место для лодок.

### Техника\пехота
- [x] Пересмотреть и разместить технику на базе.
- [x] Пересмотреть список наградной техники.
- [x] Добавить новые модули.
- [x] Обновить список разрешенной техники для пилотов.
- [x] Добавить новые классы противнику.
- [x] Добавить новую технику противнику.
- [x] Рассмотреть обновление игровых тушек на базе.

### Снаряжение
- [x] Обновить Арсенал.
- [x] Обновить скрипт ограничения оружия.
- [x] Рассмотреть возможность добавления тепловизоров без дальномеров. (TVG NV)
- [x] Добавить новое снаряжение в модули.

**Comment by AlexVDem** [comment]
Местоположение мне кажется лучше всего будет на юго-восточном острове, тогда можно сделать и миссию с захватом центрального аэродрома и ближние и дальние миссии. Да и мост есть на центральный остров, можно сделать миссию с захватом и освобождением моста. ;) В центре местоположение базы будет неудачное, т.к. до любой точки карты получается слишком близко.
Тяжелую технику таскать на острова нет особого смысла, т.к. они очень маленькие для нее.

**Comment by Noart537** [comment]
Согласен с тем что в центре будет очень близко, но друго-го подходящего места на мой взгляд нет. На юго-восточном островке, соглашусь норм местечко. Но приглядись какой там городок, и вода рядом, мостики, можно прямо на лодках подплыть в центр города. Не хотелось бы исключать такое место из заданий. Сделав там базу, мы теряем один из городов, в которых бы могли воевать. остальные 2 острова не соеденены с большим островом, что делает их не очень удобными для базы. И не попользуешься тяжелой техникой. (если только не сделать скрипт перемещения техники между портами). На северной полосе маловато местечка, да и порт рядом, где могли бы тоже миссию разместить. Вот и остается только в центре карты делать.

**Comment by AlexVDem** [comment]
Ну, есть плюсы и минусы обоих решений. Смотри, кстати, насчет скрипта, очень удачная идея. На островах есть паром, т.е. спуск к воде. Я сначала не понял, для чего это, а как ты про скрипт написал - я сразу ухватился за эту идею, это же как раз для парома решение. Подъезжаешь к парому, выбираешь из меню пункт "Переправа" и ты на другом острове сразу (или за какое то время).

**Comment by Noart537** [comment]
Я вот тоже увидел на карте переправа, и пришла такая идея. От разработчиков врятле дождешься кораблика-переправы) Еще была идея мост построить. =) 
Все же аэропорт будет не так интересен в захвате (открытая местность), чем город. Поэтому оставлю пока в центре. Рассматриваю еще возможность на северо-западном островке. Если делать скрипт в портах, то должно получиться не плохо.

**Comment by AlexVDem** [comment]
AW I&A TANOA - если любопытно поковырять.
[co60_AW_Invade_Annex_2_86J.Tanoa.zip](https://github.com/TEHGAM/ADR/files/324430/co60_AW_Invade_Annex_2_86J.Tanoa.zip)

**Comment by Noart537** [comment]
Спасибо, посмотрю.
